force-app/main/default/objects/Lightning_Actions_Configuration__mdt/Lightning_Actions_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Lightning Actions Configuration</label>
    <pluralLabel>Lightning Actions Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lightning_Actions_Configuration__mdt/fields/Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Button_Label__c</fullName>
    <label>Button Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lightning_Actions_Configuration__mdt/fields/Class_Method__c.field-meta.xml
<CustomField>
    <fullName>Class_Method__c</fullName>
    <label>Class Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lightning_Actions_Configuration__mdt/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lightning_Actions_Configuration__mdt/fields/Show_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Show_Record_Types__c</fullName>
    <description>Use this field to show button on which record type</description>
    <inlineHelpText>Add Comma Separate Record Type API Name</inlineHelpText>
    <label>Show Record Types</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lightning_Actions_Configuration__mdt/fields/Validation_Method__c.field-meta.xml
<CustomField>
    <fullName>Validation_Method__c</fullName>
    <label>Validation Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lightning_Actions_Configuration__mdt/fields/Validation_Required__c.field-meta.xml
<CustomField>
    <fullName>Validation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Validation Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomLWCActionPanelController.cls
public with sharing class CustomLWCActionPanelController {
    
    @AuraEnabled
    public static ISD_CreateLightningServerResponse getActions(String sObjectApiName) {

        Boolean bIsSuccessful = true;
        Map<String, object> mapErrorInfo = new Map<String, object>();
        Map<String, object> mapObjectData = new Map<String, object>();

        //Query Metadata to fetch actions for this object
        List<Lightning_Actions_Configuration__mdt> lstActions = new List<Lightning_Actions_Configuration__mdt>();
        
        try {
            if(sObjectApiName != null){
                lstActions = [SELECT Id, MasterLabel, Button_Label__c,Show_Record_Types__c, Class_Method__c, Class_Name__c, Component_Type__c, Object_API_Name__c,   
                        Validation_Method__c, Validation_Required__c 
                        FROM Lightning_Actions_Configuration__mdt WHERE Object_API_Name__c =: sObjectApiName];
            }
            
            
            mapObjectData.put('lstConfigs', lstActions);
        } catch(Exception oEx) {
            bIsSuccessful = false;            
        }
        return new ISD_CreateLightningServerResponse(bIsSuccessful, mapErrorInfo, mapObjectData);
    }
}