force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Answers to all questions are stored here.</description>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text__c</fullName>
    <description>The actual answer text to a question is saved here.</description>
    <label>Answer Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/AssociatedQuestion__c.field-meta.xml
<CustomField>
    <fullName>AssociatedQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated Question</description>
    <label>Associated Question</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CLQ_Standard_Detail__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Question</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CLQ_Standard_Detail__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Association to a Program Transaction record.</description>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Rating_Number__c.field-meta.xml
<CustomField>
    <fullName>Rating_Number__c</fullName>
    <label>Rating/Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_ByPassUtil__c.field-meta.xml
<CustomField>
    <fullName>CLQ_ByPassUtil__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassUtil</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Email__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Email__c</fullName>
    <label>Program Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <label>Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Child_Care_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Child_Care_Center</fullName>
    <active>true</active>
    <description>VDSS - Child Care Centers</description>
    <label>Child Care Center</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <formula>TEXT(CLQ_Program__r.CLQ_Program_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/CLQ_Standard_Detail__c.object-meta.xml
<CustomObject>
    <label>Standard Detail</label>
    <nameField>
        <label>Standard Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_Met_Not_Met__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Met_Not_Met__c</fullName>
    <description>This field maps which possible responses for each Annual Report question result in Met or Not Met</description>
    <inlineHelpText>This field maps which possible responses for each Annual Report question result in Met or Not Met</inlineHelpText>
    <label>Met/Not Met</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_ParentQuestion__c.field-meta.xml
<CustomField>
    <fullName>CLQ_ParentQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Question</description>
    <label>Parent Question</label>
    <referenceTo>CLQ_Standard_Detail__c</referenceTo>
    <relationshipLabel>Parent Questions</relationshipLabel>
    <relationshipName>Standard_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_PossibleResponses__c.field-meta.xml
<CustomField>
    <fullName>CLQ_PossibleResponses__c</fullName>
    <description>Possible responses for the question.</description>
    <label>Possible Responses</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_QuestionType__c.field-meta.xml
<CustomField>
    <fullName>CLQ_QuestionType__c</fullName>
    <description>Type of question.</description>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Options</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Yes-No</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
            <value>
                <fullName>Single Option</fullName>
            </value>
            <value>
                <fullName>Instruction</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/Possible_Points__c.field-meta.xml
<CustomField>
    <fullName>Possible_Points__c</fullName>
    <label>Possible Points</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/Possible_Ratings__c.field-meta.xml
<CustomField>
    <fullName>Possible_Ratings__c</fullName>
    <label>Possible Ratings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/recordTypes/CLQ_Question.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Question</fullName>
    <active>true</active>
    <description>All questions will be stored here</description>
    <label>Question</label>
</RecordType>

force-app/main/default/objects/QuestionToInclude__c/QuestionToInclude__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>QuestionToInclude</label>
</CustomObject>

force-app/main/default/classes/CLQ_AnswerTriggerHandlerTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_AnswerTriggerHandlerTest
** Description      : 
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A	            1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isparallel = true)
public class CLQ_AnswerTriggerHandlerTest {
    /* @testSetup //Added method for Task - 11615
public static void setExecuteControlSetting()
{
CLQ_UnitTestUtilities.setExecuteControlSetting();
}*/
    @IsTest
    public static void testAnswerTriggerHandlerMethod()
    {
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            // testing sp8
            
            
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            CLQ_Program__c clqProg=CLQ_Test_Util.getCLQProgram();
            clqProg.CLQ_Program_Status__c='Open';
            clqProg.CLQ_ByPassUtil__c = true;
            clqProg.CLQ_Program_Email__c = 'test@test.com';
            clqProg.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert clqProg;
            
            CLQ_Program_Transaction__c cpt = CLQ_Test_Util.getCLQProgramTransaction();
            cpt.CLQ_Program__c=clqProg.id;        
            insert cpt;
            
            Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
            CLQ_Standard_Detail__c standardDetail = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'Test', CLQ_PossibleResponses__c = 'Test;Yes;No', 
                                                                               Possible_Points__c = '3;4;5',Possible_Ratings__c = '1;2',CLQ_Met_Not_Met__c='Met',CLQ_QuestionType__c = 'Picklist');
            insert standardDetail;
            
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Answer__c ansOld = [select Answer_Text__c, Program_Transaction__c from Answer__c where id=:ans.Id];
            ansOld.Program_Transaction__c = cpt.Id;
            ansOld.Answer_Text__c = 'Yes';
            update ans;
            update ansOld;
            delete ans;
            Test.stopTest();  
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testAnswerTriggerHandlerMethod1()
    {
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            Test.startTest();
            
            
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            CLQ_Program__c clqProg=CLQ_Test_Util.getCLQProgram2();
            clqProg.CLQ_Program_Email__c = 'test@test.com';
            clqProg.CLQ_Program_Status__c='Open';
            clqProg.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert clqProg;
            
            CLQ_Program_Transaction__c cpt = CLQ_Test_Util.getCLQProgramTransaction();
            cpt.CLQ_Program__c=clqProg.id;
            insert cpt;
            
            Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
            CLQ_Standard_Detail__c standardDetail1 = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'Test', CLQ_PossibleResponses__c = 'Test;Yes;No',Possible_Ratings__c = '1;2',
                                                                                CLQ_QuestionType__c = 'Picklist');
            insert standardDetail1;
            
            Answer__c ans1 = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 40, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail1.Id, Program_Transaction__c = cpt.Id);
            insert ans1;
            
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testAnswerTriggerHandlerMethod2()
    {
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            Test.startTest();
            
            
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            CLQ_Program__c clqProg=CLQ_Test_Util.getCLQProgram2();
            clqProg.CLQ_Program_Email__c = 'test@test.com';
            clqProg.CLQ_Program_Status__c='Open';
            clqProg.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert clqProg;
            
            CLQ_Program_Transaction__c cpt = CLQ_Test_Util.getCLQProgramTransaction();
            cpt.CLQ_Program__c=clqProg.id;
            insert cpt;
            Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
            CLQ_Standard_Detail__c standardDetail = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'Test', CLQ_PossibleResponses__c = 'Test;Yes;No', Possible_Points__c = '3;4;5',
                                                                               Possible_Ratings__c = '1;2',CLQ_QuestionType__c = 'Picklist');
            insert standardDetail;
            
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 60, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail.Id, Program_Transaction__c = cpt.Id);
            insert ans;
            ans.Answer_Text__c = 'Yes';
            
            
            
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    static void testAnswerTriggerHandlerMethod3()
    {
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            
            Test.startTest();
            
            
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
            insert configRecord; 
            
            CLQ_Program__c clqProg=CLQ_Test_Util.getCLQProgram2();
            clqProg.CLQ_Program_Email__c = 'test@test.com';
            clqProg.CLQ_Program_Status__c='Open';
            clqProg.RecordTypeId = Schema.Sobjecttype.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Child_Care_Center').getRecordTypeId();
            insert clqProg;
            
            CLQ_Program_Transaction__c cpt = CLQ_Test_Util.getCLQProgramTransaction();
            cpt.CLQ_Program__c=clqProg.id;        
            insert cpt;
            Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
            CLQ_Standard_Detail__c standardDetail = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'Test', CLQ_PossibleResponses__c = 'Test;Yes;No', Possible_Points__c = '3;4;5',
                                                                               Possible_Ratings__c = '1;2',CLQ_QuestionType__c = 'Picklist');
            insert standardDetail;
            
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 60, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail.Id, Program_Transaction__c = cpt.Id);
            insert ans;
            ans.Answer_Text__c = 'Yes';
            
            
            
            Test.stopTest();  
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    static void setAnswerValuesTest()
    { 
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            CLQ_Program_Transaction__c ProgramTransaction2 = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'Application - FCC');
            CLQ_Program_Transaction__c ProgramTransaction = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'SUTQ - Initial Registration');//Application - FCC
            
            
            Test.startTest();
            Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
            CLQ_Standard_Detail__c standardDetail2 = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'SDL-00034', CLQ_PossibleResponses__c = 'Test;Yes;No', Possible_Points__c = '3;4;5',Possible_Ratings__c = '1;2',
                                                                                CLQ_QuestionType__c = 'Picklist');
            insert standardDetail2;
            CLQ_Standard_Detail__c standardDetail = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'SDL-00035', CLQ_PossibleResponses__c = 'Test;Yes;No', Possible_Points__c = '3;4;5',Possible_Ratings__c = '1;2',
                                                                               CLQ_QuestionType__c = 'Picklist',CLQ_ParentQuestion__c = standardDetail2.Id);
            insert standardDetail;
            
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'test',Points__c = 60, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail.Id, Program_Transaction__c = ProgramTransaction.Id);
            Answer__c ans2 = new Answer__c(Name = 'Test23',Answer_Text__c= 'test23',Points__c = 60, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail2.Id, Program_Transaction__c = ProgramTransaction.Id);
            
            CLQ_AnswerTriggerHandler hand = new CLQ_AnswerTriggerHandler(null,null,null,null,
                                                                         false,false,false,false,
                                                                         false,false,false,1);      
            hand.updateProgramTransaction(new list<Answer__c> { ans}, null);
            hand.updateProgramTransaction(new list<Answer__c> { ans2}, null);
            
            insert ans;
            insert ans2;
            ans.Answer_Text__c = 'Yes';
            ans2.Answer_Text__c = 'Yes';
            Test.stopTest();  
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    
    //Anil added method to test rating and points for edge case scenario.
    @IsTest
    static void testUpdateRatingPoint(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            //prepareData();
            CLQ_Standard_Detail__c standardDetail=[select id,Name from CLQ_Standard_Detail__c where name='SD-00066' limit 1];
            CLQ_Program_Transaction__c cpt=[select id,Name from CLQ_Program_Transaction__c limit 1];
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testUpdateRatingPoint1(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            //prepareData();
            CLQ_Standard_Detail__c standardDetail1=[select id,Name from CLQ_Standard_Detail__c where name='SD-00067' limit 1];
            CLQ_Program_Transaction__c cpt=[select id,Name from CLQ_Program_Transaction__c limit 1];
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail1.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testUpdateRatingPointWithMultipleAnswer1(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            //prepareData();
            CLQ_Standard_Detail__c standardDetail1=[select id,Name from CLQ_Standard_Detail__c where name='SD-00067' limit 1];
            CLQ_Program_Transaction__c cpt=[select id,Name from CLQ_Program_Transaction__c limit 1];
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test;Test1',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail1.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testUpdateRatingPointWithMoreThan2Answer(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            //prepareData();
            CLQ_Standard_Detail__c standardDetail1=[select id,Name from CLQ_Standard_Detail__c where name='SD-00067' limit 1];
            CLQ_Program_Transaction__c cpt=[select id,Name from CLQ_Program_Transaction__c limit 1];
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test;Test1;Test2',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail1.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testUpdateRatingPoint2(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            //prepareData();
            CLQ_Standard_Detail__c standardDetail2=[select id,Name from CLQ_Standard_Detail__c where name='SD-00076' limit 1];
            CLQ_Program_Transaction__c cpt=[select id,Name from CLQ_Program_Transaction__c limit 1];
            Answer__c ans = new Answer__c(Name = 'Test123',Answer_Text__c= 'Test123',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail2.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    @IsTest
    public static void testUpdateRatingPoint3(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            //prepareData();
            CLQ_Standard_Detail__c standardDetail3=[select id,Name from CLQ_Standard_Detail__c where name='SD-00170' limit 1];
            CLQ_Program_Transaction__c cpt=[select id,Name from CLQ_Program_Transaction__c limit 1];
            Answer__c ans = new Answer__c(Name = 'Test124',Answer_Text__c= 'Test124',Points__c = 30, Rating_Number__c = 2,AssociatedQuestion__c = standardDetail3.Id, Program_Transaction__c = cpt.Id);
            Test.startTest();
            insert ans;
            Test.stopTest();   
            system.assertEquals(True, 1==1,'Testing');
        }
    }
    
    static CLQ_Program_Transaction__c cpt = new CLQ_Program_Transaction__c();
    static CLQ_Standard_Detail__c standardDetail = new CLQ_Standard_Detail__c();
    static CLQ_Standard_Detail__c standardDetail1 = new CLQ_Standard_Detail__c();
    static CLQ_Standard_Detail__c standardDetail2 = new CLQ_Standard_Detail__c();
    static CLQ_Standard_Detail__c standardDetail3 = new CLQ_Standard_Detail__c();
    @testSetup
    public static void prepareData(){
        CLQ_UnitTestUtilities.setExecuteControlSetting();
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
        
        CLQ_Program__c clqProg=CLQ_Test_Util.getCLQProgram();
        clqProg.CLQ_ByPassUtil__c = true;
        clqProg.CLQ_Program_Email__c = 'test@test.com';
        CLQ_ProgramTriggerHandler.BypassTrigger = true;
        insert clqProg;
        CLQ_ProgramTriggerHandler.BypassTrigger = false;
        
        cpt = CLQ_Test_Util.getCLQProgramTransaction();
        cpt.CLQ_Program__c=clqProg.id;
        CLQ_Program_TransactionTriggerHandler.BypassTrigger= true;
        insert cpt;
        CLQ_Program_TransactionTriggerHandler.BypassTrigger= false;
        
        Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
        
        list<CLQ_Standard_Detail__c> standardDetails = new list<CLQ_Standard_Detail__c>();
        standardDetail.RecordTypeId=questionRecordTypeId; 
        standardDetail.Name = 'SD-00066';
        standardDetail.CLQ_PossibleResponses__c = 'Test;Yes;No';
        standardDetail.Possible_Points__c = '3;4;5';
        standardDetail.Possible_Ratings__c = '1;2';
        standardDetail.CLQ_Met_Not_Met__c='Met';
        standardDetail.CLQ_QuestionType__c = 'Picklist';
        standardDetails.add(standardDetail); 
        
        standardDetail1.RecordTypeId=questionRecordTypeId; 
        standardDetail1.Name = 'SD-00067';
        standardDetail1.CLQ_PossibleResponses__c = 'Test;Yes;No';
        standardDetail1.Possible_Points__c = '3;4;5';
        standardDetail1.Possible_Ratings__c = '1;2';
        standardDetail1.CLQ_Met_Not_Met__c='Met';
        standardDetail1.CLQ_QuestionType__c = 'Picklist';
        standardDetails.add(standardDetail1);
        
        standardDetail2.RecordTypeId=questionRecordTypeId; 
        standardDetail2.Name = 'SD-00076';
        standardDetail2.CLQ_PossibleResponses__c = 'Test;Yes;No';
        standardDetail2.Possible_Points__c = '3;4;5';
        standardDetail2.Possible_Ratings__c = '1;2';
        standardDetail2.CLQ_Met_Not_Met__c='Met';
        standardDetail2.CLQ_QuestionType__c = 'Picklist';
        standardDetails.add(standardDetail2);
        
        standardDetail3.RecordTypeId=questionRecordTypeId; 
        standardDetail3.Name = 'SD-00170';
        standardDetail3.CLQ_PossibleResponses__c = 'Test;Yes;No';
        standardDetail3.Possible_Points__c = '3;4;5';
        standardDetail3.Possible_Ratings__c = '1;2';
        standardDetail3.CLQ_Met_Not_Met__c='Met';
        standardDetail3.CLQ_QuestionType__c = 'Picklist';
        standardDetails.add(standardDetail3);
        
        insert standardDetails;
        
        List<QuestionToInclude__c> questionstoInclude = new List<QuestionToInclude__c>();
        QuestionToInclude__c questoInclude = new QuestionToInclude__c();
        questoInclude.Name = 'SD-00066';
        questionstoInclude.add(questoInclude);
        
        QuestionToInclude__c questoInclude1 = new QuestionToInclude__c();
        questoInclude1.Name = 'SD-00067';
        questionstoInclude.add(questoInclude1);
        
        QuestionToInclude__c questoInclude2 = new QuestionToInclude__c();
        questoInclude2.Name = 'SD-00076.2';
        questionstoInclude.add(questoInclude2);
        
        QuestionToInclude__c questoInclude3 = new QuestionToInclude__c();
        questoInclude3.Name = 'SD-00170.2';
        questionstoInclude.add(questoInclude3);
        
        insert questionstoInclude;
        
    }
}