force-app/main/default/objects/CLQ_Create_Onsite__mdt/CLQ_Create_Onsite__mdt.object-meta.xml
<CustomObject>
    <label>CLQ Create Onsite</label>
    <pluralLabel>CLQ Create Onsites</pluralLabel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_County_at_Site__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County_at_Site__c</fullName>
    <label>CLQ County at Site</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Owner__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InspectionOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-license</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Incident / Injury / Illness</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Amendment - change of location</fullName>
            </value>
            <value>
                <fullName>Amendment - change of capacity</fullName>
            </value>
            <value>
                <fullName>Initial Registration</fullName>
            </value>
            <value>
                <fullName>Ongoing Registration</fullName>
            </value>
            <value>
                <fullName>Technical Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Site_IRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Site_IRN__c</fullName>
    <label>Site IRN</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_BIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_BIRN__c</fullName>
    <externalId>true</externalId>
    <label>Site IRN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Site_IRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Site_IRN__c</fullName>
    <description>What is the site IRN for the exact address where the program will be located?</description>
    <inlineHelpText>What is the site IRN for the exact address where the program will be located?</inlineHelpText>
    <label>Site IRN</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/Program_Transaction_County__c.field-meta.xml
<CustomField>
    <fullName>Program_Transaction_County__c</fullName>
    <description>This field is created to get the name of county. This field is being used to fix bug 11762</description>
    <formula>IF(CLQ_New_County__c != null, CLQ_New_County__r.Name, IF(CLQ_ProgTrans_County__c!= null, CLQ_ProgTrans_County__r.Name,CLQ_Program__r.CLQ_County__r.Name))</formula>
    <label>Program Transaction County</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CLQ_CreateOnsiteVisitInspectionExtn.cls
/**************************************************************************************************************
** Name             : CLQ_CreateOnsiteVisitInspectionExtn
** Description      : This class/extension contains all detail logic/methods for CLQ_CreateOnsiteVisitInspection pages.
                    It will create a new OnSite inspection record from program transaction.
** Assumptions      : 
** Version          : 1.4
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**	Developer					Date				Version		Description
**------------------------------------------------------------------------------------------------------------
**	DevTeam						Nov-2016			1.0			Created
**	Ramana Gurivelli			07/05/2017			1.1			CR# 11199: Updated to set inspection owner as loggedin user.
**	Neetu Ojha					12/12/2017			1.2			TFS#11867 : Inspection status update
**	Pradeep Ravi				03/26/2018			1.3			TFS#11949 : Updating Inspection IRN from Prog
**	Neetu Ojha					04/25/2018			1.4			TFS#12102 : Inspection Type Update
** Rohit Gowrishetty			02/08/2019			1.5			TFS#15575 : Added logic to update county onto the Insp
**************************************************************************************************************/
public with sharing class CLQ_CreateOnsiteVisitInspectionExtn{
    //variables
    
    public CLQ_Program_Transaction__c programTransactionRecord;
     public static Map<String, String> CLQCreateOnsiteValueMap = new  Map<String, String>();
    

    public CLQ_CreateOnsiteVisitInspectionExtn(ApexPages.StandardController controller) {
        list<String> fieldlist;
        fieldlist = new list<String>{'CLQ_Program__r.CLQ_BIRN__c','CLQ_Program__r.Id','OwnerId', 'Program_Transaction_County__c'}; // 15575//add fields to this list to query from database
        if(!Test.isRunningTest()){
            controller.addFields(fieldlist);
        }
        this.programTransactionRecord = (CLQ_Program_Transaction__c)controller.getRecord();
    }


    //Method to complete all on-load logic
    //@param : none
    //@return : pagereference
    public pagereference onLoad(){
        Id onsiteVisitRecordTypeId;
        
         for(CLQ_Create_Onsite__mdt mdt : [Select label,QualifiedApiName from CLQ_Create_Onsite__mdt]){
                CLQCreateOnsiteValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
        if(Schema.sObjectType.CLQ_Inspection__c.isAccessible()){
        	 onsiteVisitRecordTypeId = Schema.CLQ_Inspection__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('Onsite Visit Record Type').getRecordTypeId();
        }
            //12102 starts
            Id ptInitialRegRecTypeId;
        	Id ptOngoingRegRecTypeId;
         if(Schema.sObjectType.CLQ_Program_Transaction__c.isAccessible()){
        	 ptInitialRegRecTypeId = Schema.CLQ_Program_Transaction__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('SUTQ - Initial Registration').getRecordTypeId();
        	 ptOngoingRegRecTypeId = Schema.CLQ_Program_Transaction__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('SUTQ - Ongoing Registration').getRecordTypeId();
         }
           
        CLQ_Inspection__c inspectionrecord = new CLQ_Inspection__c();
        inspectionrecord.RecordTypeId = onsiteVisitRecordTypeId;
        inspectionrecord.CLQ_Program_Transaction__c = programTransactionRecord.Id;
        inspectionrecord.CLQ_Program__c = programTransactionRecord.CLQ_Program__r.Id;
        inspectionrecord.CLQ_Site_IRN__c= programTransactionRecord.CLQ_Program__r.CLQ_BIRN__c;
        inspectionrecord.CLQ_County_at_Site__c = programTransactionRecord.Program_Transaction_County__c ; //15575
        /*if(String.valueOf(programTransactionRecord.OwnerId).contains('005')){ 
            inspectionrecord.CLQ_Inspection_Owner__c = programTransactionRecord.OwnerId; 
        } */ 
        
        inspectionrecord.CLQ_Inspection_Owner__c = UserInfo.getUserId();
        if(CLQCreateOnsiteValueMap.size()!=0){
        inspectionrecord.Inspection_Status__c = CLQCreateOnsiteValueMap.get('In_Progress');
        inspectionrecord.CLQ_Inspection_Status__c = CLQCreateOnsiteValueMap.get('In_Progress');//11867
        }
        
        //12102 Starts
        if(programTransactionRecord.recordtypeId == ptInitialRegRecTypeId && CLQCreateOnsiteValueMap.size()!=0){
        	inspectionrecord.CLQ_Inspection_Type__c= CLQCreateOnsiteValueMap.get('Initial_Registration');
        }
        
        if(programTransactionRecord.recordtypeId == ptOngoingRegRecTypeId && CLQCreateOnsiteValueMap.size()!=0){
        	inspectionrecord.CLQ_Inspection_Type__c= CLQCreateOnsiteValueMap.get('Ongoing_Registration');
        }
        //12102 Ends
          
        try{
            List<CLQ_Inspection__c> inspectionlist = new List<CLQ_Inspection__c>();
            inspectionlist.add(inspectionrecord);
            if(!inspectionlist.isEmpty() && Schema.sObjectType.CLQ_Inspection__c.isCreateable()){
                insert inspectionlist;
            }
        }catch(Exception e){
           Integration_Transaction_Logs.LogError
                ('SFDC-001.2', e.getMessage() ,'' ,String.valueOf(e.getLineNumber()),'','CLQ_CreateOnsiteVisitInspectionExtn');
        }
        return CLQ_UtilityClass.redirecttoPage('/'+inspectionrecord.Id);
    }  
}