force-app/main/default/objects/CLQ_Facility_Schedule__c/CLQ_Facility_Schedule__c.object-meta.xml
<CustomObject>
    <label>Facility Schedule</label>
    <nameField>
        <label>Facility Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Facility Schedules</relationshipLabel>
    <relationshipName>Facility_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Facility Schedules</relationshipLabel>
    <relationshipName>Facility_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program_Transaction_Source__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Transaction that created this record</inlineHelpText>
    <label>Program Transaction Source</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/CLQ_Room_Space_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Room/Space Information and Program Transaction.</description>
    <label>Room/Space Transaction</label>
    <nameField>
        <label>Room/Space Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room/Space Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Room/Space Transactions</relationshipLabel>
    <relationshipName>Room_Space_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Room/Space Transactions</relationshipLabel>
    <relationshipName>Room_Space_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DynamicTableFormCtrl.cls
/**
 * @author Srikrishna Regula (sregula@deloitte.com)
 * 
 * @verison 1.0
 * 
 * Provides functionality to render dynamic table and Forms
 * 
 * @Change History
 * 
 * 05/04/2020 - Initial version of DynamicTableFormCtrl @version 1.0
 * 
 */
public without sharing class DynamicTableFormCtrl implements IRequest {
    private String jsonParam;
	public static final string GET_TABLE_DATA = 'getTableData';
    private Map<String, String> programTransactionMap = new Map<String, String>();
    


    /**
     * Processes the method and returns JsonResponse
     * 
     * @param methodName - Name of the method to be processed defined in the class
     * @param jsonParam - JSON parameter to be used.
     * 
     * @return JsonResponse - Returns JsonResponse object
     */
    public JsonResponse processRequest(String methodName, String jsonParam){
        JsonResponse response = null;
        this.jsonParam = jsonParam;

        programTransactionMap.put('CLQ_Facility_Schedule__c', 'CLQ_Program_Transaction__c');
        programTransactionMap.put('CLQ_Role__c', 'CLQ_Program_Transaction_Source__c');
        programTransactionMap.put('CLQ_Room_Space_Transaction__c', 'CLQ_Program_Transaction__c');
        
        if(methodName == GET_TABLE_DATA){
            try{
                response = getTableData();
            }
            catch(Exception ex){
                response = new JsonResponse();
                response.status = RequestStatus.ERROR;
                response.data = new Map<String, Object>();
                response.errors = new List<String>();
                response.errors.add(ex.getMessage());
            }
        }
        else{
            response = new JsonResponse();
            response.status = RequestStatus.ERROR;
            response.data = new Map<String, Object>();
            response.errors = new List<String>();
            response.errors.add('Invalid method name');
        }

        return response;
    }

    public JsonResponse validate(String methodName, String jsonParam) {
        JsonResponse response = new JsonResponse();
        response.status = RequestStatus.OK;
        response.data = new Map<String, Object>();
        response.errors = new List<String>();
        return response;
    }

    private JsonResponse getTableData() {
        JsonResponse response = null;
        List<String> tableHeaders = new List<String>();
        TableRequest request = (TableRequest)JSON.deserialize(this.jsonParam, TableRequest.class);
        List<RecordType> programRecordTypes;
        string reqRecordName=request.recordTypeName;
        string reqObjectName=request.objectName;
        if(reqRecordName != null && reqObjectName != null){
            programRecordTypes = [SELECT Id, Name from RecordType where name =:reqRecordName AND SObjectType=:reqObjectName];
        }
        String query = 'SELECT ';
        for(Integer i = 0; i < request.tableInfo.size(); i++){
            tableHeaders.add(request.tableInfo[i].Label);
            if(i == request.tableInfo.size() - 1){
                query += request.tableInfo[i].FieldName;
            }
            else{
                query += request.tableInfo[i].FieldName + ', ';
            }
        }
        if(programTransactionMap.size()!=0){
        query += ' FROM ' + request.objectName + ' WHERE CLQ_Program__c = ' + escapeValue(request.programID) + ' AND CLQ_Program__c <> null ' + ' AND ' + programTransactionMap.get(request.objectName) + ' = ' + escapeValue(request.programTransactionID);
        }
        if(programRecordTypes != null && programRecordTypes.size() > 0){
            query += ' AND RecordTypeId = ' + escapeValue(programRecordTypes[0].Id);
        }

        query += ' ' + request.whereClause;

        List<sObject> sobjList = Database.query(query);



        response = new JsonResponse();
        response.status = RequestStatus.OK;
        response.data = new Map<String, Object>();
        response.data.put('Query', query);
        response.data.put('TableHeaders', tableHeaders);
        if(programRecordTypes != null && programRecordTypes.size() > 0){
            response.data.put('RecordTypeId', programRecordTypes[0].Id);
        }else{
            response.data.put('RecordTypeId', '');
        }
        response.data.put('TableData', sobjList);
        response.errors = new List<String>();

        return response;
    }

    /**
     * Encloses the value in single quotes
     * 
     * @param value - value to be enclosed
     */
    private String escapeValue(String value){
        return '\'' + String.escapeSingleQuotes(value) + '\'';
    }

    public class TableRequest {
        public String programID {get; set;}
        public String programTransactionID {get; set;}
        public String recordTypeName {get; set;}
        public String objectName {get; set;}
        public String whereClause {get; set;}
        public List<PageSubSection.FormComponent> tableInfo {get; set;} 
    }
}