force-app/main/default/objects/CLQ_Facility_Schedule__c/CLQ_Facility_Schedule__c.object-meta.xml
<CustomObject>
    <label>Facility Schedule</label>
    <nameField>
        <label>Facility Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Facility Schedules</relationshipLabel>
    <relationshipName>Facility_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Payment_Received__c/CLQ_Payment_Received__c.object-meta.xml
<CustomObject>
    <label>Payment Received</label>
    <nameField>
        <displayFormat>Pay-{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Received</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Payment_Received__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Payments Received</relationshipLabel>
    <relationshipName>Payments_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Number__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Number__c</fullName>
    <formula>IF(ISBLANK(CLQ_Legacy_Program_Number__c),
IF(or(contains(RecordType.Name,&apos;FCC&apos;),RecordType.Name = &apos;Child Care Center&apos;,RecordType.Name = &apos;Out of State Registration&apos;,RecordType.Name = &apos;In-Home Aide&apos;,RecordType.Name = &apos;Day Camp&apos; ),
&apos;2&apos;&amp;CLQ_Program_ID__c ,
IF(or(RecordType.Name=&apos;Pre School&apos;,RecordType.Name=&apos;School Age Child Care&apos;),
&apos;1&apos;&amp;CLQ_Program_ID__c,null)),CLQ_Legacy_Program_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_License_Revoked_Previously__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Revoked_Previously__c</fullName>
    <description>Was your license ever revoked?</description>
    <inlineHelpText>Was your license ever revoked?</inlineHelpText>
    <label>Was your license ever revoked?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program_Number__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Number__c</fullName>
    <formula>CLQ_Program__r.CLQ_Program_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Application Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Are_you_currently_Licensed__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Are_you_currently_Licensed__c</fullName>
    <inlineHelpText>Are you currently Licensed as the Child Care Provider/Program by the ODJFS?</inlineHelpText>
    <label>Are you currently Licensed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Certified_Licensed_by_other_state__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Certified_Licensed_by_other_state__c</fullName>
    <label>Certified/Licensed by another state?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_License_Revoked_Previously__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Revoked_Previously__c</fullName>
    <description>Was your license ever revoked</description>
    <inlineHelpText>Was your license ever revoked</inlineHelpText>
    <label>License Revoked Previously</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program_Number__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Number__c</fullName>
    <description>If you own more than 1 program, list the most recently licensed</description>
    <inlineHelpText>If you own more than 1 program, list the most recently licensed</inlineHelpText>
    <label>Program Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/recordTypes/CLQ_Organization_Role.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Organization_Role</fullName>
    <active>true</active>
    <description>Role associated to an organization</description>
    <label>Organization Role</label>
</RecordType>

force-app/main/default/objects/CLQ_Role__c/recordTypes/CLQ_Resident.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Resident</fullName>
    <active>true</active>
    <label>Resident</label>
</RecordType>

force-app/main/default/objects/CLQ_Room_Space__c/CLQ_Room_Space__c.object-meta.xml
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/CLQ_Room_Space_Inspection__c.object-meta.xml
<CustomObject>
    <description>Junction object between Room/Space and Inspection</description>
    <label>Room/Space Inspection</label>
    <nameField>
        <label>Room/Space Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Space Inspection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/CLQ_Transaction_Document__c.object-meta.xml
<CustomObject>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CLQ_RoleTriggerHandler_Test.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_RoleTriggerHandler_Test
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isparallel = true)
private class CLQ_RoleTriggerHandler_Test {
    @IsTest
    static void interceptUpdateAndCloneTest() {
        test.startTest(); 		
        map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
        integer OriginalCount = ProgramTransactionMap.size();
        CLQ_Program_Transaction__c ProgramTransaction;
        CLQ_Program_Transaction__c VersionBackup;
        for(CLQ_Program_Transaction__c trans : ProgramTransactionMap.values())
        {
            system.debug('Program Transactions: ' + trans.RecordType + '  Status ' + trans.CLQ_Transaction_Status__c);
            if(trans.CLQ_Transaction_Status__c == 'Application Revised'){
                VersionBackup = trans;
            } 
            ELSE{
                ProgramTransaction = trans;
            } 
        }
        system.assertEquals(null,VersionBackup,'Testing');
        
        
        list<CLQ_Role__c> Roles = [SELECT Id, Name, CLQ_Are_you_currently_Licensed__c,CLQ_Program_Number__c,
                                   CLQ_License_Revoked_Previously__c,CLQ_Certified_Licensed_by_other_state__c,CLQ_States__c,
                                   CLQ_Certified_as_Provider_within_past_5__c,CLQ_X2_Program_Number__c,CLQ_Licensed_as_Provider_within_past5yrs__c
                                   //,CLQ_X3_License_No__c
                                   FROM CLQ_Role__c Limit 20];    
        system.assertNotEquals(0,Roles.size(),'Testing');
        
        User customer = CLQ_UnitTestUtilities.GetCustomer();
        System.RunAs(customer)
        {
            Roles[0].CLQ_Certified_Licensed_by_other_state__c = 'Yes';
            CLQ_RoleTriggerHandler.HasUpdated = false;
            update Roles[0]; 
        }
        ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
        integer NewCount = ProgramTransactionMap.size();
        //system.assertEquals(OriginalCount + 2, NewCount);
        
        for(CLQ_Program_Transaction__c trans : ProgramTransactionMap.values())
        {
            system.debug('Program Transactions: ' + trans.RecordType + '  Status ' + trans.CLQ_Transaction_Status__c);
            if(trans.CLQ_Transaction_Status__c == 'Application Revised'){
                VersionBackup = trans;
            } 
            ELSE{
                ProgramTransaction = trans;
            } 
        }
        //system.assertNotEquals(null,VersionBackup);
        test.stopTest();        
    }
    @IsTest
    static void setEmptyRoleTest() {
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_Role__c role = new CLQ_Role__c();
            role.RecordTypeId = Schema.SObjectType.CLQ_Role__c.getRecordTypeInfosByDeveloperName().get('CLQ_Resident').getRecordTypeId();
            role.Relationship__c = 'Related';
            insert role;
            
            CLQ_Role__c modifiedrole = [SELECT Id, CLQ_Role__c FROM CLQ_Role__c WHERE Id = :role.id LIMIT 1];
            system.assertEquals('Resident', modifiedrole.CLQ_Role__c,'Testing');
        }
    }
    
    
    @testSetup 
    public static void testSetup()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
        User user = CLQ_UnitTestUtilities.AddCustomerUser();
        
        CLQ_Program_Transaction__c ProgramTransaction = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'Application - FCC');
        CLQ_Trigger.BypassAllTriggers = true;
        ProgramTransaction.OwnerId = user.Id;
        system.Debug('Unit Test setting the Status to SUBMITTED');
        ProgramTransaction.CLQ_Transaction_Status__c = 'Submitted';
        update ProgramTransaction;
        
        Task tsk = (Task)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Task');
        insert tsk;
        Event event = (Event)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Event');
        event.DurationInMinutes = 20;
        event.ActivityDateTime = DateTime.Now();
        insert Event;
        CLQ_Transaction_Document__c TransDoc = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
        insert TransDoc;
        CLQ_Facility_Schedule__c Facility = (CLQ_Facility_Schedule__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Facility_Schedule__c');
        insert Facility;
        //CLQ_Payment_Received__c Payment = (CLQ_Payment_Received__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Payment_Received__c');
        //insert Payment;
        Account a = new Account (Name = 'Test A Original');
        insert a;
        Contact c = new Contact (LastName = 'Test C Original', AccountId = a.Id);
        insert c;
        CLQ_Role__c role = (CLQ_Role__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Role__c');
        role.CLQ_Role__c = 'Authorized Representative';
        role.RecordTypeId = Schema.SObjectType.CLQ_Role__c.getRecordTypeInfosByDeveloperName().get('CLQ_Organization_Role').getRecordTypeId();
        role.OwnerId = user.id;
        role.CLQ_Contact__c=c.id;
        insert role;
        CLQ_Room_Space__c roomSpace = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
        roomSpace.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
        roomSpace.CLQ_Number_of_Children_Under_2__c = 2;
        roomSpace.CLQ_Used_By_Under_or_Over_2__c = 'Both';
        insert roomSpace;       
        CLQ_Inspection__c Inspection = (CLQ_Inspection__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Inspection__c');
        insert Inspection;
        CLQ_Room_Space_Inspection__c rsi = (CLQ_Room_Space_Inspection__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space_Inspection__c');
        rsi.CLQ_Inspection__c = Inspection.Id;
        rsi.CLQ_Room_Group_Information__c = roomSpace.Id;
        insert rsi;
        
        /*
Test.startTest();
CLQ_Trigger.BypassAllTriggers = false;
CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
System.RunAs(user)
{
//Causes a version to be created
ProgramTransaction.CLQ_Mailing_Street_Address__c = '1234 NorthWest St';
update ProgramTransaction;
}
Test.stopTest();
*/
    } 
    
    
}