force-app/main/default/objects/CLQ_Facility_Schedule__c/CLQ_Facility_Schedule__c.object-meta.xml
<CustomObject>
    <label>Facility Schedule</label>
    <nameField>
        <label>Facility Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Facility Schedules</relationshipLabel>
    <relationshipName>Facility_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Facility Schedules</relationshipLabel>
    <relationshipName>Facility_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Payment_Received__c/CLQ_Payment_Received__c.object-meta.xml
<CustomObject>
    <label>Payment Received</label>
    <nameField>
        <displayFormat>Pay-{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Received</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Payment_Received__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Payments Received</relationshipLabel>
    <relationshipName>Payments_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Payment_Received__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Payments Received</relationshipLabel>
    <relationshipName>Payments_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Application Revised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/CLQ_Room_Space__c.object-meta.xml
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/CLQ_Room_Space_Inspection__c.object-meta.xml
<CustomObject>
    <description>Junction object between Room/Space and Inspection</description>
    <label>Room/Space Inspection</label>
    <nameField>
        <label>Room/Space Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Space Inspection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Rules_Inspected__c/CLQ_Rules_Inspected__c.object-meta.xml
<CustomObject>
    <label>Rules Inspected</label>
    <nameField>
        <displayFormat>RI#-{000000}</displayFormat>
        <label>Rules Inspected No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Inspected</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Rules_Inspected__c/fields/CLQ_Room_Space__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Room_Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room/Space</label>
    <referenceTo>CLQ_Room_Space__c</referenceTo>
    <relationshipLabel>Rules Inspected</relationshipLabel>
    <relationshipName>Rules_Inspected</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Staff_Record__c/CLQ_Staff_Record__c.object-meta.xml
<CustomObject>
    <description>Provides an overview of all staff members employed by the Program.</description>
    <label>Staff Record</label>
    <nameField>
        <displayFormat>Staff #{000000}</displayFormat>
        <label>Staff Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Staff_Record__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Staff Records</relationshipLabel>
    <relationshipName>Staff_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/CLQ_Transaction_Document__c.object-meta.xml
<CustomObject>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CLQ_CloneUtility_2Test.cls
/* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*/
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_CloneUtility_2Test
** Description      : This class contains unit tests for validating the behavior of Apex classes and triggers.
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A                     N/A             1.0         Initial Build 
**  Pavan Ayta              8/23/17         1.1         Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isparallel = true)
private class CLQ_CloneUtility_2Test {
    public static final string APPLICATION_REVISED = 'Application Revised';
    @IsTest
    static void cancelUpdateTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            //get a CLQ_Program_Transaction__c record
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            system.debug('Number of Program Transactions: ' + ProgramTransactionMap.size());
            
            
            CLQ_Program_Transaction__c ProgramTransaction;
            CLQ_Program_Transaction__c VersionBackup;
            for(CLQ_Program_Transaction__c trans : ProgramTransactionMap.values())
            {
                system.debug('Program Transactions: ' + trans.RecordType + '  Status ' + trans.CLQ_Transaction_Status__c);
                if (trans.CLQ_Transaction_Status__c == APPLICATION_REVISED) {VersionBackup = trans;}
                ELSE{ ProgramTransaction = trans;}
            }
            
            Test.startTest();
            
            CLQ_Trigger.BypassAllTriggers = true;
            
            Task tsk = (Task)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Task');
            insert tsk;
            Event event = (Event)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Event');
            event.DurationInMinutes = 20;
            event.ActivityDateTime = DateTime.Now();
            insert Event;
            CLQ_Transaction_Document__c TransDoc = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
            insert TransDoc;
            CLQ_Facility_Schedule__c Facility = (CLQ_Facility_Schedule__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Facility_Schedule__c');
            insert Facility;
            //CLQ_Payment_Received__c Payment = (CLQ_Payment_Received__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Payment_Received__c');
            //insert Payment;
            CLQ_Role__c role = (CLQ_Role__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Role__c');
            insert role;
            CLQ_Room_Space__c roomSpace = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
            roomSpace.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
            roomSpace.CLQ_Number_of_Children_Under_2__c = 2;
            roomSpace.CLQ_Used_By_Under_or_Over_2__c = 'Both';
            insert roomSpace;       
            CLQ_Inspection__c Inspection = (CLQ_Inspection__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Inspection__c');
            insert Inspection;
            CLQ_Room_Space_Inspection__c rsi = (CLQ_Room_Space_Inspection__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space_Inspection__c');
            rsi.CLQ_Inspection__c = Inspection.Id;
            rsi.CLQ_Room_Group_Information__c = roomSpace.Id;
            insert rsi;
            
            CLQ_Program_Transaction__c ChangedTransaction = CLQ_CloneUtility.CancelRevision(ProgramTransaction);
            
            Test.stopTest();
        }
    }       
    
    @IsTest
    static void cloneTrasnactionTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            //get a CLQ_Program_Transaction__c record
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            CLQ_Program_Transaction__c ProgramTransaction;
            CLQ_Program_Transaction__c VersionBackup;
            for(CLQ_Program_Transaction__c trans : ProgramTransactionMap.values())
            {
                system.debug('Program Transactions: ' + trans.RecordType + '  Status ' + trans.CLQ_Transaction_Status__c);
                if (trans.CLQ_Transaction_Status__c == APPLICATION_REVISED) {VersionBackup = trans;}
                ELSE{ ProgramTransaction = trans;}
            }
            
            
            CLQ_Trigger.BypassAllTriggers = true;
            Task tsk = (Task)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Task');
            insert tsk;
            CLQ_Transaction_Document__c TransDoc1 = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
            CLQ_Transaction_Document__c TransDoc2 = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
            insert new list<sObject>{TransDoc1, TransDoc2};
                CLQ_Staff_Record__c staffRecord1 = (CLQ_Staff_Record__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Staff_Record__c');
            CLQ_Staff_Record__c staffRecord2 = (CLQ_Staff_Record__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Staff_Record__c');
            insert new list<sObject>{staffRecord1, staffRecord2};
                CLQ_Room_Space__c RS1 = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
            CLQ_Room_Space__c RS2 = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
            RS1.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
            RS1.CLQ_Number_of_Children_Under_2__c = 2;
            RS1.CLQ_Used_By_Under_or_Over_2__c = 'Both';
            RS2.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
            RS2.CLQ_Number_of_Children_Under_2__c = 2;
            RS2.CLQ_Used_By_Under_or_Over_2__c = 'Both';
            insert new list<sObject>{RS1, RS2};
                
                //ProgramTransaction;
                
                CLQ_Trigger.BypassAllTriggers = false;
            Test.StartTest();
            //Finished test data
            CLQ_Program_Transaction__c cloned = CLQ_CloneUtility.CloneProgramTransaction(ProgramTransaction, null, null);
            insert cloned;
            
            CLQ_Program_Transaction__c Deserialized = CLQ_CloneUtility.DeserializeRelatedLists(cloned);
            
            list<CLQ_Room_Space__c> spaces = Deserialized.Rooms_Spaces__r;
            
            system.debug('spaces: ' + spaces[0]);
            system.debug('spaces: ' + spaces[1]);
            system.debug('spaces: ' + spaces[2]);
            
            map<string, list<sObject>> relatedListMap = CLQ_CloneUtility.QueryRelatedLists(Deserialized);
            Test.StopTest();
        }
        
    }
    
    @IsTest
    static void cloneCancelTwoTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            //get a CLQ_Program_Transaction__c record
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            CLQ_Program_Transaction__c ProgramTransaction;
            CLQ_Program_Transaction__c VersionBackup;
            for(CLQ_Program_Transaction__c trans : ProgramTransactionMap.values())
            {
                system.debug('Program Transactions: ' + trans.RecordType + '  Status ' + trans.CLQ_Transaction_Status__c);
                if (trans.CLQ_Transaction_Status__c == APPLICATION_REVISED) {VersionBackup = trans;}
                ELSE{ ProgramTransaction = trans;}
            }
            CLQ_Program_Transaction__c RelatedToPrevious = CLQ_CloneUtility.RelatedItems(ProgramTransaction.id);
            
            CLQ_Trigger.BypassAllTriggers = true;
            Task tsk = (Task)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Task');
            insert tsk;
            CLQ_Transaction_Document__c TransDoc1 = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
            CLQ_Transaction_Document__c TransDoc2 = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
            insert new list<sObject>{TransDoc1, TransDoc2};
                CLQ_Staff_Record__c staffRecord1 = (CLQ_Staff_Record__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Staff_Record__c');
            CLQ_Staff_Record__c staffRecord2 = (CLQ_Staff_Record__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Staff_Record__c');
            insert new list<sObject>{staffRecord1, staffRecord2};
                CLQ_Room_Space__c RS1 = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
            CLQ_Room_Space__c RS2 = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
            RS1.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
            RS1.CLQ_Number_of_Children_Under_2__c = 2;
            RS1.CLQ_Used_By_Under_or_Over_2__c = 'Both';
            RS2.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
            RS2.CLQ_Number_of_Children_Under_2__c = 2;
            RS2.CLQ_Used_By_Under_or_Over_2__c = 'Both';
            insert new list<sObject>{RS1, RS2};
                CLQ_Facility_Schedule__c Facility = (CLQ_Facility_Schedule__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Facility_Schedule__c');
            insert Facility;
            //CLQ_Payment_Received__c Payment = (CLQ_Payment_Received__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Payment_Received__c');
            //insert Payment;
            CLQ_Role__c role = (CLQ_Role__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Role__c');
            insert role;
            
            Test.StartTest();
            
            CLQ_Program_Transaction__c RelatedToMost = CLQ_CloneUtility.RelatedItems(ProgramTransaction.id);
            
            map<string, list<sObject>> AllItems = CLQ_CloneUtility.QueryRelatedLists(RelatedToPrevious);
            for(sObject sobj : AllItems.get('Facility Schedules'))
            {
                CLQ_Facility_Schedule__c sch = (CLQ_Facility_Schedule__c)sobj;
                // fix by MP - Test class failure - 1/14
                if(sch!= null && VersionBackup!=null && VersionBackup.Id != null){
                    sch.CLQ_Program_Transaction__c = VersionBackup.Id;
                }
            }
            update AllItems.get('Facility Schedules'); 
            
            for(sObject sobj : AllItems.get('Associated Individuals'))
            {
                CLQ_Role__c sch = (CLQ_Role__c)sobj;
                if(VersionBackup!=null && VersionBackup.Id != null){
                    sch.CLQ_Program_Transaction_Source__c = VersionBackup.Id;
                }
            }
            update AllItems.get('Associated Individuals'); 
            
            for(sObject sobj : AllItems.get('Rules Inspected'))
            {
                CLQ_Rules_Inspected__c sch = (CLQ_Rules_Inspected__c)sobj;
                if(VersionBackup!=null && VersionBackup.Id != null){
                    sch.ProgramTransaction__c = VersionBackup.Id;
                }
            }
            update AllItems.get('Rules Inspected'); 
            //for(sObject sobj : AllItems.get('Payments Received'))
            //{
                //CLQ_Payment_Received__c sch = (CLQ_Payment_Received__c)sobj;
                //if(VersionBackup!=null && VersionBackup.Id != null){
                //    sch.CLQ_Program_Transaction__c = VersionBackup.Id;
                //}
            //}
            //update AllItems.get('Payments Received'); 
            for(sObject sobj : AllItems.get('Transaction Documents'))
            {
                CLQ_Transaction_Document__c sch = (CLQ_Transaction_Document__c)sobj;
                //if(VersionBackup!=null && VersionBackup.Id != null){
                //sch.CLQ_Program_Transaction__c = VersionBackup.Id;
                //}
            }
            //update AllItems.get('Transaction Documents'); 
            
            
            //ProgramTransaction;
            
            CLQ_Program_Transaction__c RelatedAfterSomeMoved = CLQ_CloneUtility.RelatedItems(ProgramTransaction.id);
            
            CLQ_Trigger.BypassAllTriggers = false;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            ProgramTransaction.CLQ_Transaction_Status__c = 'Cancelled';
            update ProgramTransaction;
            CLQ_Program_Transaction__c RelatedToAfterCancel = CLQ_CloneUtility.RelatedItems(ProgramTransaction.id);
            
            Test.StopTest();
        }
        
    }    
    
    /*static void DisplayRelatedLists(CLQ_Program_Transaction__c Related)
    {
        map<string, list<sObject>> AllItems = CLQ_CloneUtility.QueryRelatedLists(Related);
        for(string KeyName : AllItems.keySet())
        {
            system.Debug(KeyName + '  -  ' + AllItems.get(KeyName).size());
            for(sObject sobj : AllItems.get(KeyName))
                system.Debug(KeyName + '  ---------  ' + string.valueOf(sobj.Id).subString(11).toUpperCase());
        }
    }*/
    
    @testSetup 
    public static void testSetup()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting(); //11615
        User user = CLQ_UnitTestUtilities.AddCustomerUser();
        
        CLQ_Program_Transaction__c ProgramTransaction = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'Application - FCC');
        CLQ_Trigger.BypassAllTriggers = true;
        ProgramTransaction.OwnerId = user.Id;
        system.Debug('Unit Test setting the Status to SUBMITTED');
        ProgramTransaction.CLQ_Transaction_Status__c = 'Submitted';
        update ProgramTransaction;
        
        Task tsk = (Task)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Task');
        insert tsk;
        Event event = (Event)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'Event');
        event.DurationInMinutes = 20;
        event.ActivityDateTime = DateTime.Now();
        insert Event;
        CLQ_Transaction_Document__c TransDoc = (CLQ_Transaction_Document__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Transaction_Document__c');
        insert TransDoc;
        CLQ_Facility_Schedule__c Facility = (CLQ_Facility_Schedule__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Facility_Schedule__c');
        insert Facility;
        //CLQ_Payment_Received__c Payment = (CLQ_Payment_Received__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Payment_Received__c');
        //insert Payment;
        CLQ_Role__c role = (CLQ_Role__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Role__c');
        insert role;
        CLQ_Room_Space__c roomSpace = (CLQ_Room_Space__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space__c');
        roomSpace.CLQ_Program__c = ProgramTransaction.CLQ_Program__c;
        roomSpace.CLQ_Number_of_Children_Under_2__c = 2;
        roomSpace.CLQ_Used_By_Under_or_Over_2__c = 'Both';
        insert roomSpace;       
        CLQ_Inspection__c Inspection = (CLQ_Inspection__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Inspection__c');
        
        insert Inspection;
        CLQ_Room_Space_Inspection__c rsi = (CLQ_Room_Space_Inspection__c)CLQ_UnitTestUtilities.AddRelatedItem(ProgramTransaction, 'CLQ_Room_Space_Inspection__c');
        rsi.CLQ_Inspection__c = Inspection.Id;
        rsi.CLQ_Room_Group_Information__c = roomSpace.Id;
        insert rsi;
        
        Test.startTest();
        CLQ_Trigger.BypassAllTriggers = false;
        CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
        System.RunAs(user)
        {
            //Causes a version to be created
            ProgramTransaction.CLQ_Mailing_Street_Address__c = '1234 NorthWest St';
            ProgramTransaction.CLQ_Portal_Application_Update__c = true;
            update ProgramTransaction;
        }
        Test.stopTest();
    }
}