force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Record_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Assigned_To__c</fullName>
    <formula>Owner:User.FirstName + &quot; &quot; +  Owner:User.LastName</formula>
    <label>Assigned To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Calculated_Max_Capacity_Under_2_5Yr__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Calculated_Max_Capacity_Under_2_5Yr__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Maximum Capacity(Under 2 1/2)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Calculated_Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Calculated_Maximum_Capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Maximum Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Record_Type__c</fullName>
    <formula>CLQ_Program__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/clq_recordtypename__c.field-meta.xml
<CustomField>
    <fullName>clq_recordtypename__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>clq_recordtypename</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Updated__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to determine if Transaction has been updated so that we can disable Cancel button accordingly</description>
    <label>Transaction Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/CLQ_Room_Space__c.object-meta.xml
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Approved_for_under_2_1_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_for_under_2_1_2__c</fullName>
    <label>Approved for under 2 1/2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Approved_Room_Space__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_Room_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Calc_Nb_of_Child_Allowed_Indoor__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Calc_Nb_of_Child_Allowed_Indoor__c</fullName>
    <formula>IF(
AND(ISPICKVAL(CLQ_Room_Space_Shape__c ,&quot;Square/Rectangle/L-Shaped&quot;),RecordType.Name  = &apos;Indoor Room/Space&apos;),FLOOR(CLQ_Square_Footage__c / 35),
IF(
AND(ISPICKVAL(CLQ_Room_Space_Shape__c ,&quot;Irregular&quot;),RecordType.Name  = &apos;Indoor Room/Space&apos;),FLOOR(CLQ_Square_Footage_Irregular__c / 35),0
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is used for Indoor RecordType.</inlineHelpText>
    <label>Calculated Number of Children Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/recordTypes/CLQ_Indoor_Room_Space.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Indoor_Room_Space</fullName>
    <active>true</active>
    <label>Indoor Room/Space</label>
</RecordType>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/CLQ_Room_Space_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Room/Space Information and Program Transaction.</description>
    <label>Room/Space Transaction</label>
    <nameField>
        <label>Room/Space Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room/Space Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Approved_for_under_2_1_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_for_under_2_1_2__c</fullName>
    <label>Approved for under 2 1/2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Approved_Room_Space__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_Room_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Calc_Nb_of_Child_Allowed_Indoor__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Calc_Nb_of_Child_Allowed_Indoor__c</fullName>
    <formula>IF( 
AND(ISPICKVAL(CLQ_Room_Space_Shape__c ,&quot;Square/Rectangle/L-Shaped&quot;),RecordType.Name = &apos;Indoor Room/Space&apos;),FLOOR(CLQ_Square_Footage__c / 35), 
IF( 
AND(ISPICKVAL(CLQ_Room_Space_Shape__c ,&quot;Irregular&quot;),RecordType.Name = &apos;Indoor Room/Space&apos;),FLOOR(CLQ_Square_Footage_Irregular__c / 35),0 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Number of Children Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Currently_In_Use__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Currently_In_Use__c</fullName>
    <label>In Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/clq_formatted_change_table__c.field-meta.xml
<CustomField>
    <fullName>clq_formatted_change_table__c</fullName>
    <label>clq_formatted_change_table</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Room/Space Transactions</relationshipLabel>
    <relationshipName>Room_Space_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Program_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Record_Type__c</fullName>
    <formula>CLQ_Program_Transaction__r.CLQ_Program__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Room/Space Transactions</relationshipLabel>
    <relationshipName>Room_Space_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Room_Space_Information__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Room_Space_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room/Space Information</label>
    <referenceTo>CLQ_Room_Space__c</referenceTo>
    <relationshipLabel>Room/Space Transactions</relationshipLabel>
    <relationshipName>Room_Space_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/fields/CLQ_Room_Space_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Room_Space_Type__c</fullName>
    <label>Room/Space Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Space</fullName>
            </value>
            <value>
                <fullName>Additional Space</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Transaction__c/recordTypes/CLQ_Indoor_Room_Space.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Indoor_Room_Space</fullName>
    <active>true</active>
    <label>Indoor Room/Space</label>
</RecordType>

force-app/main/default/classes/CLQ_RoomSpaceTransactionTriggerHandler.cls
/**************************************************************************************************************
** Name             : CLQ_RoomSpaceTransactionTriggerHandler
** Description      : Handles RoomSpaceTransaction methods
** Assumptions      : 
** Version          : 1.5
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**	Developer				Date			Version		Description
**------------------------------------------------------------------------------------------------------------
**  Prakriti Biswas         9/19/17         1.1         TFS#11648 : Using CLQ_Calc_Nb_of_Child_Allowed_Indoor__c for footApp Math Calculation for ODE and CC 
** 	Soufin Rahimeen			02/14/2018		1.2			TFS#11958 : Added upper limits to max value
**	Neetu Ojha				04/16/2018		1.3			TFS#12138 : Redefined Capacity calculation
**	Neetu Ojha				05/10/2018		1.4			TFS#12218 : Added null check
**	Soufin Rahimeen			07/26/2018		1.5			TFS#12150 : Added logic to update Transaction Updated flag on PT
**  Rohit Gowrishetty		02/22/2019		1.6			TFS#15095 : Added logic to check for reviewer before deleting the RmSpace Records 
**************************************************************************************************************/ 

public with sharing class CLQ_RoomSpaceTransactionTriggerHandler extends CLQ_Trigger 
{
    
    Public static final string Reviewer='Reviewer';
    Public static final string TD='<td>';
    Public static final string FCC_Type_A_Home='FCC - Type A Home';
    Public static final string FCC_Type_B_Home='FCC - Type B Home';
    Public static final string YES='Yes';
    Public static final string UPDATESTR='update';
    Public static final string INSERTSTR='insert';
    Public static final string DELETESTR='delete';
    
    //Allows only this trigger to be bypassed. Useful in Unit Test data setup and some bulk data loads.
    public static boolean BypassTrigger {
        get {
            if (BypassTrigger == null){
                BypassTrigger = false;
            } 
            return BypassTrigger;
        }
        set;
    }
    
    public static final String headerValue = '<table border="1" rules="all" style="padding-top:3rem;padding-bottom:3rem;"> <thead> <tr> <th>Field Name</th> <th>Original Value</th> <th>New Value</th> </tr> </thead> <tbody>'; 
    public static final String footerValue = '</tbody></table> <br><br>';
    public static final String empty_string = '';
    //Calls the Base class Constructor
    public CLQ_RoomSpaceTransactionTriggerHandler(list < sObject > newlistin, map < id, sObject > newMapin, list < sObject > oldlistin,map < id, sObject > oldMapin,
                                    boolean isExecutingin, boolean isInsertin, boolean isUpdatein, boolean isDeletein,
                                    boolean isBeforein, boolean isAfterin, boolean isUndeletein, integer sizein) {
                                        super(newlistin, newMapin, oldlistin, oldMapin,
                                              isExecutingin, isInsertin, isUpdatein, isDeletein,
                                              isBeforein, isAfterin, isUndeletein, sizein);
                                        BypassInheritedTrigger = BypassTrigger;
                                                if(!(BypassInheritedTrigger || BypassAllTriggers)){            
            BypassInheritedTrigger = BypassSelectiveTriggers;
        }
                                    }
   public override void AfterInsert() {
        updateCapacityOnProgTransacation((list < CLQ_Room_Space_Transaction__c > ) newList , false); //12138
        updateProgramTransaction((list < CLQ_Room_Space_Transaction__c > ) newList, (map < id, CLQ_Room_Space_Transaction__c > ) oldMap, 'insert'); //12150
    }
    
    public override void AfterUpdate() {
        updateCapacityOnProgTransacation((list < CLQ_Room_Space_Transaction__c > ) newList , false); //12138
        updateProgramTransaction((list < CLQ_Room_Space_Transaction__c > ) newList, (map < id, CLQ_Room_Space_Transaction__c > ) oldMap,  'update'); //12150
    }
    
    public override void BeforeUpdate() {
        buildFieldChangeHtmlTable((List <CLQ_Room_Space_Transaction__c> ) newList, (Map < Id, CLQ_Room_Space_Transaction__c > ) OldMap);
    }
    
    //12138 starts
    public override void AfterDelete() {
    	updateCapacityOnProgTransacation((list < CLQ_Room_Space_Transaction__c > ) oldList, true);
    	updateProgramTransaction((list < CLQ_Room_Space_Transaction__c > ) newList, (Map < Id, CLQ_Room_Space_Transaction__c > ) OldMap, 'delete'); //12150       
    }    
    //12138 Ends
    
    //15095 - Starts
    public override void BeforeDelete(){
        checkIfReviewerIsDeleting((list < CLQ_Room_Space_Transaction__c > ) oldList, true);
    }
    
    public void checkIfReviewerIsDeleting( list<CLQ_Room_Space_Transaction__c>  oldList, Boolean isDelete){
        
       // List<CLQ_Room_Space_Transaction__c> rmSpaceTrans = new List<CLQ_Room_Space_Transaction__c> ();
        Map<Id, Id> mapOfRmSpAndPT = new Map<Id,Id>();
        
        for (CLQ_Room_Space_Transaction__c rst : oldList){
        	if(rst.CLQ_Program_Transaction__c!=null){
                mapOfRmSpAndPT.put(rst.Id,rst.CLQ_Program_Transaction__c);
            }
		}
        
        if(!mapOfRmSpAndPT.isEmpty()){
        	Map<Id,CLQ_Program_Transaction__c> MapPT = new Map<Id,CLQ_Program_Transaction__c>([SELECT id ,CLQ_Assigned_To__c,CLQ_Transaction_Assigned_To__c from CLQ_Program_Transaction__c where id in :mapOfRmSpAndPT.values()]);
		  	String profileId = UserInfo.getProfileId();
            String profileName = UserInfo.getName();
            //System.debug('profileName ' + profileName);
            
            for(CLQ_Room_Space_Transaction__c rst : oldList){
            Clq_Program_Transaction__c  pt =    MapPT.get(mapOfRmSpAndPT.get(rst.Id));
                //System.debug('Trans assignd to '+ pt.CLQ_Assigned_To__c );
                if(!profileName.containsIgnoreCase(Reviewer)){
                   // System.debug('is it coming inside--1');
                    Continue;
                }
                else if(profileName.containsIgnoreCase(Reviewer) && profileName !=pt.CLQ_Assigned_To__c ){
                    System.debug('is it coming inside--2');
                    //rst.addError('Only Reviewer assigned to Program Transaction can be able to delete the Room space records.');
            	}
        	}
    	}
    }
    //15095 - Ends
    public void buildFieldChangeHtmlTable(list < CLQ_Room_Space_Transaction__c > newList, map < id, CLQ_Room_Space_Transaction__c > oldMap){
      
        for (CLQ_Room_Space_Transaction__c rst : newList){
            string htmlTableValue = empty_string;
            string oldChangeTableHtml = empty_string;
            map<string, string> modifiedHtmlMap = new map<string, string>();
            map<string, string> originalHtmlMap = new map<string, string>();
            //first pull in the original field value and parse into map
            system.debug('******LD -----'+rst.clq_formatted_change_table__c);
            if (rst.clq_formatted_change_table__c != null ){
                oldChangeTableHtml = rst.clq_formatted_change_table__c.substringbetween('<tbody>','</tbody>');
            }
            list<string> listVals = oldChangeTableHtml.split('<tr>');
            for (string fieldVal : listVals){
                system.debug('value of splitarray ' + fieldVal);
                system.debug('value of td tags ' + fieldVal.substringbetween('<td>','</td>'));
                if (fieldVal.substringbetween(TD,TD) != null){
                    originalHtmlMap.put(fieldVal.substringbetween('<td>','</td>').trim(),'<tr>' + fieldVal);
                }
            }

            //now get the diff fields into the html table
            if(oldMap.size()!=0){
            modifiedHtmlMap = CLQ_CloneUtility.FindModifiedFieldsRoomSpaceTrans(rst,oldMap.get(rst.id));
            }
            //now check the originalHtmlMap and replace anything that was changed from modified map
            for (string modFieldNm : modifiedHtmlMap.keyset()){
                system.debug('value of lookup field' + modFieldNm + 'fff');
                if(originalHtmlMap.size()!=0 && modifiedHtmlMap.size()!=0){
                string test = originalHtmlMap.get(modFieldNm);
                system.debug('value of existing field' + test);
                originalHtmlMap.put(modFieldNm,modifiedHtmlMap.get(modFieldNm));            
            }
            }
            system.debug('*****value of originalHtmlMap after mod ' + originalHtmlMap);
           
            if(!originalHtmlMap.isEmpty()){  //LD
                //rebuild the html table value
                htmlTableValue += headerValue;
                for(string htmlVal : originalHtmlMap.values()){
                    htmlTableValue += htmlVal; 
                }
                
                //wrap the end of the table
                htmlTableValue += footerValue;
                rst.clq_formatted_change_table__c = htmlTableValue;
            }
        }

    }
    
    //12138 Starts
    private static void updateCapacityOnProgTransacation(list < CLQ_Room_Space_Transaction__c > lstRoomSpaceTrans , boolean isDelete){
    	
    	Id indoorRSRecTypeId = Schema.SObjectType.CLQ_Room_Space_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Indoor_Room_Space').getRecordTypeId();
    	Map<Id,List<CLQ_Room_Space_Transaction__c>> mapPTRoomSpace = new Map<Id,List<CLQ_Room_Space_Transaction__c>>();
        Map<Id,Id> mapRoomSpacePTId = new Map<Id,Id>();
        List<CLQ_Room_Space_Transaction__c> lstRoomSpaceT;
        List<CLQ_Program_Transaction__c> lstProgTransToUpdate = new List<CLQ_Program_Transaction__c>();
        
        system.debug('lstRoomSpaceTrans---'+lstRoomSpaceTrans);
        
        for(CLQ_Room_Space_Transaction__c rstObj:lstRoomSpaceTrans){
        	if(rstObj.CLQ_Program_Transaction__c != null){ //12218
            	mapRoomSpacePTId.put(rstObj.Id, rstObj.CLQ_Program_Transaction__c);
        	}
        }
        
		if(isDelete) {
            if(indoorRSRecTypeId != null && mapRoomSpacePTId.values() != null){
                lstRoomSpaceT = [Select Id,Name, CLQ_Approved_for_under_2_1_2__c, CLQ_Calc_Nb_of_Child_Allowed_Indoor__c,
											CLQ_Program_Transaction__c, CLQ_Program_Transaction__r.CLQ_Program_Record_Type__c
	                                      From CLQ_Room_Space_Transaction__c 
	                                      Where RecordTypeId =: indoorRSRecTypeId
	                                      AND CLQ_Program_Transaction__c in: mapRoomSpacePTId.values() 
	                                      AND (CLQ_Approved_Room_Space__c = true  
	                                      OR CLQ_Approved_for_under_2_1_2__c = 'Yes')
	                                      AND CLQ_Room_Space_Type__c = 'Primary Space'
	                                      AND CLQ_Currently_In_Use__c = 'Yes'
	                                      AND Id not in : mapRoomSpacePTId.keySet()
	                                      AND CLQ_Program_Transaction__r.CLQ_Transaction_Status__c != 'Approved'];
            }
		}else{
            if(indoorRSRecTypeId != null && mapRoomSpacePTId.values() != null){
                lstRoomSpaceT = [Select Id,Name, CLQ_Approved_for_under_2_1_2__c, CLQ_Calc_Nb_of_Child_Allowed_Indoor__c,
                                          CLQ_Program_Transaction__c, CLQ_Program_Transaction__r.CLQ_Program_Record_Type__c
                                          From CLQ_Room_Space_Transaction__c 
                                          Where RecordTypeId =: indoorRSRecTypeId
                                          AND CLQ_Program_Transaction__c in: mapRoomSpacePTId.values()
                                          AND (CLQ_Approved_Room_Space__c = true  
                                          OR CLQ_Approved_for_under_2_1_2__c = 'Yes') 
                                          AND CLQ_Room_Space_Type__c = 'Primary Space'
                                          AND CLQ_Currently_In_Use__c = 'Yes'
                                          AND CLQ_Program_Transaction__r.CLQ_Transaction_Status__c != 'Approved'];
            }
        }
        
		for(CLQ_Room_Space_Transaction__c roomSpaceIns: lstRoomSpaceT){
			if(mapPTRoomSpace.containsKey(roomSpaceIns.CLQ_Program_Transaction__c)){
                 mapPTRoomSpace.get(roomSpaceIns.CLQ_Program_Transaction__c).add(roomSpaceIns);
             }else{
				mapPTRoomSpace.put(roomSpaceIns.CLQ_Program_Transaction__c, new List<CLQ_Room_Space_Transaction__c>{roomSpaceIns});
			}
		}
        
        if(!mapPTRoomSpace.isEmpty()){
			for(Id ptId:mapPTRoomSpace.keySet()){
                decimal maxCapUnder2AndHalf = 0;
                decimal calcMaxCapacity = 0;
				
				for(CLQ_Room_Space_Transaction__c roomObj:mapPTRoomSpace.get(ptId)){
					if(roomObj.CLQ_Calc_Nb_of_Child_Allowed_Indoor__c != null){
						calcMaxCapacity = roomObj.CLQ_Calc_Nb_of_Child_Allowed_Indoor__c + calcMaxCapacity;
						
						if(roomObj.CLQ_Program_Transaction__r.CLQ_Program_Record_Type__c == FCC_Type_A_Home && calcMaxCapacity > 12){
							calcMaxCapacity = 12;
						}
						if(roomObj.CLQ_Program_Transaction__r.CLQ_Program_Record_Type__c == FCC_Type_B_Home && calcMaxCapacity > 6){
							calcMaxCapacity = 6;
						}
						
						if(roomObj.CLQ_Approved_for_under_2_1_2__c == YES){
							maxCapUnder2AndHalf = maxCapUnder2AndHalf + roomObj.CLQ_Calc_Nb_of_Child_Allowed_Indoor__c;
							if(roomObj.CLQ_Program_Transaction__r.CLQ_Program_Record_Type__c == FCC_Type_B_Home && maxCapUnder2AndHalf > 3){
								maxCapUnder2AndHalf = 3;
							}						
						}			
					}
					system.debug('maxCapUnder2AndHalf is:' +maxCapUnder2AndHalf);
					system.debug('calcMaxCapacity is:' +calcMaxCapacity);
				}
				//Max Capacity Under 2.5 year cannot be greater than calculated Max Capacity
				if(maxCapUnder2AndHalf > calcMaxCapacity){
					maxCapUnder2AndHalf = calcMaxCapacity;
				}
                CLQ_Program_Transaction__c ptObj = new CLQ_Program_Transaction__c();
                ptObj.Id = ptId;
                ptObj.CLQ_Calculated_Maximum_Capacity__c = calcMaxCapacity;
                ptObj.CLQ_Calculated_Max_Capacity_Under_2_5Yr__c = maxCapUnder2AndHalf;
                lstProgTransToUpdate.add(ptObj);
            }
        }
        
        system.debug('lstProgTransToUpdate --- '+lstProgTransToUpdate);
        try{
        	if(!lstProgTransToUpdate.isEmpty()){
	            update lstProgTransToUpdate;
	        }
        }catch(Exception e){
			Integration_Transaction_Logs.LogError('SFDC-001.2', e.getMessage() ,'' ,String.valueOf(e.getLineNumber()),'','Salesforce Exception -- CLQ_RoomSpaceTransactionTriggerHandler');
        }
    }
    //12138 Ends
    
    //12150 starts
	//update PT transaction updated field
	public void updateProgramTransaction(List<CLQ_Room_Space_Transaction__c> newList, Map<Id, CLQ_Room_Space_Transaction__c> oldMap, String operationType) {
		Id userId = userinfo.getProfileId();
		system.debug('User Id ---- '+userId);
		
		if(Label.CommunityProfileIds.contains(userId)){
			//System.debug('community user found-->');
			
			Set<Id> programTransIdSet = new Set<Id>(); //collect all the PT Ids
			Set<CLQ_Program_Transaction__c> ptToUpdate = new Set<CLQ_Program_Transaction__c>(); //collect all pt to update
			
			if(operationType==UPDATESTR || operationType==INSERTSTR) { //check if owner was changed, old map only exists for update
                System.debug('');
				for(CLQ_Room_Space_Transaction__c rst : newList) { //we dont have old map for these types
					if (rst.CLQ_Program_Transaction__c != null) { //this wont exist on rst on program
                        	//System.debug('');
							if(oldMap.size()!=0 && rst.OwnerId == oldMap.get(rst.Id).OwnerId) { //for new there is no old map so check
								programTransIdSet.add(rst.CLQ_Program_Transaction__c); //collect all the PT
							}
					}
				}
			}
			
			if(operationType==DELETESTR) { //check if owner was changed, old map only exists for update
				for(CLQ_Room_Space_Transaction__c rst : oldMap.values()) { //we have old map for delete
					if (rst.CLQ_Program_Transaction__c != null) { //this wont exist on rst on program
						programTransIdSet.add(rst.CLQ_Program_Transaction__c); //collect all the PT
					}
				}
			}
			
			if(programTransIdSet.size() > 0) {
				//master query to get all required details
				List<CLQ_Program_Transaction__c> relatedProgramTrans = [SELECT Id, Name, CLQ_Program__c, CLQ_Transaction_Updated__c, clq_recordtypename__c, (SELECT Id FROM Room_Space_Transactions__r LIMIT 1999) 
																	FROM CLQ_Program_Transaction__c 
																	WHERE Id IN:programTransIdSet
																	AND clq_recordtypename__c='Update Outdoor Space Information'];
																	
				if (relatedProgramTrans != null) {
					//get the count of rst from program
					
					//System.debug('relatedProgramTrans-->' + relatedProgramTrans);
					
					Map<Id, Id> programTransToProgramMap = new Map<Id, Id>(); //map to hold pt->p relationships so we delete correct items
					
					try {
						for(CLQ_Program_Transaction__c pt : relatedProgramTrans) { //if updated, change the flag
							if(operationType==UPDATESTR){
								//System.debug('operationType is update-->');
								pt.CLQ_Transaction_Updated__c = true;
								ptToUpdate.add(pt);
							}
							
							programTransToProgramMap.put(pt.Id, pt.CLQ_Program__c);
						}
						
						 			
					
						if(operationType==INSERTSTR || operationType==DELETESTR) {
							//System.debug('rst operationType is-->' + operationType);
		
							List<CLQ_Program__c> programsList = new List<CLQ_Program__c>(); //list of all programs
					
							if(programTransToProgramMap.size() > 0) {
								programsList = [SELECT Id, (SELECT Id FROM Rooms_Spaces__r LIMIT 1999) FROM CLQ_Program__c WHERE Id IN: programTransToProgramMap.values()];
							}
							
							
							//go through the programs and pt and check if new rst has been added or if rst has been deleted in pt
							for(CLQ_Program__c prog : programsList) {
								for(CLQ_Program_Transaction__c pt : relatedProgramTrans) {
									if(programTransToProgramMap.size() !=0 && programTransToProgramMap.get(pt.Id) == prog.Id) {
										System.debug('rst pt.Room_Space_Transactions__r.size()-->' + pt.Room_Space_Transactions__r.size());
										//System.debug('rst prog.Rooms_Spaces__r.size()-->' + prog.Rooms_Spaces__r.size());
										if(pt.Room_Space_Transactions__r.size() != prog.Rooms_Spaces__r.size()) { //if not equal then changes were made
											system.debug('rst Adding pt to list to update--->');
											pt.CLQ_Transaction_Updated__c = true;
											ptToUpdate.add(pt);
										}
									}
								}
							}
		
						}
					
					} catch (Exception e) {
						//System.debug('Error-->' + e);
						Integration_Transaction_Logs.LogError('SFDC-001.2', e.getMessage() ,'' ,String.valueOf(e.getLineNumber()),'','Salesforce Exception -- CLQ_RoomSpaceTransactionTriggerHandler');  
					}
					
					//update all the collected pt	
					if(ptToUpdate != null) {
						List<CLQ_Program_Transaction__c> ptToUpdateList = new List<CLQ_Program_Transaction__c>(ptToUpdate);
                        if(!ptToUpdateList.isEmpty()){
        					update ptToUpdateList;
         				}
					}
				}
				
			}
		}
	}    
    
}