force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Total_of_Rooms__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Total_of_Rooms__c</fullName>
    <label>Total # of Rooms</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Total_of_Rooms_under_21_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Total_of_Rooms_under_21_2__c</fullName>
    <label>Total # of Rooms (under 2 1/2)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/CLQ_Room_Space__c.object-meta.xml
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Approved_for_under_2_1_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_for_under_2_1_2__c</fullName>
    <label>Approved for under 2 1/2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Approved_Room_Space__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_Room_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Used_by_Under_or_Over_2_1_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Used_by_Under_or_Over_2_1_2__c</fullName>
    <label>Used by Under or Over 2 1/2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under</fullName>
            </value>
            <value>
                <fullName>Over</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLQ_RoomOrGrptgrHandler.cls
/**************************************************************************************************************
** Name             : CLQ_RoomOrGrptgrHandler
** Description      : Handles Room Space Information operation.
** Assumptions      : 
** Version          : 1.3
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**	Developer				Date			Version		Description
**------------------------------------------------------------------------------------------------------------
**	IncapsulateDevTeam		Oct-2016		1.0			Created
**	Neetu Ojha				18-Oct-2017		1.2			TFS#11820 : Update Room Space Info on Prog 
**	Neetu Ojha				21-Nov-2017		1.3			TFS#11909 : Changed Class modifier to Without sharing
**************************************************************************************************************/ 

public with sharing class CLQ_RoomOrGrptgrHandler extends CLQ_Trigger {
    ////////////////////////////////     Boilerplate implementation  ////////////////////////////
    //Allows only this trigger to be bypassed. Useful in Unit Test data setup and some bulk data loads.
    public static boolean BypassTrigger {
        get {
            if (BypassTrigger == null){
                BypassTrigger = false;
            } 
            return BypassTrigger;
        }
        set;
    }
    
    public static boolean HasUpdated;
    public override boolean getUpdateFlag()             {   return HasUpdated; }
    public override void setUpdateFlag(boolean newVal)  {   HasUpdated = newVal; }
    
        //Calls the Base class Constructor
    public CLQ_RoomOrGrptgrHandler(list < sObject > newlistin, map < id, sObject > newMapin, list <sObject > oldlistin, 
    							map < id, sObject > oldMapin, boolean isExecutingin, boolean isInsertin, boolean isUpdatein, boolean isDeletein,
            					boolean isBeforein, boolean isAfterin, boolean isUndeletein, integer sizein) {
		super(newlistin, newMapin, oldlistin, oldMapin,isExecutingin, isInsertin, isUpdatein, isDeletein,isBeforein, isAfterin, isUndeletein, sizein);
			BypassInheritedTrigger = BypassTrigger;

		if(!(BypassInheritedTrigger || BypassAllTriggers)){            
			BypassInheritedTrigger = BypassSelectiveTriggers;
		}
	}

    public override void AfterInsert() {
    }
    
    public override void AfterUpdate() {
    }

    //11820 Starts
	@InvocableMethod(label='UpdateRoomSpaceDetailsOnProgram' description='Updates Room Space details on program')
  	public static void updateRoomSpaceOnProgram(List<ID> lstPrgIds) {
  		system.debug('Id --- '+lstPrgIds);
  		
  		Map<Id, CLQ_Program__c> mapPrgToUpdate = new Map<Id,CLQ_Program__c>();
  		
  		try{
  			//To udpate Total number of Rooms
            if(lstPrgIds!=null){
                for(CLQ_Program__c prgObj : [Select Id, CLQ_Total_of_Rooms__c, CLQ_Total_of_Rooms_under_21_2__c, (Select Id from Rooms_Spaces__r where CLQ_Currently_In_Use__c ='Yes' AND CLQ_Approved_Room_Space__c = true) 
	  									from CLQ_Program__c where Id IN : lstPrgIds]){
  				prgObj.CLQ_Total_of_Rooms__c = prgObj.Rooms_Spaces__r.size();
	  			mapPrgToUpdate.put(prgObj.Id, prgObj);							
			}
            }
	  		//To update Total number of Rooms (under 2 1/2)
            if(lstPrgIds!=null){
                for(CLQ_Program__c prgObj : [Select Id, CLQ_Total_of_Rooms__c, CLQ_Total_of_Rooms_under_21_2__c, (Select Id from Rooms_Spaces__r where CLQ_Currently_In_Use__c ='Yes' 
	  													AND CLQ_Approved_for_under_2_1_2__c = 'Yes' AND CLQ_Used_by_Under_or_Over_2_1_2__c != 'Over') 
	  									from CLQ_Program__c where Id IN : lstPrgIds]){
	  				
  				if(mapPrgToUpdate.containsKey(prgObj.Id)){
  					mapPrgToUpdate.get(prgObj.Id).CLQ_Total_of_Rooms_under_21_2__c = prgObj.Rooms_Spaces__r.size();	
  				}else{
  					prgObj.CLQ_Total_of_Rooms_under_21_2__c = prgObj.Rooms_Spaces__r.size();
  					
  					mapPrgToUpdate.put(prgObj.Id, prgObj);	
  				}
			}
            }
	  		
			
			if(!mapPrgToUpdate.isEmpty()){
				CLQ_ProgramTriggerHandler.BypassTrigger = true;
				update mapPrgToUpdate.values();
			}
  		}catch(Exception ex){
  			system.debug('Exception occured in : updateTotalRoomsOnProgram --'+ex.getMessage());
  			Integration_Transaction_Logs.LogError('SFDC-001.2', ex.getMessage() ,'' ,String.valueOf(ex.getLineNumber()),'','Salesforce Exception -- CLQ_RoomOrGrptgrHandler');
  		}
  	}
  	//11820 Ends    
}