force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Email__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Email__c</fullName>
    <label>Program Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <label>Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Program_Rating__c.field-meta.xml
<CustomField>
    <fullName>Program_Rating__c</fullName>
    <label>SUTQ Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Anniversary_Date__c</fullName>
    <description>Program rating anniversary date gets populated based on the program effective date and expiration date.</description>
    <label>Rating Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Discontinue__c.field-meta.xml
<CustomField>
    <fullName>Rating_Discontinue__c</fullName>
    <description>Rating discontinue date is used when the program rating turns to 0 either by manually or through AR process or through Ongoing registration it should get punched with the system date on that particular date</description>
    <label>Rating Discontinue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Effective_Date__c</fullName>
    <label>SUTQ Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Expiration_Date__c</fullName>
    <label>SUTQ Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>CLQ_Role__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Original_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Original_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <formula>TEXT(CLQ_Program__r.CLQ_Program_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/Submission_Date1__c.field-meta.xml
<CustomField>
    <fullName>Submission_Date1__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/Ongoing_Quality_Rating_Registration.recordType-meta.xml
<RecordType>
    <fullName>Ongoing_Quality_Rating_Registration</fullName>
    <active>true</active>
    <description>This record type will be used for ongoing quality rating transactions except annual reports</description>
    <label>SUTQ - Ongoing Registration</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/Quality_Rating_Registration.recordType-meta.xml
<RecordType>
    <fullName>Quality_Rating_Registration</fullName>
    <active>true</active>
    <description>Use this record type for Initial Quality Rating Registrations</description>
    <label>SUTQ - Initial Registration</label>
</RecordType>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program_Transaction_Source__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Program Transaction that created this record</inlineHelpText>
    <label>Program Transaction Source</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/Portal_Roles__c.field-meta.xml
<CustomField>
    <fullName>Portal_Roles__c</fullName>
    <label>Portal Roles</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OCLQSOwner</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
                <label>Level 4</label>
            </value>
            <value>
                <fullName>Director</fullName>
                <label>Level 3</label>
            </value>
            <value>
                <fullName>Licensing Admin</fullName>
                <label>Level 2</label>
            </value>
            <value>
                <fullName>SUTQ Consultant</fullName>
                <label>Level 1</label>
            </value>
            <value>
                <fullName>OCLQSSUTQ</fullName>
            </value>
            <value>
                <fullName>OCLQSLicensing</fullName>
            </value>
            <value>
                <fullName>OCLQSAdministrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JFS</fullName>
            </value>
            <value>
                <fullName>ODE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/recordTypes/Portal_Roles.recordType-meta.xml
<RecordType>
    <fullName>Portal_Roles</fullName>
    <active>true</active>
    <description>This record type is used to create Portal Roles</description>
    <label>Portal Roles</label>
</RecordType>

force-app/main/default/classes/CLQ_90_Priordate_notification_Batch.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_90_Priordate_notification_Batch 
** Description      : Batch class to Send program email notification 90 days from expiration date
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**	Developer			Date			Version		Description
**	Pradeep Ravi		04/04/2017		1.1			Code Cleanup, Fix for 10916 - Updated the query to look for PT SUTQ IR and OR. Added logging for batch job. 
**	Neetu Ojha			06/08/2017		1.2			CR-11200; Email Matrix Change
**  Pradeep Ravi        07/07/2017      1.3         Included condition to process batch only for Program with status 
												    Open, New or Enforcement - Defect 11452  
**  Sujith Balakrishnan 04/03/2020      1.4         TFS#16356,16357 Stopping missed deadline when when expedited registration is submitted
**************************************************************************************************************/
global with sharing class CLQ_90_Priordate_notification_Batch implements Database.Batchable<sObject>{
    // Declaring a boolean to capture logs when there are no records to process
    public boolean recToProcess = false;
    public static final String completed = 'Completed';
    public static final String Newstring = 'New';
    public static final String Enforcement = 'Enforcement';
    public static final String Open = 'Open';
    public static Set<string> recordType_developername_set = new Set<String>{'Quality_Rating_Registration','Ongoing_Quality_Rating_Registration'};
    public static final String Portal_Roles = 'Portal_Roles';
    public static final String JFS = 'JFS';
    public static Set<string> Portal_Roles_Set = new Set<String>{'Owner', 'Director', 'SUTQ Consultant'};  
    public static final String SUTQ = 'SUTQ_Email_Missed_Ongoing_Reg_Filing_Deadline';   
    public static final String SJ = 'SJ-001.3';
    public static final String email1 = 'NOREPLY@TEST.COM';
    public static final String email2 = 'mvg@deloitte.com';
    public static final String LogBatchMessage1 = 'Reminder Mails Sent';
    public static final String LogBatchMessage2 = 'No Records found to send reminder eMails';
    public static final String LogBatchMessage3 = 'No Records to Process';
    public static final String success = 'Success';
    public static final String cause = 'Cause:';
    public static final String line = 'Line:'; 
    public static List<CLQ_90_Priordate_notification_Batch__mdt> CLQ_90_Priordate_notification_BatchList = [Select label from CLQ_90_Priordate_notification_Batch__mdt];
    
    global Database.QueryLocator start(Database.BatchableContext BC)
	{
        //set the scope by defining records
        //Retrieves all programs, ratings and emails where the Rating expiration date is equal to 90 days from today and expiration date        
		return Database.getQueryLocator([Select id,Program_Rating__c,CLQ_Program_Email__c from CLQ_Program__c
		        						 where Rating_Expiration_Date__c != null  
		        						 and Rating_Expiration_Date__c =: date.today().addDays(89)
										 AND (CLQ_Program_Status__c = :Open OR CLQ_Program_Status__c = :Newstring OR CLQ_Program_Status__c = :Enforcement)
										 ]
										 );
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope)
    {
    	try
    	{	
            Set<String> CLQ_Transaction_Status_Set = new Set<String>();
            for(CLQ_90_Priordate_notification_Batch__mdt mdt : CLQ_90_Priordate_notification_BatchList){
                CLQ_Transaction_Status_Set.add(mdt.label);
            }
            recToProcess = true;		
			List<CLQ_Program__c> clqPrgmLst = new List<CLQ_Program__c>();
			List<CLQ_Program__c> updateCLQPrgmLst = new List<CLQ_Program__c>();
			Set<id> clqPrgmIdLst  = new Set<Id>();  

	        //Retrieve Program Ids from the Scope 		
			for(SObject s: scope){
				CLQ_Program__c clqPrgrm = (CLQ_Program__c)s;
				clqPrgmIdLst.add(clqPrgrm.id);
			}//end for loop 

			List<CLQ_Program__c> clqPrgLst = new List<CLQ_Program__c>();

	        //Retrieve ODE program Id,CLQ_Associated_Organization__c,CLQ_Associated_Organization__r.Id,Recordtype.name,CLQ_Program_Email__c,
	        //Rating_Discontinue__c,Program_Rating__c,Rating_Expiration_Date__c, Rating_Anniversary_Date__c,Rating_Effective_Date__c,
	        //Program Transaction Id, Transaction submission date for all SUTQ Annual reports and SUTQ Ongoing Registrations
	        //From programs in scope 
			if(clqPrgmIdLst.size() >0 || clqPrgmIdLst != null)
			{
				clqPrgLst =  [select id,CLQ_Associated_Organization__c,CLQ_Associated_Organization__r.Id,Recordtype.name,
							  CLQ_Program_Email__c,Rating_Discontinue__c,Program_Rating__c,Rating_Expiration_Date__c,
							  Rating_Anniversary_Date__c,Rating_Effective_Date__c,
							  (select id,Submission_Date1__c,CLQ_Transaction_Status__c 
							   from Program_Transactions__r 
							   where recordType.developername 
							   in :recordType_developername_set
							   AND CLQ_Transaction_Status__c 
							   IN  : CLQ_Transaction_Status_Set 
	                          AND Submission_Date1__c != null
	                          ORDER BY CreatedDate),
	                          (Select Id, CLQ_Contact__r.Email from Roles__r 
												where RecordType.developername = :Portal_Roles AND Role_Type__c = :JFS 
												AND CLQ_Contact__r.Email != null AND Portal_Roles__c IN :Portal_Roles_Set ) //CR-11200  
							  from CLQ_Program__c 
							  where id=:clqPrgmIdLst];

	        	//Retrieve Org Wide Email Address from OCLQS - used as the "from" email address   
				OrgWideEmailAddress[] owea = [select Id 
											  from OrgWideEmailAddress 
											  where Address = :email2];

	        	//Dummy contact - technically used only for sending emails - NO functional dependency    										  
				Contact cnt = [SELECT Id 
							   From Contact 
							   Where Email!=null 
							   and Email = :email1 Limit 1];			

	        	//Retrieve Appropriate Email Template for this scenario, content of email is driven from this query     
				List<EmailTemplate> lstEmailTemplates = [SELECT Id, Body, Subject from EmailTemplate where 
													   DeveloperName = :SUTQ];	

				//Collection of mails we'll be sending 
	        	List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();												   					   							  
				Map<Id,List<String>> finalMapPTtoEmail = new Map<Id,List<String>>();
				List<CLQ_Program__c> ODEPrograms = new List<CLQ_Program__c>();

	            //Get all the ODE programs			
				for(CLQ_Program__c prog : clqPrgLst )
				{
					if(prog.RecordType.Name == Label.PreSchoolRecType || prog.RecordType.Name == Label.SACCRecType)
					{
						ODEPrograms.add(prog);
					}
				}//End of loop

	            //Get the send to email address for each program			
				if(!ODEPrograms.isEmpty() && ODEPrograms != null)
				{
					finalMapPTtoEmail =  CLQ_GlobalWebserviceUtility.getAllRecipientsSUTQBatchProg(ODEPrograms);
				}

                //Count for logging success 
                Integer totalNoMailRecCnt = 0;
                Integer totalSuccessCnt = 0;

				for(CLQ_Program__c cp : clqPrgLst)  
				{    
					totalNoMailRecCnt++;
					List<CLQ_Program_Transaction__c> cptLst = cp.Program_Transactions__r;
					//Date strDate  = cp.Rating_Effective_Date__c.addDays(180);
					// Date endDate = cp.Rating_Expiration_Date__c.addDays(-90);
					//boolean flag = false; 

					//Start date 180 day after Rating Effective date
					//Date strDate  = cp.Rating_Effective_Date__c.addDays(180);//16357
                    Date strDate  = cp.Rating_Effective_Date__c;//16357
					//Start date 90 days prior to Expiration date				
					Date endDate = cp.Rating_Expiration_Date__c.addDays(-89);

	            	boolean processFurther = false;
	                //Check if the AR/OR submission date is between 180 days after rating effective date and 90 days before Rating expiration date            	
					if(cptLst.size()> 0 && !cptLst.isEmpty()){
						for(CLQ_Program_Transaction__c cpt: cptLst)
						{
							Datetime local_Submission_Date1 = convertDateTimetoLocalTimeZone(cpt.Submission_Date1__c);
							//Check if PT submission is between 180 days after rating effective date and 90 days before Rating expiration date
							if(local_Submission_Date1.date() >= strDate && local_Submission_Date1.date() <= endDate)
							{
	                        	processFurther = true;
						    }
						}
					}
                    else
                        processFurther=true;//16356
					if(!processFurther)
					{
						List<String> emailList= new List<String>(); 
						List<String> emailCCList = new List<String>();//CR-11200
						//List<String> emailaddress = new List<String>();
		                List<String> tempEmailList = new List<String>();
		                tempEmailList.add('mvg@deloitte.com');  					
						if(cp.CLQ_Program_Email__c != null)
						{
							emailList.add(cp.CLQ_Program_Email__c);
						}
						Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
						mail.setTemplateId(lstEmailTemplates[0].Id);               
						mail.setSaveAsActivity(true);
						mail.setTargetObjectId(cnt.ID);// Any contact or User id of your record
	        			//If record type is ODE get the send to email address from map   					
						if(cp.Recordtype.name == Label.PreSchoolRecType  || cp.Recordtype.name == Label.SACCRecType)
						{
					            if(finalMapPTtoEmail.containsKey(cp.Id)){
				                List<String> emailaddress = new List<String>();
				                for(String email : finalMapPTtoEmail.get(cp.Id)){
				                    emailaddress.add(email);
				                }
				                mail.setToAddresses(tempEmailList);
				            }
				            mail.setToAddresses(tempEmailList);
				        }
				        else
				        {
				            mail.setToAddresses(tempEmailList);
				            //CR-11200 Starts
				            for(CLQ_Role__c roleObj : cp.Roles__r){
				            	emailCCList.add(roleObj.CLQ_Contact__r.Email);
				            }
				            
				            if(!emailCCList.isEmpty()){
				            	mail.setCcAddresses(emailCCList);
				            }
				            //CR-11200 Ends 				            
				        }
						if ( owea.size() > 0 ) 
						{
							mail.setOrgWideEmailAddressId(owea.get(0).Id);
						}
						mail.setWhatId(cp.id); // Enter your record Id whose merge field you want to add in template
						mails.add(mail);
						totalSuccessCnt++;
					}//End if reminder mails are to be sent
				}//End loop for programs
				/*if(updateCLQPrgmLst != null && !updateCLQPrgmLst.isEmpty())
				update updateCLQPrgmLst; */
				//Debug Printing below
				//End debug printing
				//send all emails at once in bulk - avoids exhausting salesforce govenor limits
				if(!mails.isEmpty())
				{  
					Messaging.sendEmail(mails);					
					Integration_Transaction_Logs.LogBatchMessage(SJ,LogBatchMessage1, success, totalSuccessCnt, totalSuccessCnt, 0);             
				}
				else
				{
					totalNoMailRecCnt = totalNoMailRecCnt-totalSuccessCnt; 
					Integration_Transaction_Logs.LogBatchMessage(SJ,LogBatchMessage2, success, totalNoMailRecCnt, 0, 0); 
				}
			}//End if program list not null  
		}
        catch(Exception e)
        {
            Integration_Transaction_Logs.LogErrorRealTime(SJ,e.getMessage()  ,cause + e.getCause(), line +e.getLineNumber(), e.getStackTraceString(), e.getTypeName());
        }      
    }    
	
    global void finish(Database.BatchableContext bc)
	{
        String IntLogID = SJ;
        // Check batch status - IF not COMPLETED then send notification
        AsyncApexJob jobStatus = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email, ExtendedStatus
                                        from AsyncApexJob where Id = :BC.getJobId()];        
        
        if(jobStatus.Status != completed || jobStatus.NumberOfErrors > 0)
        {
            Integration_Transaction_Logs.LogBatchMessage(IntLogID,jobStatus.ExtendedStatus,jobStatus.status,jobStatus.TotalJobItems,jobStatus.JobItemsProcessed,jobStatus.NumberOfErrors);   
        }
        if(!recToProcess)
        {
            Integration_Transaction_Logs.LogBatchMessage(IntLogID,LogBatchMessage3, success, 0, 0, 0); 
        }		
    }

    //Method to convert Datetime value to local timezone
    public Datetime convertDateTimetoLocalTimeZone(Datetime myDate){
        Datetime convertedDateTime;
        if(myDate != null){
            
            convertedDateTime = myDate.date();
            convertedDateTime = convertedDateTime.addHours(myDate.hour());
            convertedDateTime = convertedDateTime.addMinutes(myDate.minute());
            convertedDateTime = convertedDateTime.addSeconds(myDate.second());
            
        }
        return convertedDateTime;
    }//end method
}