force-app/main/default/objects/Background_Check__c/Background_Check__c.object-meta.xml
<CustomObject>
    <label>Background Check</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>SEQUENCE_NUMBER</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Background Check</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Background_Check__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <description>Applicant Full Name derived by combing First Name, Middle Name and Last Name</description>
    <formula>IF( Middle_Name__c != Null, First_Name__c  &amp;&apos; &apos; &amp;   Middle_Name__c  &amp;&apos; &apos;  &amp;  Last_Name__c, First_Name__c  &amp;&apos; &apos; &amp;  Last_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Out of State</fullName>
            </value>
            <value>
                <fullName>New Hire</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Background_Check_Status__c.field-meta.xml
<CustomField>
    <fullName>Background_Check_Status__c</fullName>
    <label>Background Check Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Admin Processing</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Consent_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Due_Date__c</fullName>
    <label>Consent Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Consent_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received_Date__c</fullName>
    <label>Consent Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipLabel>Background Check</relationshipLabel>
    <relationshipName>Background_Check</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Juvenile__c.field-meta.xml
<CustomField>
    <fullName>Juvenile__c</fullName>
    <label>Juvenile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Background Check</relationshipLabel>
    <relationshipName>Background_Check</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Background_Check__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <formula>Contact_Id__c  &amp;  Organization_Id__c  &amp;  (  TEXT( Consent_Received_Date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_County__c/CLQ_County__c.object-meta.xml
<CustomObject>
    <description>List of OH county a Organization/Program can operate from</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Number__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Number__c</fullName>
    <formula>IF(ISBLANK(CLQ_Legacy_Program_Number__c),
IF(or(contains(RecordType.Name,&apos;FCC&apos;),RecordType.Name = &apos;Child Care Center&apos;,RecordType.Name = &apos;Out of State Registration&apos;,RecordType.Name = &apos;In-Home Aide&apos;,RecordType.Name = &apos;Day Camp&apos; ),
&apos;2&apos;&amp;CLQ_Program_ID__c ,
IF(or(RecordType.Name=&apos;Pre School&apos;,RecordType.Name=&apos;School Age Child Care&apos;),
&apos;1&apos;&amp;CLQ_Program_ID__c,null)),CLQ_Legacy_Program_Number__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/fetchAllRelatedRecords.cls
public with sharing class fetchAllRelatedRecords {
        @AuraEnabled(cacheable=true)
        public static string getBgList(Background_Check__c backgroundcheckRecord, string firstName, string lastName, string ssn, date dob, string facilityNum, string facilityName, string applicantName,string county,string applicationType,date consentReceivedDate,string juvenile,string bgCheckStatus) {
               
           // create contact list to store search result 
            list<Background_Check__c> bgFullListRecord = new list<Background_Check__c>();
            list<String> UniqueIdList = new list<String>();

            String filters = '';
            String jsonDT = '';
            
            if(firstName != '') {
             filters = 'First_Name__c Like :firstName';
            }
            if(lastName != '') {
                filters = filters + (!String.isBlank(filters) ?  (' AND Last_Name__c Like :lastName ') : (' Last_Name__c Like :lastName '));
            }
            if(ssn != '') {
                filters = filters + (!String.isBlank(filters) ? (' AND SSN__C Like :ssn ') : (' SSN__C Like :ssn '));
            }
            if(dob != null) {
                filters = filters + (!String.isBlank(filters) ? (' AND Date_of_Birth__c = :dob ') : (' Date_of_Birth__c = :dob '));
            }
            if(facilityName != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND Program__r.Name like :facilityName ') : (' Program__r.Name like :facilityName '));
            }
            if(facilityNum != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND Program__r.CLQ_Program_Number__c like :facilityNum ') : (' Program__r.CLQ_Program_Number__c like :facilityNum '));
             }
             if(applicantName != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND Applicant_Name__c like :applicantName ') : (' Applicant_Name__c like :applicantName '));
             }
             if(county != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND County__r.Id = :county ') : (' County__r.Id = :county '));
             }
             if(applicationType != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND Application_Type__c Like :applicationType ') : (' Application_Type__c Like :applicationType' ));
             }
             if(consentReceivedDate != null) {
                filters = filters + (!String.isBlank(filters) ? (' AND Consent_Received_Date__c = :consentReceivedDate ') : (' Consent_Received_Date__c = :consentReceivedDate '));
             }
             if(juvenile != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND Juvenile__c Like :juvenile ') : (' Juvenile__c Like :juvenile' ));
             }
             if(bgCheckStatus != ''){
                filters = filters + (!String.isBlank(filters) ? (' AND Background_Check_Status__c Like :bgCheckStatus ') : (' Background_Check_Status__c Like :bgCheckStatus' ));
             }

           // query contact records
           String query = 'SELECT id,Email_Address__c,First_Name__c,Last_Name__c,Phone_Number__c,Consent_Received_Date__c,Consent_Due_Date__c,Application_Type__c,Unique_Id__c FROM Background_Check__c';
           if(!String.isBlank(filters)) {
            query += ' WHERE ' + filters + ' ORDER BY Application_Type__c, Consent_Received_Date__c';
          }
          System.debug('Query-->'+ query);
          Integer totalRecords = 0;
             for(Background_Check__c conObj : Database.query(query)){
                system.debug('Is contains' +UniqueIdList.contains(conObj.Unique_Id__c));
                boolean isUnique = UniqueIdList.contains(conObj.Unique_Id__c);
                if(isUnique == false){
                    if(String.isNotBlank(conObj.Unique_Id__c)){
                        UniqueIdList.add(conObj.Unique_Id__c);
                    }
                    bgFullListRecord.add(conObj);
                    totalRecords+=1;
                }
                
             }
             system.debug('Full List'+bgFullListRecord);
             if(bgFullListRecord.size() == 0){
                throw new AuraHandledException('No Record Found..'); 
             }
             
            //return bgListRecord;
            BackgroundCheckDTWrapper objDT =  new BackgroundCheckDTWrapper();  
            objDT.totalRecords = totalRecords;
            objDT.bgFullrecords = bgFullListRecord;

            jsonDT = JSON.serialize(objDT);
            return jsonDT;
        }

        public class BackgroundCheckDTWrapper {
            public Integer totalRecords {get;set;}
            public List<Background_Check__c> bgFullrecords {get;set;}
        }

        @AuraEnabled(cacheable=true)
        public static List<OptionWrapper> getCountyList(){
            List<OptionWrapper> countyNameList = new List<OptionWrapper>();
            List<CLQ_County__c> countyList = new List<CLQ_County__c>();
            for(CLQ_County__c county :[SELECT Id, Name FROM CLQ_County__c]){
                countyNameList.add(new OptionWrapper(county.Name, county.Name));
              }
           
           return countyNameList; 
        }
        public class OptionWrapper {
            @AuraEnabled
            public String label {get; set;}
            @AuraEnabled
            public String value {get; set;}
    
            public OptionWrapper(String label, String value) {
                this.label = label;
                this.value = value;
            }
        }

    @AuraEnabled(cacheable=true)
    public static list<sObject> fetchLookupData(string searchKey ) {    
        List < sObject > returnList = new List < sObject > ();
        string sWildCardText = '%' + searchKey + '%';
        string sQuery = 'Select Id,Name From CLQ_County__c  Where Name Like : sWildCardText order by createdDate DESC LIMIT 5';
        for (sObject obj: database.query(sQuery)) {
            returnList.add(obj);
        }
        return returnList;
    }

    @AuraEnabled
    public static sObject fetchDefaultRecord(string recordId) {
        string sRecId = recordId;    
        string sQuery = 'Select Id,Name From CLQ_County__c Where Id = : sRecId LIMIT 1';
        for (sObject obj: database.query(sQuery)) {
            return obj;
        }
        return null;
    }
    }