force-app/main/default/objects/PGFSection__c/PGFSection__c.object-meta.xml
<CustomObject>
    <description>Section metadata object for framework.</description>
    <label>Section</label>
    <nameField>
        <label>FB_Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PageSection.cls
public class PageSection {
    public String Id {get; set;}
    public Decimal OrderNumber {get; set;}
    public String Label {get; set;}
    public List<PageSubSection> SubSections {get; set;}
    public String Status {get; set;}
    public String Name {get; set;}

    public PageSection(PGFSection__c section, String sStatus, string language){
        this.Id = String.valueOf(section.Id);
        this.OrderNumber = section.OrderNumber__c;
        this.Label = section.Label__c;
        this.SubSections = new List<PageSubSection>();
        this.Status = sStatus;
        this.Name = section.Name;
    }
}