force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/CLQ_Corrective_Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object links Inspection and Findings</description>
    <label>Corrective Action Plan</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Corrective Action No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corrective Action Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_CAP_Complete__c.field-meta.xml
<CustomField>
    <fullName>CLQ_CAP_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAP Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_CAP_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_CAP_Status__c</fullName>
    <label>CAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed - Not Addressed</fullName>
            </value>
            <value>
                <fullName>Report Revised - Not Required</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>CAP Revised</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Corrective Action Plans</relationshipLabel>
    <relationshipName>Corrective_Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Is_All_CAP_Approved__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Is_All_CAP_Approved__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is All CAP Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Original_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Original_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Associated Inspections (Follow-Ups)</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_CAP_Complete__c.field-meta.xml
<CustomField>
    <fullName>CLQ_CAP_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAP Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CLQ_CorrectiveActionPlanHandler_Test.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_CorrectiveActionPlanHandler_Test
** Description      : This class contains unit tests for validating the behavior of Apex classes and triggers.
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A	            1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/ 
@isTest(isparallel = true)
private class CLQ_CorrectiveActionPlanHandler_Test {
    @testSetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    @IsTest
    static void updateCAPInfoOnInspectionTest() {
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_Inspection__c Inspection = new CLQ_Inspection__c();
            insert Inspection;
            CLQ_Inspection__c InspectionRet = [SELECT id, CLQ_Is_All_CAP_Approved__c, (SELECT Id, CLQ_CAP_Status__c FROM Corrective_Action_Plans__r)
                                               FROM CLQ_Inspection__c
                                               WHERE Id = :Inspection.Id ];
            system.AssertEquals(true,InspectionRet.CLQ_Is_All_CAP_Approved__c,'Testing');
            system.AssertEquals(0,InspectionRet.Corrective_Action_Plans__r.size(),'Testing');
            
            CLQ_Corrective_Action_Plan__c plan = new CLQ_Corrective_Action_Plan__c(
                CLQ_CAP_Status__c = 'Submitted',
                CLQ_Inspection__c = Inspection.Id);
            insert plan;
            
            InspectionRet = [SELECT id, CLQ_Is_All_CAP_Approved__c, (SELECT Id, CLQ_CAP_Status__c FROM Corrective_Action_Plans__r)
                             FROM CLQ_Inspection__c
                             WHERE Id = :Inspection.Id ];
            system.AssertEquals(false,InspectionRet.CLQ_Is_All_CAP_Approved__c,'Testing');
            system.AssertEquals(1,InspectionRet.Corrective_Action_Plans__r.size(),'Testing');
            
            plan.CLQ_CAP_Status__c = 'Approved';
            CLQ_CorrectiveActionPlanTriggerHandler.HasUpdated = false;
            update plan;
            
            InspectionRet = [SELECT id, CLQ_Is_All_CAP_Approved__c
                             FROM CLQ_Inspection__c
                             WHERE Id = :Inspection.Id ];
            system.AssertEquals(true,InspectionRet.CLQ_Is_All_CAP_Approved__c,'Testing');
            
            plan.CLQ_CAP_Status__c = 'Revised';
            CLQ_CorrectiveActionPlanTriggerHandler.HasUpdated = false;
            update plan;
            
            InspectionRet = [SELECT id, CLQ_Is_All_CAP_Approved__c
                             FROM CLQ_Inspection__c
                             WHERE Id = :Inspection.Id ];
            system.AssertEquals(false,InspectionRet.CLQ_Is_All_CAP_Approved__c,'Testing');
            
            plan.CLQ_CAP_Status__c = 'Report Revised - Not Required';
            CLQ_CorrectiveActionPlanTriggerHandler.HasUpdated = false;
            update plan;
            
            InspectionRet = [SELECT id, CLQ_Is_All_CAP_Approved__c
                             FROM CLQ_Inspection__c
                             WHERE Id = :Inspection.Id ];
            system.AssertEquals(true,InspectionRet.CLQ_Is_All_CAP_Approved__c,'Testing');
        }
    }
    
    @IsTest
    static void updateCAPInfoOnTransactionTest() {
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_Program_Transaction__c ProgramTransaction = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'Application - FCC');
            
            CLQ_Inspection__c Inspection = new CLQ_Inspection__c(CLQ_Program_Transaction__c = ProgramTransaction.Id);
            insert Inspection;
            CLQ_Program_Transaction__c ProgramTransactionRet = [SELECT id, CLQ_CAP_Complete__c, 
                                                                (SELECT Id, CLQ_Is_All_CAP_Approved__c FROM Inspections__r)
                                                                FROM CLQ_Program_Transaction__c
                                                                WHERE Id = :ProgramTransaction.Id ];
            system.AssertEquals(false,ProgramTransactionRet.CLQ_CAP_Complete__c,'Testing');
            system.AssertEquals(1,ProgramTransactionRet.Inspections__r.size(),'Testing');
            
            CLQ_Corrective_Action_Plan__c plan = new CLQ_Corrective_Action_Plan__c(
                CLQ_CAP_Status__c = 'Submitted',
                CLQ_Inspection__c = Inspection.Id);
            insert plan;
            
            ProgramTransactionRet = [SELECT id, CLQ_CAP_Complete__c
                                     FROM CLQ_Program_Transaction__c
                                     WHERE Id = :ProgramTransaction.Id ];
            system.AssertEquals(false,ProgramTransactionRet.CLQ_CAP_Complete__c,'Testing');
            
            plan.CLQ_CAP_Status__c = 'Approved';
            CLQ_CorrectiveActionPlanTriggerHandler.HasUpdated = false;
            update plan;
            
            ProgramTransactionRet = [SELECT id, CLQ_CAP_Complete__c
                                     FROM CLQ_Program_Transaction__c
                                     WHERE Id = :ProgramTransaction.Id ];
            system.AssertEquals(false,ProgramTransactionRet.CLQ_CAP_Complete__c,'Testing');
            
            plan.CLQ_CAP_Status__c = 'Revised';
            CLQ_CorrectiveActionPlanTriggerHandler.HasUpdated = false;
            update plan;
            
            ProgramTransactionRet = [SELECT id, CLQ_CAP_Complete__c
                                     FROM CLQ_Program_Transaction__c
                                     WHERE Id = :ProgramTransaction.Id ];
            system.AssertEquals(false,ProgramTransactionRet.CLQ_CAP_Complete__c,'Testing');
            
            plan.CLQ_CAP_Status__c = 'Report Revised - Not Required';
            CLQ_CorrectiveActionPlanTriggerHandler.HasUpdated = false;
            update plan;
            
            ProgramTransactionRet = [SELECT id, CLQ_CAP_Complete__c
                                     FROM CLQ_Program_Transaction__c
                                     WHERE Id = :ProgramTransaction.Id ];
            system.AssertEquals(false,ProgramTransactionRet.CLQ_CAP_Complete__c,'Testing');
        }
        
    }    
}