force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/CLQ_Corrective_Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object links Inspection and Findings</description>
    <label>Corrective Action Plan</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Corrective Action No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corrective Action Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <formula>CLQ_Program__r.CLQ_Associated_Organization__r.Name</formula>
    <label>Associated Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Corrective Action Plans</relationshipLabel>
    <relationshipName>Corrective_Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Organization this individual as a role with</inlineHelpText>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Organization_Individual</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Status__c</fullName>
    <description>This field describes the current role status of the contact on the program.</description>
    <label>Program Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending Removal</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/Portal_Roles__c.field-meta.xml
<CustomField>
    <fullName>Portal_Roles__c</fullName>
    <label>Portal Roles</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Role_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OCLQSOwner</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
                <label>Level 4</label>
            </value>
            <value>
                <fullName>Director</fullName>
                <label>Level 3</label>
            </value>
            <value>
                <fullName>Licensing Admin</fullName>
                <label>Level 2</label>
            </value>
            <value>
                <fullName>SUTQ Consultant</fullName>
                <label>Level 1</label>
            </value>
            <value>
                <fullName>OCLQSSUTQ</fullName>
            </value>
            <value>
                <fullName>OCLQSLicensing</fullName>
            </value>
            <value>
                <fullName>OCLQSAdministrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLQ_GlobalWebService3.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_GlobalWebService3
** Description      : Class to send email
** Version          : 1.2
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer           Date                Version         Description
**	Neetu Ojha			10/09/2017			1.1				TFS#11785 - Fix to remove Inactive/ Denied Role while sending email.
**  Neetu Ojha          11/02/2017          1.2             TFS#11799
**************************************************************************************************************/

global with sharing class CLQ_GlobalWebService3 {

     @InvocableMethod(label='Send CAP Email' description='Allows an email to be sent using apex, combine template and CAPRecordID id separated by pipe')
    public static void sendCAPEmail(list<string> templateAndRecordID) {  

        for (string tempRec : templateAndRecordID){
            list<string> callParms = tempRec.split('\\|');
            sendCAPEmail(callParms[0], callParms[1]);
        }
    }  
    
    webservice static void sendCAPEmail(string templateName, id CAPRecordID) {

        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        CLQ_Corrective_Action_Plan__c capRecord;
        if(CAPRecordID!=null && Schema.SObjectType.CLQ_Corrective_Action_Plan__c.isAccessible()){
        capRecord = [select id,CLQ_Program__r.id,CLQ_Program__r.CLQ_Associated_Organization__r.id from CLQ_Corrective_Action_Plan__c where id = :CAPRecordID limit 1];
        }
        list<string> toAddressesLICENSING = CLQ_GlobalWebserviceUtility.getAllRecipientsLicensing(capRecord.CLQ_Program__r.Id,capRecord.CLQ_Program__r.CLQ_Associated_Organization__r.id,null);
        
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'jshivakumar@deloitte.com'];
        if(toAddressesLICENSING.size() > 0 ){
           try{
               EmailTemplate templateForEmail;
               if(templateName!=null &&  Schema.SObjectType.EmailTemplate.isAccessible()){
               templateForEmail = [select id from EmailTemplate where DeveloperName = :templateName]; //11799
               }
               CLQ_Role__c roleForEmail;
               if(capRecord!=null &&  Schema.SObjectType.CLQ_Role__c.isAccessible()){
                   
               roleForEmail = [select id,CLQ_Contact__r.id from CLQ_Role__c 
               									where Portal_Roles__c IN ('OCLQSOwner','OCLQSSUTQ','OCLQSAdministrator') 
               									and ( CLQ_Program__r.id = :capRecord.CLQ_Program__r.id 
               										or CLQ_Organization__r.id = :capRecord.CLQ_Program__r.CLQ_Associated_Organization__r.id)
               									AND CLQ_Status__c NOT IN ('Inactive', 'Denied') limit 1]; //11785
               }
               msg.settargetObjectID(roleForEmail.CLQ_Contact__r.id);
               msg.setwhatID(capRecord.id);
               msg.setTemplateId(templateForEmail.id);
               msg.setToaddresses(toAddressesLICENSING);
               if ( owea.size() > 0 ) {
                   msg.setOrgWideEmailAddressId(owea.get(0).Id);
               }
               msg.setTreatTargetObjectAsRecipient(false);
               //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { msg });
            }
            catch(QueryException e){
                system.debug('exception:'+e);
            }
        }
    }
}