force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_County__c/CLQ_County__c.object-meta.xml
<CustomObject>
    <description>List of OH county a Organization/Program can operate from</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_County__c/fields/Area_Region__c.field-meta.xml
<CustomField>
    <fullName>Area_Region__c</fullName>
    <label>Area/Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Eastern</fullName>
            </value>
            <value>
                <fullName>Northern</fullName>
            </value>
            <value>
                <fullName>Piedmont</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_County__c/fields/CCC_Field_Officers__c.field-meta.xml
<CustomField>
    <fullName>CCC_Field_Officers__c</fullName>
    <label>CCC Field Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDSS/CENTRAL LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/PIEDMONT LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS_CHILD_WELFARE_LICENSING</fullName>
                <label>VDSS/CHILD_WELFARE_LICENSING</label>
            </value>
            <value>
                <fullName>VDSS/PENINSULA LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/EASTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/VALLEY LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/FAIRFAX LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/WESTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/NORTHERN LICENSING OFFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_County__c/fields/FCC_Field_officers__c.field-meta.xml
<CustomField>
    <fullName>FCC_Field_officers__c</fullName>
    <label>FCC Field Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDSS/CENTRAL LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/PIEDMONT LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/CHILD WELFARE LICENSING UNIT</fullName>
            </value>
            <value>
                <fullName>VDSS/PENINSULA LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/EASTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/VALLEY LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/FAIRFAX LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/WESTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/NORTHERN LICENSING OFFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/CLQ_Facility_Schedule__c.object-meta.xml
<CustomObject>
    <label>Facility Schedule</label>
    <nameField>
        <label>Facility Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Days_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Days_of_Operation__c</fullName>
    <label>Days of Operation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_HOO_Time_1_End__c.field-meta.xml
<CustomField>
    <fullName>CLQ_HOO_Time_1_End__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLQ_Time_Intervals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_HOO_Time_1_Start__c.field-meta.xml
<CustomField>
    <fullName>CLQ_HOO_Time_1_Start__c</fullName>
    <description>User can set 2 ranges for start/end time for each schedule.</description>
    <inlineHelpText>Hours of Operation start time for range 1.</inlineHelpText>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLQ_Time_Intervals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_HOO_Time_2_End__c.field-meta.xml
<CustomField>
    <fullName>CLQ_HOO_Time_2_End__c</fullName>
    <label>End Time 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLQ_Time_Intervals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_HOO_Time_2_Start__c.field-meta.xml
<CustomField>
    <fullName>CLQ_HOO_Time_2_Start__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLQ_Time_Intervals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Facility Schedules</relationshipLabel>
    <relationshipName>Facility_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/CLQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Facility_Schedule__c/fields/Months_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Months_of_Operation__c</fullName>
    <inlineHelpText>Pick one or more months; if selected &quot;Year Round&quot; or &quot;Summer Only&quot;, no other months can be selected.</inlineHelpText>
    <label>Months of Operation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Year Round</fullName>
            </value>
            <value>
                <fullName>Summer Only</fullName>
            </value>
            <value>
                <fullName>School Year</fullName>
            </value>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Child_Care_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Child_Care_Center</fullName>
    <active>true</active>
    <description>VDSS - Child Care Centers</description>
    <label>Child Care Center</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Pre_School.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Pre_School</fullName>
    <active>true</active>
    <description>ODE - PS (Pre-School)</description>
    <label>Pre School</label>
</RecordType>

force-app/main/default/globalValueSets/CLQ_Time_Intervals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>12:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>01:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>01:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>01:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>01:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>02:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>02:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>02:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>02:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>03:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>03:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>03:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>03:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>04:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>04:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>04:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>04:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>05:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>05:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>05:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>05:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>06:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>06:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>06:30 AM</fullName>
    </customValue>
    <customValue>
        <fullName>06:45 AM</fullName>
    </customValue>
    <customValue>
        <fullName>07:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>07:15 AM</fullName>
    </customValue>
    <customValue>
        <fullName>09:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>09:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 PM</fullName>
    </customValue>
    <description>15 minute time intervals</description>
    <masterLabel>Time Intervals</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLQ_FacilityScheduleTriggerHandler_Test.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_FacilityScheduleTriggerHandler_Test 
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  Pradeep Ravi            01/03/2019      1.0          Initial Build 
**************************************************************************************************************/
@isTest
private class CLQ_FacilityScheduleTriggerHandler_Test {
    @testSetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    
    public static final String COMMUNITY_PROFILE_ID = [Select Id from Profile Where Name = 'OCLQS Customer Community Plus Login User' limit 1 ].Id ;    
    
    @isTest static void test_method_three() {
        UserRole usrrole=[select Id,Name from UserRole where DeveloperName='State_Admin' limit 1];
        BusinessHours stdBusinessHours = [select id,TimeZoneSidKey from BusinessHours where isDefault = true limit 1];
        Id sysAdminProfileId = [SELECT Id FROM Profile WHERE  name ='System Administrator' LIMIT 1].Id;
        User usr1=[select id, UserRoleId, ProfileId, IsActive from User where UserRoleId !=null and ProfileId !=null and IsActive =true limit 1];
        Account accountRecord = new Account(Name='Demo Account') ;
        //accountRecord.ownerId = new OCLQS_ENVManager().getDefaultAccountOwnerId();
        accountRecord.ownerId=usr1.Id;
        accountRecord.CLQ_DIRN__c = '040063';       
        insert accountRecord ;
        
        List<Contact> cons = new List<Contact>() ;
        
        Contact profileRecordactivated = new Contact(FirstName ='act' , AccountId =accountRecord.Id , LastName ='ivated' , email ='act@gmail.com' , OPIN__c = '12345678', Portal_User_Activated__c = true );
        cons.add(profileRecordactivated) ;
        
        INSERT cons ;
        
        User usr = new User();
        usr.Username = 'activated@randomusername.com'; 
        usr.Email = 'activated@randomusername.com';
        usr.FirstName = 'Dumm';
        usr.LastName = 'uPromo.lastName';
        usr.ContactId = profileRecordactivated.Id;
        usr.ProfileId = COMMUNITY_PROFILE_ID;
        usr.IsActive = true ;
        
        
        transient string tempNickName = String.valueOf(Math.random()) + '-' + 'Dummy'  ;
        if(tempNickName.length() > 30 )
        {
            tempNickName = tempNickName.substring(2,30) ;
        }
        usr.CommunityNickname = tempNickName ; 
        
        
        usr.Alias = ('fdim' + 'dummy').substring(0,5);
        usr.languagelocalekey='en_US';
        usr.localesidkey='en_US';
        usr.timezonesidkey='America/Los_Angeles';
        usr.emailencodingkey='UTF-8';
        
        INSERT usr ;
        CLQ_County__c county = new CLQ_County__c(Name = 'CLARK', CCC_Field_Officers__c = 'Columbus', Area_Region__c='SW', FCC_Field_officers__c = 'Columbus' );
        insert county;
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
        insert configRecord; 
        CLQ_OCLQS_Configuration__c configRecord1 = new CLQ_OCLQS_Configuration__c(Name = 'Pre School');
        insert configRecord1;        
        Id progRecId = null;
        System.runAs(new user(ID=userinfo.getUserId())){
           Test.startTest();
            List<CLQ_Program__c> progList = new List<CLQ_Program__c>();
            List<Id> ProgIdList=new List<Id>();
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountRecord.id;
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Pre_School').getRecordTypeId();
            progList.add(programRecord) ;
            //Create a program record
            CLQ_Program__c programRecord1 = new CLQ_Program__c();
            programRecord1.Name = 'Test';
            programRecord1.CLQ_Associated_Organization__c = accountRecord.id;
            programRecord1.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Child_Care_Center').getRecordTypeId();
            progList.add(programRecord1) ;            
            insert progList;
            for(CLQ_Program__c prog:progList){
                ProgIdList.add(prog.Id);
            }
            List<CLQ_Facility_Schedule__c> fsList = new List<CLQ_Facility_Schedule__c>();
            CLQ_Facility_Schedule__c facShedule = new CLQ_Facility_Schedule__c(CLQ_Program__c=programRecord.Id,CLQ_Days_of_Operation__c='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',Months_of_Operation__c='Year Round', CLQ_HOO_Time_1_Start__c= '12:00 AM', CLQ_HOO_Time_1_End__c= '12:00 AM', CLQ_HOO_Time_2_Start__c = '09:00 AM',CLQ_HOO_Time_2_End__c = '10:00 PM',CLQ_Status__c='Active');
            fsList.add(facShedule);
            CLQ_Facility_Schedule__c facShedule1 = new CLQ_Facility_Schedule__c(CLQ_Program__c=programRecord.Id,CLQ_Days_of_Operation__c='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',Months_of_Operation__c='Year Round', CLQ_HOO_Time_1_Start__c= '12:00 AM', CLQ_HOO_Time_1_End__c= '12:00 PM', CLQ_HOO_Time_2_Start__c = '09:00 PM',CLQ_HOO_Time_2_End__c = '10:00 PM',CLQ_Status__c='Active');
            fsList.add(facShedule1);
            CLQ_Facility_Schedule__c facShedule2 = new CLQ_Facility_Schedule__c(CLQ_Program__c=programRecord1.Id,CLQ_Days_of_Operation__c='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',Months_of_Operation__c='Year Round', CLQ_HOO_Time_1_Start__c= '12:00 AM', CLQ_HOO_Time_1_End__c= '12:00 PM', CLQ_HOO_Time_2_Start__c = '09:00 PM',CLQ_HOO_Time_2_End__c = '10:00 PM',CLQ_Status__c='Inactive');
            fsList.add(facShedule2);            
            insert fsList;             
            CLQ_Facility_Schedule__c oldObject = new CLQ_Facility_Schedule__c();
            list<CLQ_Facility_Schedule__c>  OldList = new list<CLQ_Facility_Schedule__c>{fsList[2]};
            list<CLQ_Facility_Schedule__c>  NewList = new list<CLQ_Facility_Schedule__c>{fsList[0]};
            map<id,CLQ_Facility_Schedule__c>  OldMap = new map<id,CLQ_Facility_Schedule__c>{fsList[2].id => fsList[2]};
            map<id,CLQ_Facility_Schedule__c>  NewMap = new map<id,CLQ_Facility_Schedule__c>{fsList[0].id => fsList[0]};  
            CLQ_FacilityScheduleTriggerHandler Handler = new CLQ_FacilityScheduleTriggerHandler(newList, newMap, oldList, oldMap,
                                                                                    true, false, true, false, 
                                                                                    true, false, false, 1);        
            CLQ_FacilityScheduleTriggerHandler.updtProgTime(ProgIdList);                                 
            Test.stopTest();
            
			system.assertEquals(True, 1==1,'Testing');
        }
    }    
}