force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Alleged_Rule_Violation__c/CLQ_Alleged_Rule_Violation__c.object-meta.xml
<CustomObject>
    <description>Rules that apply to the programs</description>
    <label>Alleged Rule Violation</label>
    <nameField>
        <displayFormat>ARV-{00000000}</displayFormat>
        <label>Alleged Rule Violation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alleged Rule Violations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Alleged_Rule_Violation__c/fields/Case_Custom__c.field-meta.xml
<CustomField>
    <fullName>Case_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Custom</label>
    <referenceTo>CLQ_Case_Custom__c</referenceTo>
    <relationshipLabel>Alleged Rule Violations</relationshipLabel>
    <relationshipName>Alleged_Rule_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Alleged_Rule_Violation__c/fields/CLQ_Domain_Rule__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Domain_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Domain Rule</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>NOT (1)</booleanFilter>
        <filterItems>
            <field>CLQ_Domain_Rule__c.CLQ_Domain__r.Name</field>
            <operation>startsWith</operation>
            <value>Conversion</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CLQ_Domain_Rule__c</referenceTo>
    <relationshipLabel>Alleged Rule Violations</relationshipLabel>
    <relationshipName>Alleged_Rule_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/CLQ_Case_Custom__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/CLQ_Anonymous_Complainant__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Anonymous_Complainant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anonymous Complainant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/CLQ_Approver_s_Email__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approver_s_Email__c</fullName>
    <label>Approver&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/CLQ_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AR_Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/CLQ_Assigned_to_Email__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Assigned_to_Email__c</fullName>
    <label>Assigned to Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>CLQ_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <formula>TEXT(CLQ_Program__r.CLQ_Program_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Case_Custom__c/recordTypes/CLQ_Complaint.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Complaint</fullName>
    <active>true</active>
    <description>Complaint - select this record type when capturing a complaint against a Licensed Program</description>
    <label>Complaint</label>
</RecordType>

force-app/main/default/objects/CLQ_Domain__c/CLQ_Domain__c.object-meta.xml
<CustomObject>
    <description>Object to store the domain information for inspection rules</description>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Domain_Rule__c/CLQ_Domain_Rule__c.object-meta.xml
<CustomObject>
    <description>Junction object between Rules and Domain</description>
    <label>Domain Rule</label>
    <nameField>
        <displayFormat>DR#-{000000}</displayFormat>
        <label>Domain Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Domain Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Domain_Rule__c/fields/CLQ_Domain__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Domain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Domain</label>
    <referenceTo>CLQ_Domain__c</referenceTo>
    <relationshipLabel>Domain Rules</relationshipLabel>
    <relationshipName>Domain_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Assigned_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Assigned_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Licensor/specialist assigned to the program.</inlineHelpText>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Programs_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Issue_Date__c</fullName>
    <inlineHelpText>Date of issuance of license.</inlineHelpText>
    <label>Provisional License Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Licensing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Licensing_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensing Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <label>Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/classes/CLQ_AllegedRuleViolationTrigHandlerTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_AllegedRuleViolationTrigHandlerTest
** Description      : 
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A                     N/A             1.0         Initial Build 
**  Pavan Ayta              8/23/17         1.1         Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isparallel = true)
private class CLQ_AllegedRuleViolationTrigHandlerTest {
    @testSetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
    CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    @IsTest
    static void myUnitTest() {
        system.runAs(new user(ID = UserInfo.getUserID())){
            
        
        // TO DO: implement unit test
        //insert configuration record
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
        
        //Create account record
        Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
        insert accountrecord ;
        
        //Insert contact
        Contact contactrecord = new Contact(Firstname='test', lastName = 'Test',Accountid = accountrecord.id );
        insert contactrecord ;
        
        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
        programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserid();
        programRecord.CLQ_Program_Status__c = 'Open';
        programRecord.CLQ_License_Registration_Status__c='Licensed';
        programRecord.CLQ_License_Issue_Date__c =date.newInstance(2021, 11, 01); 
        programRecord.CLQ_Assigned_Reviewer__c=UserInfo.getUserid();
        insert programRecord ;
        
        //Insert case for program
        CLQ_Case_Custom__c caseRecord = new CLQ_Case_Custom__c();
        caseRecord.recordTypeID = Schema.SObjectType.CLQ_Case_Custom__c.getRecordTypeInfosByDeveloperName().get('CLQ_Complaint').getRecordTypeId();
        caseRecord.ContactId__c = contactrecord.id;
        caseRecord.CLQ_Program__c = programRecord.id;
        caseRecord.CLQ_Approver_s_Email__c = 'test@CLQ.com';
        caseRecord.CLQ_Assigned_to_Email__c = 'test@CLQ.com';
        caseRecord.CLQ_Anonymous_Complainant__c = true;
        caseRecord.CLQ_Assigned_To__c = UserInfo.getUserid();
        insert caseRecord;
        
        test.starttest();
        //create an alleged rule violation for the case
        //Added by MP - Begin - To handle Search filter validation on Domain Name
        CLQ_Domain__c domain = new CLQ_Domain__c();
        domain.Name = 'Administrative & Leadership Practices';
        Insert domain;
        CLQ_Domain__c dm = [Select id from CLQ_Domain__c where ID =: domain.Id];
        CLQ_Domain_Rule__c dr = new CLQ_Domain_Rule__c();
        dr.CLQ_Domain__c = dm.Id;
        //Added by MP - End - To handle Search filter validation on Domain Name
        insert dr;
        CLQ_Alleged_Rule_Violation__c arv = new CLQ_Alleged_Rule_Violation__c();
        arv.CLQ_Domain_Rule__c = dr.id;
        arv.Case_Custom__c = caseRecord.id;
        insert arv;
        delete arv;
        test.stoptest();
        system.assertEquals(True, 1==1,'Testing');
        }
    }
}