force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CLQ_Org_Wide_Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Org_Wide_Email_Addresses__c</fullName>
    <description>This field includes email addresses for all persons connected to this Organization though a Role. The Role Trigger updates this field, so it can be used to send out emails to all recipients.</description>
    <label>Org Wide Email Addresses</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/CLQ_Corrective_Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object links Inspection and Findings</description>
    <label>Corrective Action Plan</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Corrective Action No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corrective Action Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <formula>CLQ_Program__r.CLQ_Associated_Organization__r.Name</formula>
    <label>Associated Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Corrective Action Plans</relationshipLabel>
    <relationshipName>Corrective_Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_County__c/CLQ_County__c.object-meta.xml
<CustomObject>
    <description>List of OH county a Organization/Program can operate from</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_County__c/fields/Area_Region__c.field-meta.xml
<CustomField>
    <fullName>Area_Region__c</fullName>
    <label>Area/Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Eastern</fullName>
            </value>
            <value>
                <fullName>Northern</fullName>
            </value>
            <value>
                <fullName>Piedmont</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_County__c/fields/CCC_Field_Officers__c.field-meta.xml
<CustomField>
    <fullName>CCC_Field_Officers__c</fullName>
    <label>CCC Field Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDSS/CENTRAL LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/PIEDMONT LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS_CHILD_WELFARE_LICENSING</fullName>
                <label>VDSS/CHILD_WELFARE_LICENSING</label>
            </value>
            <value>
                <fullName>VDSS/PENINSULA LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/EASTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/VALLEY LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/FAIRFAX LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/WESTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/NORTHERN LICENSING OFFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_County__c/fields/FCC_Field_officers__c.field-meta.xml
<CustomField>
    <fullName>FCC_Field_officers__c</fullName>
    <label>FCC Field Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDSS/CENTRAL LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/PIEDMONT LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/CHILD WELFARE LICENSING UNIT</fullName>
            </value>
            <value>
                <fullName>VDSS/PENINSULA LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/EASTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/VALLEY LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/FAIRFAX LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/WESTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/NORTHERN LICENSING OFFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Issue_Date__c</fullName>
    <inlineHelpText>Date of issuance of license.</inlineHelpText>
    <label>Provisional License Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Type__c</fullName>
    <inlineHelpText>Type of license issued</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
                <default>true</default>
                <label>Provisional</label>
            </value>
            <value>
                <fullName>Continuous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Org_Wide_Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Org_Wide_Email_Addresses__c</fullName>
    <description>This field includes email addresses for all persons connected to this Organization though a Role. The Role Trigger updates this field, so it can be used to send out emails to all recipients.</description>
    <label>Org Wide Email Addresses</label>
    <length>1300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <label>Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Pre_School.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Pre_School</fullName>
    <active>true</active>
    <description>ODE - PS (Pre-School)</description>
    <label>Pre School</label>
</RecordType>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JFS</fullName>
            </value>
            <value>
                <fullName>ODE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/recordTypes/Portal_Roles.recordType-meta.xml
<RecordType>
    <fullName>Portal_Roles</fullName>
    <active>true</active>
    <description>This record type is used to create Portal Roles</description>
    <label>Portal Roles</label>
</RecordType>

force-app/main/default/classes/CLQ_GlobalWebservice3Test.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_GlobalWebservice3Test
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/

@isTest(isparallel = true)
private class CLQ_GlobalWebservice3Test {
    @testSetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    @IsTest
    static void myUnitTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Pre School');
            if(Schema.SObjectType.CLQ_OCLQS_Configuration__c.isAccessible()){
                insert configRecord; 
            }
            
            CLQ_County__c county = new CLQ_County__c(Name = 'Clinton', CCC_Field_Officers__c = 'Columbus', Area_Region__c='C', FCC_Field_officers__c = 'Akron' );
            if(Schema.SObjectType.CLQ_County__c.isAccessible()){
                insert county;
            }
            county = new CLQ_County__c(Name = 'Clark', CCC_Field_Officers__c = 'Dayton', Area_Region__c='NW', FCC_Field_officers__c = 'Toledo' );
            if(Schema.SObjectType.CLQ_County__c.isAccessible()){
                insert county;
            }
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            if(Schema.SObjectType.Account.isAccessible()){
                insert accountrecord ;
            }
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Pre_School').getRecordTypeId();
            programRecord.CLQ_Program_Status__c = 'New';
            programRecord.CLQ_License_Type__c = 'Continuous';
            programRecord.CLQ_License_Registration_Status__c = 'Licensed';
            
            programRecord.CLQ_County__c = county.id;
            programRecord.CLQ_License_Issue_Date__c = system.Date.today();
            
            programRecord.CLQ_Org_Wide_Email_Addresses__c = 'test@test.com';
            if(Schema.SObjectType.CLQ_Program__c.isAccessible()){
                insert programRecord ;
            }
            
            CLQ_Corrective_Action_Plan__c capTest = new CLQ_Corrective_Action_Plan__c();
            capTest.CLQ_Program__c = programRecord.id;
            if(Schema.SObjectType.CLQ_Corrective_Action_Plan__c.isAccessible()){
                insert capTest;
            }
            
            
            contact c = new contact();
            c.lastname = 'tester';
            c.email = 'tester@tester.com';
            if(Schema.SObjectType.contact.isAccessible()){
                insert c;
            }
            list<string> parms = new list<string>();
            CLQ_Role__c role1 = new CLQ_Role__c();
            role1.CLQ_Contact__c = c.id;
            role1.Role_Type__c = 'ODE';
            role1.Portal_Roles__c = 'OCLQSAdministrator';
            role1.CLQ_Program__c = programRecord.id;
            role1.Secondary_Role__c = 'OCLQSPS';
            role1.recordtypeid = Schema.SObjectType.CLQ_Role__c .getRecordTypeInfosByDeveloperName().get('Portal_Roles').getRecordTypeId();
            if(Schema.SObjectType.CLQ_Role__c.isAccessible()){
                insert role1;
            }
            parms.add('CLQ_ODE_CAP_Overdue_Email_Template' + '|' + capTest.id);
            
            Test.startTest();
            CLQ_GlobalWebService3.sendCAPEmail(parms);
            Test.StopTest();  
            
        }
    }
}