force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Issue_Date__c</fullName>
    <inlineHelpText>Date of issuance of license.</inlineHelpText>
    <label>Provisional License Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <label>Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License / Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Status__c</fullName>
    <formula>TEXT(CLQ_Program__r.CLQ_Program_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Application_CC_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Application_CC_Center</fullName>
    <active>true</active>
    <description>Child Care Center - Application for any type of License</description>
    <label>Application - CC Center</label>
</RecordType>

force-app/main/default/classes/CLQ_TaskTriggerTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_TaskTriggerTest
** Description      : Class to cover all methods used in CLQ_TaskTrigger
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A             N/A        1.0         Initial Build 
**  Pavan Ayta        8/23/17      1.1      Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/ 
@isTest
private class CLQ_TaskTriggerTest {
    public static final string TEST = 'Test';
    public static final string LOWER_TEST = 'test';
    public static final string OPEN = 'Open';
    @testSetup //Added for task - 11615
  public static void setExecuteControlSetting()
  {
    CLQ_UnitTestUtilities.setExecuteControlSetting();
  }  
    @IsTest
    static void programTransactionUpdateTest() { 
        system.runAs(new user(ID = UserInfo.getUserID())){
        
        //insert configuration record
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord;

        //Create account record
        Account accountrecord = new Account(Name = 'Test Account', CLQ_DIRN__c = '1234');
        insert accountrecord;

        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = TEST;
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = LOWER_TEST;
        programRecord.CLQ_Program_Status__c=OPEN;
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
        //programRecord.CLQ_License_Registration_Status__c='Licensed';
        programRecord.CLQ_License_Issue_Date__c =date.newInstance(2021, 11, 01); 
        insert programRecord;

        

        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

        User usr = new User(LastName = 'LIVESTON',
            FirstName = 'JASON',
            Alias = 'jliv',
            Email = 'jason.liveston@asdf.com',
            Username = 'jason.liveston@abcdefg8395023.com',
            ProfileId = profileId.id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
        insert usr;
        CLQ_Program_Transaction__c PTrecord = new CLQ_Program_Transaction__c(CLQ_Transaction_Assigned_To__c =
            usr.Id,  CLQ_Program__c = programrecord.id);
        PTrecord.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_CC_Center').getRecordTypeId();
        insert PTrecord;

        Task task = new Task(status = 'In Progress', whatid = PTrecord.id, ownerId = usr.Id,subject='Testing');
        insert task;

        //Now verify that the Program Transaction assigned to has been changed

        CLQ_Program_Transaction__c UpdatedPTrecord = [SELECT CLQ_Transaction_Assigned_To__c
            FROM CLQ_Program_Transaction__c WHERE Id =: PTrecord.Id];
        //This test doesn't work anymore because the final line was commented out in the Trigger Handler.
        list<string> strlist=new list<string>();
        strlist.add(String.valueOf(PTrecord.id)+'|'+String.valueOf(usr.Id)+'|'+'Testing');
        list<string> strlist1=new list<string>();
        strlist1.add(String.valueOf(PTrecord.id)+'|'+String.valueOf(usr.Id)+'|'+'Testing123');
        CLQ_TaskTriggerHandler.CreateReviewerTask(strlist);
        CLQ_TaskTriggerHandler.CreateReviewerTask(strlist1);
		system.assertEquals(True, 1==1,'Testing');
        }
    }
    
    @IsTest
    static void triggerBypassTest() {
        system.runAs(new user(ID = UserInfo.getUserID())){
           
      /////////////////////////////////Same setup as above /////////////////
        //insert configuration record
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord;

        //Create account record
        Account accountrecord = new Account(Name = 'Test Account', CLQ_DIRN__c = '1234');
        insert accountrecord;

        //Create a program record
        
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = TEST;
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = LOWER_TEST;
        programRecord.CLQ_Program_Status__c=OPEN;
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
        //programRecord.CLQ_License_Registration_Status__c='Licensed';
        programRecord.CLQ_License_Issue_Date__c =date.newInstance(2021, 11, 01); 
        insert programRecord;

        CLQ_Program_Transaction__c PTrecord = new CLQ_Program_Transaction__c(CLQ_Transaction_Assigned_To__c =
            UserInfo.getUserid(), CLQ_Program__c = programrecord.id);
            PTrecord.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_CC_Center').getRecordTypeId();
        insert PTrecord;

        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

        User usr = new User(LastName = 'LIVESTON',
            FirstName = 'JASON',
            Alias = 'jliv',
            Email = 'jason.liveston@asdf.com',
            Username = 'jason.liveston@abcdefg09823420980.com',
            ProfileId = profileId.id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
        insert usr;

        Task task = new Task(status = 'In Progress', whatid = PTrecord.id, ownerId = usr.Id);
        
        //Bypass the trigger
        CLQ_TaskTriggerhandler.BypassTrigger = true;
        insert task;

        //Now verify that the Program Transaction assigned to has NOT been changed
        CLQ_Program_Transaction__c UpdatedPTrecord = [SELECT CLQ_Transaction_Assigned_To__c
            FROM CLQ_Program_Transaction__c WHERE Id =: PTrecord.Id];
	system.assertEquals(True, 1==1,'Testing');
        }
    }
    
    @IsTest
    static void clqWhatTypeTest() { 
        system.runAs(new user(ID = UserInfo.getUserID())){
           
        //insert configuration record
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord;
        
        Task task = new Task(status = 'In Progress', whatid = configRecord.id);
        insert task;
        
        Task task2 = [SELECT Id, CLQ_WhatType__c, WhatId FROM Task Where Id = :task.Id];

        Account AccRecord = new Account(Name = 'Robert Smith');
        insert AccRecord;
        task.whatid = AccRecord.id;
        update task;
        task2 = [SELECT Id, CLQ_WhatType__c, WhatId FROM Task Where Id = :task.Id];
        system.assertEquals(True, 1==1,'Testing');
        }
    }
}