force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <formula>CLQ_Street_Address_1_at_Site__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License / Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/Rating_Estimated_By_System__c.field-meta.xml
<CustomField>
    <fullName>Rating_Estimated_By_System__c</fullName>
    <label>Rating Estimated By System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/Ongoing_Quality_Rating_Registration.recordType-meta.xml
<RecordType>
    <fullName>Ongoing_Quality_Rating_Registration</fullName>
    <active>true</active>
    <description>This record type will be used for ongoing quality rating transactions except annual reports</description>
    <label>SUTQ - Ongoing Registration</label>
</RecordType>

force-app/main/default/classes/CLQ_UserTriggerHandlerTest.cls
/*************************************************************************************************************
** Name            : CLQ_UserTriggerHandlerTest  
** Description     : Test Class for CLQ_UserTriggerHandler
** Version         : 1.0
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**	Developer						Date					Version		Description
**------------------------------------------------------------------------------------------------------------
**	Neetu Ojha						Sep 25, 2017			1.0			Initial Version                 
**************************************************************************************************************/ 
@isTest
private class CLQ_UserTriggerHandlerTest {
    
    @testSetup
    public static void setExecuteControlSetting(){
        CLQ_UnitTestUtilities.setExecuteControlSetting();
        User usr =[select id, UserRoleId, ProfileId, IsActive from User where UserRoleId !=null and ProfileId !=null and IsActive =true limit 1];
        
        
        
        
        //Create account record
        List<Account> lstAccount = new List<Account>();
        lstAccount.add(new Account(Name='Test Account1',CLQ_DIRN__c = '1234',OwnerId= usr.Id)); 
        lstAccount.add(new Account(Name='Test Account2',CLQ_DIRN__c = '1234',OwnerId= usr.Id)); 
        insert lstAccount ;
        
        //Insert contact
        List<Contact> lstContact = new List<Contact>();
        lstContact.add(new Contact(FirstName='Test', lastName = 'Contact1',AccountId = lstAccount[0].id));
        lstContact.add(new Contact(FirstName='Test', lastName = 'Contact2',AccountId = lstAccount[1].id));
        insert lstContact;
    }
    
    @IsTest
    static void newUserUnitTest(){  
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            List<Contact> lstContact = [Select Id from Contact where FirstName='Test'];  
            List<User> lstUser = new List<User>();
            //Create a new user
            
            List<Profile> lstProfile = [SELECT Id FROM Profile WHERE Name IN ('OCLQS Customer Community Plus Login User','OCLQS Customer Community Login User') order by Name];
            lstUser.add(new User(LastName = 'Pierce', FirstName = 'Ben', Alias = 'bpie', Email = 'ben.pierce@test.com',
                                 Username = 'ben.pierce@ygmail.com',ProfileId = lstProfile[0].id, ContactId=lstContact[0].Id,
                                 TimeZoneSidKey = 'GMT', LanguageLocaleKey = 'en_US', EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US',
                                 IsActive  = true, CommunityNickname = 'testbenpierce'));      
            
            
            
            
            Test.startTest();
            insert lstUser; 
            Test.stopTest(); 
        }
        
    }    
    
    @IsTest
    static void updateUserUnitTest() {
        system.assertEquals(True, 1==1,'Testing');
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
        List<Contact> lstContact = [Select Id from Contact where FirstName='Test']; 
        Account accountrecord = new Account(Name='Test Account', CLQ_DIRN__C = '1234');
        insert accountrecord;
        List<User> lstUser=new List<User>();
        
         List<Profile> lstProfile = [SELECT Id FROM Profile WHERE Name IN ('OCLQS Customer Community Plus Login User','OCLQS Customer Community Login User') order by Name];
         lstUser.add(new User(LastName = 'Pierce', FirstName = 'Ben', Alias = 'bpie', Email = 'ben.pierce@test.com',
                                 Username = 'ben.pierce@ygmail.com',ProfileId = lstProfile[0].id,ContactId=lstContact[0].Id,
                                 TimeZoneSidKey = 'GMT', LanguageLocaleKey = 'en_US', EmailEncodingKey = 'UTF-8', LocaleSidKey = 'en_US',
                                 IsActive  = true, CommunityNickname = 'testbenpierce'));     
        insert lstUser; 
        //List<User> lstUser = [Select Id,isActive,ManagerId from User where Profile.Name = 'OCLQS Customer Community Plus Login User' limit 1];
        //List<User> lstUser = [Select Id,isActive,ManagerId from User where Profile.Name = 'Customer Community Login VDSS' limit 1];
        lstUser[0].isActive=false;
        List<User> lstUser1=[Select Id,isActive,Manager.IsActive,ManagerId from User where ManagerId !=null and ( Profile.name like '%Admin%') and manager.isactive =true and IsActive =true limit 1];
        lstUser[0].isActive=false;
        lstUser[0].ManagerId=lstUser1[0].Id;
        
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
        programRecord.CLQ_License_Registration_Status__c = 'Exempt';
        programRecord.OwnerId= lstUser[0].Id;
        insert programRecord;
        
        CLQ_Program_Transaction__c programTransaction = new CLQ_Program_Transaction__c();
        programTransaction.CLQ_Program__c = programRecord.Id;
        programTransaction.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
        programTransaction.Rating_Estimated_By_System__c = '2';
        programTransaction.CLQ_Transaction_Status__c = 'Not Complete';
        programTransaction.OwnerId=lstUser[0].Id;
        Insert programTransaction;
        
        CLQ_Inspection__c inspection = new CLQ_Inspection__c();
        inspection.Inspection_Status__c = 'Not Complete';
        inspection.CLQ_Inspection_Status__c = 'Pending Processing';
        inspection.CLQ_Program_Transaction__c = ProgramTransaction.Id;
        inspection.CLQ_Program__c = programRecord.id;
        inspection.OwnerId=lstUser[0].Id;
        Insert inspection;
        
        Profile p1 = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        
        
        system.runAs(lstUser1[0]){
            Test.startTest();
            CLQ_UserTriggerHandler.BypassTrigger=null;
            update lstUser[0];
        }
        
        Test.stopTest(); 
    }       
}