force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Owner__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InspectionOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Last_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Last_Visit_Date__c</fullName>
    <description>The date stamp when we complete the visit. Initially it is being used in CAP</description>
    <label>Last Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <formula>CLQ_Street_Address_1_at_Site__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Visit_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Visit_Status__c</fullName>
    <label>Visit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Scheduled</fullName>
                <default>true</default>
                <label>To be Scheduled</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Visit Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Licensing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Licensing_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensing Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Child_Care_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Child_Care_Center</fullName>
    <active>true</active>
    <description>VDSS - Child Care Centers</description>
    <label>Child Care Center</label>
</RecordType>

force-app/main/default/classes/CLQ_CompleteVisitModeExtnTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_CompleteVisitModeExtnTest
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A	            1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest
public class CLQ_CompleteVisitModeExtnTest {
	@testSetup //Added method for Task - 11615
	public static void setExecuteControlSetting()
	{
	CLQ_UnitTestUtilities.setExecuteControlSetting();
	} 	
    @IsTest
    static void completeVisitModeTest(){
        User currUser = [Select id, Profile.Name from User where Id =: UserInfo.getUserId()];
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
        insert configRecord; 
        
        //Create account record
        Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
        insert accountrecord ;
              		
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Admin Read-Only' LIMIT 1];               
        User usr = new User(LastName = 'Hugh',
            FirstName = 'Jack',
            Alias = 'jHugh',
            Email = 'jack@hugh.com',
            Username = 'jack@hugh.com',
            ProfileId = profileId.id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
        insert usr;       
		          
        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Child_Care_Center').getRecordTypeId();
        programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserid();
        insert programRecord ;        
        
        CLQ_Inspection__c inspnRecord = new CLQ_Inspection__c();
        CLQ_Inspection__c inspectionrecord2 = CLQ_UtilityClass.createInspectionrecord('Complaint', 'Partial', 'Pending Processing');
        inspnRecord.CLQ_Program__c = programRecord.id;
        inspnRecord.CLQ_Inspection_Owner__c = currUser.Id;
        inspnRecord.OwnerId = currUser.Id;
        inspnRecord.CLQ_Visit_Status__c = 'Visit Completed';
        inspnRecord.CLQ_Last_Visit_Date__c = Date.today();
        Insert inspnRecord;
        
        CLQ_Inspection__c inspnRecord2 = new CLQ_Inspection__c();
        inspnRecord2.CLQ_Program__c = programRecord.id;
        inspnRecord2.CLQ_Inspection_Owner__c = currUser.Id;
        inspnRecord2.OwnerId = currUser.Id;
        inspnRecord2.CLQ_Visit_Status__c = 'Visit Completed';
        inspnRecord2.CLQ_Last_Visit_Date__c = Date.today();
        inspnRecord2.CLQ_Inspection_Status__c = 'Approved';     
        Insert inspnRecord2;
                   
        CLQ_Inspection__c insp = [Select id,CLQ_Inspection_Owner__c,CLQ_Visit_Status__c,CLQ_Last_Visit_Date__c from CLQ_Inspection__c where Id =: inspnRecord.Id];
        System.debug('Inspection Owner - '+insp.CLQ_Inspection_Owner__c+' . Inspection Visit Status - '+insp.CLQ_Visit_Status__c);
        CLQ_Inspection__c insp2 = [Select id,CLQ_Inspection_Owner__c,CLQ_Visit_Status__c,CLQ_Last_Visit_Date__c from CLQ_Inspection__c where Id =: inspnRecord2.Id];
        System.debug('Inspection Owner - '+insp2.CLQ_Inspection_Owner__c+' . Inspection Visit Status - '+insp2.CLQ_Visit_Status__c);
        
        List<String> fieldlist = new List<String>();
        fieldlist.add('CLQ_Visit_Status__c');
        fieldlist.add('CLQ_Last_Visit_Date__c');
       
        PageReference pageRef = Page.CLQ_CompleteVisitMode;
         pageRef.getParameters().put('id',inspnRecord.id);
          Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(inspnRecord);
        CLQ_CompleteVisitModeExtn ic = new CLQ_CompleteVisitModeExtn(sc);            
        system.AssertNotEquals(null,inspnRecord.CLQ_Inspection_Owner__c,'Testing');
        ic.inspectionRecord = Database.query(CLQ_UtilityClass.createSOQLQuery('CLQ_Inspection__c',' id=\''+inspnRecord.id+'\'', null));
        ic.onLoad();
        ic.onOK();
       PageReference pageRef2 = Page.CLQ_CompleteVisitMode;
         pageRef.getParameters().put('id',inspnRecord2.id);
          Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc2 = new ApexPages.StandardController(inspnRecord2);
        CLQ_CompleteVisitModeExtn ic2 = new CLQ_CompleteVisitModeExtn(sc2);            
        system.AssertNotEquals(null,inspnRecord2.CLQ_Inspection_Owner__c,'Testing');
        ic2.inspectionRecord = Database.query(CLQ_UtilityClass.createSOQLQuery('CLQ_Inspection__c',' id=\''+inspnRecord2.id+'\'', null));
        ic2.onLoad();
        ic2.onOK();
        system.assertNotEquals(True, 1==2,'Testing');
    }
}