force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/fields/CLQ_Change_of_Location_Fee__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Change_of_Location_Fee__c</fullName>
    <label>Change of Location Fee</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>Type of programs</description>
    <label>Program Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Child Care Center</fullName>
            </value>
            <value>
                <fullName>Out Of State</fullName>
            </value>
            <value>
                <fullName>Day Camp</fullName>
            </value>
            <value>
                <fullName>FCC - Type A Home</fullName>
            </value>
            <value>
                <fullName>FCC - Type B Home</fullName>
            </value>
            <value>
                <fullName>In-Home Aide</fullName>
            </value>
            <value>
                <fullName>Out of State Registration</fullName>
            </value>
            <value>
                <fullName>Pre School</fullName>
            </value>
            <value>
                <fullName>School Age Child Care</fullName>
            </value>
            <value>
                <fullName>CC Center</fullName>
                <isActive>false</isActive>
                <label>CC Center</label>
            </value>
            <value>
                <fullName>FCC Type A</fullName>
                <isActive>false</isActive>
                <label>FCC Type A</label>
            </value>
            <value>
                <fullName>FCC Type B</fullName>
                <isActive>false</isActive>
                <label>FCC Type B</label>
            </value>
            <value>
                <fullName>In Home Aide</fullName>
                <isActive>false</isActive>
                <label>In Home Aide</label>
            </value>
            <value>
                <fullName>ODE - Pre School</fullName>
                <isActive>false</isActive>
                <label>ODE - Pre School</label>
            </value>
            <value>
                <fullName>ODE - SACC</fullName>
                <isActive>false</isActive>
                <label>ODE - SACC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/classes/CLQ_TriggerTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_TriggerTest
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isParallel=true)
private class CLQ_TriggerTest 
{
    @testSetup //Added for task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    } 
    @IsTest
    static void constructorTest() 
    { 
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ;
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert programRecord ;
            
            list<CLQ_Program__c>  OldList = new list<CLQ_Program__c>{programRecord};
                list<CLQ_Program__c>  NewList = new list<CLQ_Program__c>{programRecord};
                    
                    //Before Insert
                    CLQ_Trigger trig = new CLQ_Trigger(NewList, null, OldList, null,
                                                       true, true, false, false, 
                                                       true, false, false, 1);
            //system.AssertEquals('BeforeInsert', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger(); 
            
            //After Insert
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, true, false, false, 
                                   false, true, false, 1);
            //system.AssertEquals('AfterInsert', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //Before Update
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, false, true, false, 
                                   true, false, false, 1);
            //system.AssertEquals('BeforeUpdate', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //After Update
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, false, true, false, 
                                   false, true, false, 1);
            //system.AssertEquals('AfterUpdate', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //Before Delete
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, false, false, true, 
                                   true, false, false, 1);
            //system.AssertEquals('BeforeDelete', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //After Delete
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, false, false, true, 
                                   false, true, false, 1);
            //system.AssertEquals('AfterDelete', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //Before UnDelete
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, false, false, false, 
                                   true, false, true, 1);
            //system.AssertEquals('BeforeUndelete', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //After UnDelete
            trig = new CLQ_Trigger(NewList, null, OldList, null,
                                   true, false, false, false, 
                                   false, true, true, 1);
            //system.AssertEquals('AfterUndelete', trig.TriggerExecutionType,'Testing');
            trig.ProcessTrigger();
            
            //Bypass Trigger
            CLQ_Trigger.BypassAllTriggers = true;
            trig.ProcessTrigger();
            CLQ_Trigger.BypassAllTriggers = false;
            
            CLQ_ProgramTriggerHandler trig2 = new CLQ_ProgramTriggerHandler(NewList, null, OldList, null,
                                                                            true, true, false, false, 
                                                                            true, false, false, 1);
            CLQ_Program_TransactionTriggerHandler.BypassTrigger = true; 
            trig2.ProcessTrigger();
        }
    }
    
    @IsTest
    static void makeVersionBackupTest() 
    {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home', CLQ_Change_of_Location_Fee__c = 12.5, Program_Type__c = 'Child Care Center');
            insert configRecord;
            map<Id,CLQ_OCLQS_Configuration__c> OldMap = new  map<Id,CLQ_OCLQS_Configuration__c>();
            OldMap.put(configRecord.id, configRecord);
            
            CLQ_OCLQS_Configuration__c NewChangedConfigRecord = configRecord.Clone(true,true,true,true);
            NewChangedConfigRecord.CLQ_Change_of_Location_Fee__c = 44;
            NewChangedConfigRecord.Program_Type__c = 'FCC Type B';
            
            CLQ_OCLQS_Configuration__c configRecordClone = (CLQ_OCLQS_Configuration__c)CLQ_Trigger.MakeVersionBackup(NewChangedConfigRecord.Id, OldMap);
            
            system.AssertEquals(null, configRecordClone.Id,'Testing');
            system.AssertNotEquals(NewChangedConfigRecord.Id, configRecordClone.Id,'Testing');
            system.AssertNotEquals(NewChangedConfigRecord.CLQ_Change_of_Location_Fee__c, configRecordClone.CLQ_Change_of_Location_Fee__c,'Testing');
            system.AssertNotEquals(NewChangedConfigRecord.Program_Type__c, configRecordClone.Program_Type__c,'Testing');
            
            system.AssertNotEquals(configRecord.Id, configRecordClone.Id,'Testing');
            system.AssertEquals(configRecord.CLQ_Change_of_Location_Fee__c, configRecordClone.CLQ_Change_of_Location_Fee__c,'Testing');
            system.AssertEquals(configRecord.Program_Type__c, configRecordClone.Program_Type__c,'Testing');
        } 
    }
}