force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/Approved_Total_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Approved_Total_Capacity__c</fullName>
    <description>Approved Total Capacity for TFS 11180</description>
    <label>Recommended Total Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Approved_Total_Capacity_Under_2_1_2__c.field-meta.xml
<CustomField>
    <fullName>Approved_Total_Capacity_Under_2_1_2__c</fullName>
    <description>Field getting updated from Max. Number of Children Under 2 1/2 from Room Space Inspection</description>
    <label>Recommended Total Capacity Under 2 1/2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Calculated_Max_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Max_Capacity__c</fullName>
    <description>Field created for Bug 11180</description>
    <label>Calculated Max Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Owner__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InspectionOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Notice__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Notice__c</fullName>
    <label>Notice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unannounced</fullName>
                <default>true</default>
                <label>Unannounced</label>
            </value>
            <value>
                <fullName>Announced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <formula>CLQ_Street_Address_1_at_Site__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Max_Capacity_Under_2_1_2_Years__c.field-meta.xml
<CustomField>
    <fullName>Max_Capacity_Under_2_1_2_Years__c</fullName>
    <label>Max Capacity Under 2 1/2 Years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Licensing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Licensing_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensing Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Child_Care_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Child_Care_Center</fullName>
    <active>true</active>
    <description>VDSS - Child Care Centers</description>
    <label>Child Care Center</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_ProgTrans_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>CLQ_ProgTrans_Street_Address__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Application_CC_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Application_CC_Center</fullName>
    <active>true</active>
    <description>Child Care Center - Application for any type of License</description>
    <label>Application - CC Center</label>
</RecordType>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/CLQ_Room_Space_Inspection__c.object-meta.xml
<CustomObject>
    <description>Junction object between Room/Space and Inspection</description>
    <label>Room/Space Inspection</label>
    <nameField>
        <label>Room/Space Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Space Inspection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Rooms/Space Inspection</relationshipLabel>
    <relationshipName>Rooms_Space_Inspection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Rooms_Spaces_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <formula>CLQ_Program__r.CLQ_Street_Address_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Street Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/recordTypes/CLQ_Indoor_Room_Space.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Indoor_Room_Space</fullName>
    <active>true</active>
    <label>Indoor Room/Space</label>
</RecordType>

force-app/main/default/classes/CLQ_RoomSpaceInspectionTrgHndlrTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_RoomSpaceInspectionTrgHndlrTest
** Description      : Test Class for CLQ_RoomSpaceInspectionTriggerHandler
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isparallel = true)
public class CLQ_RoomSpaceInspectionTrgHndlrTest {
    @testSetup //Added for task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    @IsTest
    static void updateRoomSpaceOnInspectionTest(){
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
            insert configRecord; 
            
            
            //Create Account Record
            Account accountrecord = new Account(Name='Test123 Account',CLQ_DIRN__c = '3347'); 
            insert accountrecord ;
            //Create Program Record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test Program Name';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'Test Address';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Child_Care_Center').getRecordTypeId();
            programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserID();
            insert programRecord ;
            
            //Create Program Transaction Record
            CLQ_Program_Transaction__c progTransA = new CLQ_Program_Transaction__c();
            progTransA.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_CC_Center').getRecordTypeId();
            progTransA.CLQ_Program__c = programRecord.Id;
            progTransA.CLQ_ProgTrans_Street_Address__c ='Test Street Address';
            progTransA.CLQ_Transaction_Status__c = 'Not Submitted';
            progTransA.CLQ_Transaction_Assigned_To__c = UserInfo.getUserId();
            Insert progTransA;  
            
            
            
            //Insert CLQ_Inspection__c 
            CLQ_Inspection__c inspectionrecord = CLQ_UtilityClass.createInspectionrecord('Pre-license', 'Full', 'Pending Processing');
            inspectionrecord.CLQ_Program__c = programRecord.id;
            inspectionrecord.CLQ_Inspection_Owner__c = UserInfo.getUserId();
            inspectionrecord.Calculated_Max_Capacity__c = 10;
            inspectionrecord.Approved_Total_Capacity_Under_2_1_2__c = 10;
            inspectionrecord.Approved_Total_Capacity__c = 5;
            inspectionrecord.Max_Capacity_Under_2_1_2_Years__c = 30;
            inspectionrecord.CLQ_Notice__c ='Unannounced';
            inspectionrecord.CLQ_Inspection_Type__c ='Annual';
            inspectionrecord.CLQ_Scope__c='Full';
            inspectionrecord.CLQ_Use_Rules_Effective_On__c = System.today();
            inspectionrecord.CLQ_Method__c ='On-site Inspection';
            
            insert inspectionrecord;
            
            inspectionrecord.Calculated_Max_Capacity__c = 11;
            inspectionrecord.Approved_Total_Capacity_Under_2_1_2__c = 3;
            inspectionrecord.Approved_Total_Capacity__c = 5;
            inspectionrecord.Max_Capacity_Under_2_1_2_Years__c = 12;
            update inspectionrecord;
            
            //Insert List for CLQ_Room_Space_Inspection__c
            list<CLQ_Room_Space_Inspection__c> rsiInsert = new list<CLQ_Room_Space_Inspection__c>();
            
            CLQ_Room_Space_Inspection__c rsiRecord1 = new CLQ_Room_Space_Inspection__c();
            rsiRecord1.Name = 'Room2';
            rsiRecord1.CLQ_Room_Space_Number__c = '1234';
            rsiRecord1.recordTypeid = Schema.SObjectType.CLQ_Room_Space_Inspection__c.getRecordTypeInfosByDeveloperName().get('CLQ_Indoor_Room_Space').getRecordTypeId();
            rsiRecord1.CLQ_Room_Space_Shape__c = 'Square/Rectangle/L-Shaped';
            rsiRecord1.CLQ_Length_Feet__c = 100;
            rsiRecord1.CLQ_Width_Feet__c = 90;
            rsiRecord1.CLQ_Room_Space_Type__c = 'Primary Space';
            rsiRecord1.CLQ_Approved_Room_Space__c = true;
            rsiRecord1.CLQ_Used_by_Under_or_Over_2_1_2__c = 'Under';
            rsiRecord1.CLQ_Approved_for_under_2_1_2__c = 'No';
            rsiRecord1.CLQ_Currently_In_Use__c = 'Yes'; 
            rsiRecord1.CLQ_Inspection__c= inspectionrecord.Id;
            rsiRecord1.CLQ_Observation_Complete__c ='Yes';
            rsiRecord1.CLQ_Number_of_Children_Allowed__c = 4;
            rsiInsert.add(rsiRecord1);
            
            CLQ_Room_Space_Inspection__c rsiRecord2 = new CLQ_Room_Space_Inspection__c();
            rsiRecord2.Name = 'Room2';
            rsiRecord2.CLQ_Room_Space_Number__c = '4321';
            rsiRecord2.recordTypeid = Schema.SObjectType.CLQ_Room_Space_Inspection__c.getRecordTypeInfosByDeveloperName().get('CLQ_Indoor_Room_Space').getRecordTypeId();
            rsiRecord2.CLQ_Room_Space_Shape__c = 'Square/Rectangle/L-Shaped';
            rsiRecord2.CLQ_Length_Feet__c = 90;
            rsiRecord2.CLQ_Width_Feet__c = 100;
            rsiRecord2.CLQ_Room_Space_Type__c = 'Primary Space';
            rsiRecord2.CLQ_Approved_Room_Space__c = true;
            rsiRecord2.CLQ_Used_by_Under_or_Over_2_1_2__c = 'Under';
            rsiRecord2.CLQ_Approved_for_under_2_1_2__c = 'Yes';
            rsiRecord2.CLQ_Currently_In_Use__c = 'Yes';
            rsiRecord2.CLQ_Inspection__c= inspectionrecord.Id;
            rsiRecord2.CLQ_Observation_Complete__c ='Yes';
            rsiRecord2.CLQ_Number_of_Children_Allowed__c = 3;
            rsiInsert.add(rsiRecord2);
            
            CLQ_Room_Space_Inspection__c rsiRecord3 = new CLQ_Room_Space_Inspection__c();
            rsiRecord3.Name = 'Room3';
            rsiRecord3.CLQ_Room_Space_Number__c = '2472';
            rsiRecord3.recordTypeid = Schema.SObjectType.CLQ_Room_Space_Inspection__c.getRecordTypeInfosByDeveloperName().get('CLQ_Indoor_Room_Space').getRecordTypeId();
            rsiRecord3.CLQ_Room_Space_Shape__c = 'Square/Rectangle/L-Shaped';
            rsiRecord3.CLQ_Length_Feet__c = 120;
            rsiRecord3.CLQ_Width_Feet__c = 100;
            rsiRecord3.CLQ_Room_Space_Type__c = 'Primary Space';
            rsiRecord3.CLQ_Approved_Room_Space__c = true;
            rsiRecord3.CLQ_Used_by_Under_or_Over_2_1_2__c = 'Both';
            rsiRecord3.CLQ_Approved_for_under_2_1_2__c = 'Yes';
            rsiRecord3.CLQ_Currently_In_Use__c = 'Yes';
            rsiRecord3.CLQ_Inspection__c= inspectionrecord.Id;
            rsiRecord3.CLQ_Observation_Complete__c ='Yes';
            rsiRecord3.CLQ_Number_of_Children_Allowed__c = 5;
            rsiInsert.add(rsiRecord3);
            
            CLQ_Room_Space_Inspection__c rsiRecord4 = new CLQ_Room_Space_Inspection__c();
            rsiRecord4.Name = 'Room4';
            rsiRecord4.CLQ_Room_Space_Number__c = '3284';
            rsiRecord4.recordTypeid = Schema.SObjectType.CLQ_Room_Space_Inspection__c.getRecordTypeInfosByDeveloperName().get('CLQ_Indoor_Room_Space').getRecordTypeId();
            rsiRecord4.CLQ_Room_Space_Shape__c = 'Square/Rectangle/L-Shaped';
            rsiRecord4.CLQ_Length_Feet__c = 120;
            rsiRecord4.CLQ_Width_Feet__c = 110;
            rsiRecord4.CLQ_Room_Space_Type__c = 'Primary Space';
            rsiRecord4.CLQ_Approved_Room_Space__c = true;
            rsiRecord4.CLQ_Used_by_Under_or_Over_2_1_2__c = 'Both';
            rsiRecord4.CLQ_Approved_for_under_2_1_2__c = 'No';
            rsiRecord4.CLQ_Currently_In_Use__c = 'Yes';
            rsiRecord4.CLQ_Inspection__c= inspectionrecord.Id;
            rsiRecord4.CLQ_Observation_Complete__c ='Yes';
            rsiRecord4.CLQ_Number_of_Children_Allowed__c = 5;
            rsiInsert.add(rsiRecord4);
            
            
            insert rsiInsert;
            
            update rsiRecord1;
            
            
            CLQ_Room_Space_Inspection__c oldRecord = rsiRecord1.clone(true,true,true,true);
            
            
            list<CLQ_Room_Space_Inspection__c> newList = new list<CLQ_Room_Space_Inspection__c>{rsiRecord1};
                list<CLQ_Room_Space_Inspection__c> oldList = new list<CLQ_Room_Space_Inspection__c>{oldRecord};
                    map<id,CLQ_Room_Space_Inspection__c> newMap = new map<id,CLQ_Room_Space_Inspection__c>{rsiRecord1.Id => rsiRecord1};
                        map<id,CLQ_Room_Space_Inspection__c> oldMap = new map<id,CLQ_Room_Space_Inspection__c>{oldRecord.Id => oldRecord};
                            CLQ_RoomSpaceInspectionTriggerHandler rsi = new CLQ_RoomSpaceInspectionTriggerHandler(newList,newMap,oldList,oldMap,
                                                                                                                  true,false,true,false,
                                                                                                                  true,false,false,1);
            
            rsi.roomSpaceChildrenUpdate(newList , false);
            
            
        }
    }
}