force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Issue_Date__c</fullName>
    <inlineHelpText>Date of issuance of license.</inlineHelpText>
    <label>Provisional License Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Type__c</fullName>
    <inlineHelpText>Type of license issued</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
                <default>true</default>
                <label>Provisional</label>
            </value>
            <value>
                <fullName>Continuous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Org_Wide_Email_Addresses_SUTQ__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Org_Wide_Email_Addresses_SUTQ__c</fullName>
    <label>Org Wide Email Addresses SUTQ</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Day_Camp.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Day_Camp</fullName>
    <active>true</active>
    <description>Non Licensed - Day Camp</description>
    <label>Day Camp</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Pre_School.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Pre_School</fullName>
    <active>true</active>
    <description>ODE - PS (Pre-School)</description>
    <label>Pre School</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License / Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/Application_Day_Camp.recordType-meta.xml
<RecordType>
    <fullName>Application_Day_Camp</fullName>
    <active>true</active>
    <description>Day Camp Application for any Registered Day Camp</description>
    <label>Application - Day Camp</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Amendment_Change_of_Administrator.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Amendment_Change_of_Administrator</fullName>
    <active>true</active>
    <description>Used for Change of Administrator</description>
    <label>Amendment - Change of Administrator</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Amendment_Change_of_Capacity_Space.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Amendment_Change_of_Capacity_Space</fullName>
    <active>true</active>
    <description>Used for Change of Capacity or Space for FCC</description>
    <label>Amendment- FCC - Change of Capacity / Space</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Amendment_FCC_Change_of_Location.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Amendment_FCC_Change_of_Location</fullName>
    <active>true</active>
    <label>Amendment - FCC - Change of Location</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Application_CC_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Application_CC_Center</fullName>
    <active>true</active>
    <description>Child Care Center - Application for any type of License</description>
    <label>Application - CC Center</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Application_ODE_Program.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Application_ODE_Program</fullName>
    <active>true</active>
    <description>Use this for School Age and Pre-School program types</description>
    <label>Application - ODE Program</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/Ongoing_Quality_Rating_Registration.recordType-meta.xml
<RecordType>
    <fullName>Ongoing_Quality_Rating_Registration</fullName>
    <active>true</active>
    <description>This record type will be used for ongoing quality rating transactions except annual reports</description>
    <label>SUTQ - Ongoing Registration</label>
</RecordType>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/CLQ_Transaction_Document__c.object-meta.xml
<CustomObject>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_All_Comments__c.field-meta.xml
<CustomField>
    <fullName>CLQ_All_Comments__c</fullName>
    <label>All Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
                <default>true</default>
                <label>Attached</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CLQ_NotifyApplicantTest2.cls
@isTest
private class CLQ_NotifyApplicantTest2 {
    
    @testSetup 
    public static void testSetup()
    {
        
        Account accountrecord_setup = new Account(Name='Test Account Setup',CLQ_DIRN__c = '1234'); 
        insert accountrecord_setup ; 
    }
    @IsTest
    static void myUnitTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            // TO DO: implement unit test
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            //CLQ_NotifyApplicantTest notApplicant = new CLQ_NotifyApplicantTest();
            //Id objInitialRegId = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByName().get('SUTQ - Initial Registration').getRecordTypeId();
            Id ccApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_CC_Center').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ; 
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord.CLQ_License_Type__c = 'Continuous';
            programRecord.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert programRecord ;
            
            contact c = new contact();
            c.lastname = 'tester';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord.id;
            insert r;
            
            CLQ_Program_Transaction__c pt = new CLQ_Program_Transaction__c();
            pt.recordtypeid = objOnGoingReg;
            pt.CLQ_Program__c = programRecord.id;
            pt.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt;
            
            Test.startTest();
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef); 
            ApexPages.currentPage().getParameters().put('id' ,pt.id);
            CLQ_Transaction_Document__c td = new CLQ_Transaction_Document__c();
            td.CLQ_Program_Transaction__c = pt.id;
            td.CLQ_Document_Status__c='Under Review';
            td.CLQ_All_Comments__c = 'test';
            insert td; 
            CLQ_NotifyApplicant.notification(); 
            Test.stopTest(); 
        }
    }
    
    @IsTest
    static void cccTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            //CLQ_NotifyApplicantTest notApplicant = new CLQ_NotifyApplicantTest();
            //Id objInitialRegId = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByName().get('SUTQ - Initial Registration').getRecordTypeId();
            Id ccApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_CC_Center').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ;
            //Create a program record
            CLQ_Program__c programRecord2 = new CLQ_Program__c();
            programRecord2.Name = 'Test2';
            programRecord2.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord2.CLQ_License_Type__c = 'Continuous';
            programRecord2.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord2.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord2.CLQ_Street_Address_1__c = 'test2';
            programRecord2.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert programRecord2 ;
            contact c = new contact();
            c.lastname = 'tester';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord2.id;
            insert r;        
            CLQ_Program_Transaction__c pt2 = new CLQ_Program_Transaction__c();
            pt2.recordtypeid = ccApp;
            pt2.CLQ_Program__c = programRecord2.id;
            pt2.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt2;
            
            Test.startTest();   
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef); 
            ApexPages.currentPage().getParameters().put('id' ,pt2.id);
            CLQ_Transaction_Document__c td2 = new CLQ_Transaction_Document__c();
            td2.CLQ_Program_Transaction__c = pt2.id;
            td2.CLQ_Document_Status__c='Under Review';
            td2.CLQ_All_Comments__c = 'test';
            insert td2; 
            CLQ_NotifyApplicant.notification();
            Test.stopTest();
        }
    } 
    
    @IsTest
    static void odeTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            //CLQ_NotifyApplicantTest notApplicant = new CLQ_NotifyApplicantTest();
            //Id objInitialRegId = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByName().get('SUTQ - Initial Registration').getRecordTypeId();
            Id odeApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_ODE_Program').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Pre School');
            insert configRecord;
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ; 
            //Create a program record 
            CLQ_Program__c programRecord3 = new CLQ_Program__c();
            programRecord3.Name = 'Test2';
            programRecord3.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord3.CLQ_License_Type__c = 'Continuous';
            programRecord3.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord3.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord3.CLQ_Street_Address_1__c = 'test2';
            programRecord3.CLQ_Org_Wide_Email_Addresses_SUTQ__c = 'abc@gmail.com;def@gmail.com;ghi@gmail.com';
            programRecord3.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Pre_School').getRecordTypeId();
            insert programRecord3 ;   
            contact c = new contact();
            c.lastname = 'tester'; 
            c.email = 'tester@tester.com';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord3.id;
            insert r;      
            CLQ_Program_Transaction__c pt3 = new CLQ_Program_Transaction__c();
            pt3.recordtypeid = odeApp;
            pt3.CLQ_Program__c = programRecord3.id;
            pt3.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt3;  
            
            Test.startTest();
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef);  
            ApexPages.currentPage().getParameters().put('id' ,pt3.id);
            CLQ_Transaction_Document__c td3 = new CLQ_Transaction_Document__c();
            td3.CLQ_Program_Transaction__c = pt3.id;
            td3.CLQ_Document_Status__c='Under Review';
            td3.CLQ_All_Comments__c = 'test';
            insert td3; 
            CLQ_NotifyApplicant.notification();   
            Test.stopTest();  
        }
    }
    
    @IsTest
    static void dayCampTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            
            Id dcApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Application_Day_Camp').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ; 
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test A';
            programRecord.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord.CLQ_License_Type__c = 'Continuous';
            programRecord.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert programRecord ;
            
            contact c = new contact();
            c.lastname = 'tester';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord.id;
            insert r;
            
            CLQ_Program_Transaction__c pt = new CLQ_Program_Transaction__c();
            pt.recordtypeid = dcApp;
            pt.CLQ_Program__c = programRecord.id;
            pt.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt;
            
            Test.startTest();   
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef); 
            ApexPages.currentPage().getParameters().put('id' ,pt.id);
            CLQ_Transaction_Document__c td2 = new CLQ_Transaction_Document__c();
            td2.CLQ_Program_Transaction__c = pt.id;
            td2.CLQ_Document_Status__c='Under Review';
            td2.CLQ_All_Comments__c = 'test';
            insert td2; 
            CLQ_NotifyApplicant.notification();
            Test.stopTest();
        }
    }
    @IsTest
    static void coaTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            
            Id coaApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Amendment_Change_of_Administrator').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Day Camp');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ; 
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test A';
            programRecord.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord.CLQ_License_Type__c = 'Continuous';
            programRecord.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Day_Camp').getRecordTypeId();
            insert programRecord ;
            
            contact c = new contact();
            c.lastname = 'tester';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord.id;
            insert r;
            
            CLQ_Program_Transaction__c pt = new CLQ_Program_Transaction__c();
            pt.recordtypeid = coaApp;
            pt.CLQ_Program__c = programRecord.id;
            pt.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt;
            
            Test.startTest();   
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef); 
            ApexPages.currentPage().getParameters().put('id' ,pt.id);
            CLQ_Transaction_Document__c td2 = new CLQ_Transaction_Document__c();
            td2.CLQ_Program_Transaction__c = pt.id;
            td2.CLQ_Document_Status__c='Under Review';
            td2.CLQ_All_Comments__c = 'test';
            insert td2; 
            CLQ_NotifyApplicant.notification();
            Test.stopTest();
        }
    }
    
    @IsTest
    static void coLTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            
            Id coaApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Amendment_FCC_Change_of_Location').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ; 
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test A';
            programRecord.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord.CLQ_License_Type__c = 'Continuous';
            programRecord.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert programRecord ;
            
            contact c = new contact();
            c.lastname = 'tester';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord.id;
            insert r;
            
            CLQ_Program_Transaction__c pt = new CLQ_Program_Transaction__c();
            pt.recordtypeid = coaApp;
            pt.CLQ_Program__c = programRecord.id;
            pt.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt;
            
            Test.startTest();   
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef); 
            ApexPages.currentPage().getParameters().put('id' ,pt.id);
            CLQ_Transaction_Document__c td2 = new CLQ_Transaction_Document__c();
            td2.CLQ_Program_Transaction__c = pt.id;
            td2.CLQ_Document_Status__c='Under Review';
            td2.CLQ_All_Comments__c = 'test';
            insert td2; 
            CLQ_NotifyApplicant.notification();
            Test.stopTest();
        }
    }
    
    @IsTest
    static void coCTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_NotifyApplicant notApplicant = new CLQ_NotifyApplicant();
            
            Id coaApp = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Amendment_Change_of_Capacity_Space').getRecordTypeId();
            Id objOnGoingReg = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Ongoing_Quality_Rating_Registration').getRecordTypeId();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ; 
            
            //Create a program record
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test A';
            programRecord.CLQ_License_Issue_Date__c  = system.date.today();
            programRecord.CLQ_License_Type__c = 'Continuous';
            programRecord.CLQ_License_Registration_Status__c = 'Licensed';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            insert programRecord ;
            
            contact c = new contact();
            c.lastname = 'tester';
            insert c;
            CLQ_Role__c r = new CLQ_Role__c();
            r.CLQ_Contact__c = c.id;
            r.CLQ_Program__c = programRecord.id;
            insert r;
            
            CLQ_Program_Transaction__c pt = new CLQ_Program_Transaction__c();
            pt.recordtypeid = coaApp;
            pt.CLQ_Program__c = programRecord.id;
            pt.CLQ_Transaction_Status__c = 'Not Submitted';
            insert pt;
            
            Test.startTest();   
            PageReference pageRef = Page.CLQ_NotifyApplicantpage;
            Test.setCurrentPage(pageRef); 
            ApexPages.currentPage().getParameters().put('id' ,pt.id);
            CLQ_Transaction_Document__c td2 = new CLQ_Transaction_Document__c();
            td2.CLQ_Program_Transaction__c = pt.id;
            td2.CLQ_Document_Status__c='Under Review';
            td2.CLQ_All_Comments__c = 'test';
            insert td2; 
            CLQ_NotifyApplicant.notification();
            Test.stopTest();
        }
    }    
}