force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>Answers to all questions are stored here.</description>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text__c</fullName>
    <description>The actual answer text to a question is saved here.</description>
    <label>Answer Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Association to a Program Transaction record.</description>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Findings__c/CLQ_Findings__c.object-meta.xml
<CustomObject>
    <label>Findings</label>
    <nameField>
        <displayFormat>Findings-{000000}</displayFormat>
        <label>Findings No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Findings__c/fields/CLQ_Met_Not_Met__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Met_Not_Met__c</fullName>
    <label>Met/Not Met</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Met</fullName>
            </value>
            <value>
                <fullName>Not Met</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Findings__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Findings__c/fields/Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Findings</relationshipLabel>
    <relationshipName>Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Application_FCC.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Application_FCC</fullName>
    <active>true</active>
    <description>Use this for new application associated to Family Child Care:  type A/B Homes program</description>
    <label>Application - FCC</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/SUTQ_Expedited_Registration.recordType-meta.xml
<RecordType>
    <fullName>SUTQ_Expedited_Registration</fullName>
    <active>true</active>
    <label>SUTQ - Expedited Registration</label>
</RecordType>

force-app/main/default/objects/CLQ_Standard_Detail__c/CLQ_Standard_Detail__c.object-meta.xml
<CustomObject>
    <label>Standard Detail</label>
    <nameField>
        <label>Standard Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_Met_Not_Met__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Met_Not_Met__c</fullName>
    <description>This field maps which possible responses for each Annual Report question result in Met or Not Met</description>
    <inlineHelpText>This field maps which possible responses for each Annual Report question result in Met or Not Met</inlineHelpText>
    <label>Met/Not Met</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_PossibleResponses__c.field-meta.xml
<CustomField>
    <fullName>CLQ_PossibleResponses__c</fullName>
    <description>Possible responses for the question.</description>
    <label>Possible Responses</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/CLQ_QuestionType__c.field-meta.xml
<CustomField>
    <fullName>CLQ_QuestionType__c</fullName>
    <description>Type of question.</description>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Options</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Yes-No</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
            <value>
                <fullName>Single Option</fullName>
            </value>
            <value>
                <fullName>Instruction</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/Possible_Points__c.field-meta.xml
<CustomField>
    <fullName>Possible_Points__c</fullName>
    <label>Possible Points</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/fields/Possible_Ratings__c.field-meta.xml
<CustomField>
    <fullName>Possible_Ratings__c</fullName>
    <label>Possible Ratings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/recordTypes/CLQ_Question.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Question</fullName>
    <active>true</active>
    <description>All questions will be stored here</description>
    <label>Question</label>
</RecordType>

force-app/main/default/objects/CLQ_Transaction_Document__c/CLQ_Transaction_Document__c.object-meta.xml
<CustomObject>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
                <default>true</default>
                <label>Attached</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/Document_Points__c.field-meta.xml
<CustomField>
    <fullName>Document_Points__c</fullName>
    <label>Document Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Document Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalulateDeskReviewRatingCtrlLWCTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CalulateDeskReviewRatingCtrlLWCTest
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				9/15/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest()
public with sharing class CalulateDeskReviewRatingCtrlLWCTest {
    static CLQ_Program_Transaction__c ProgramTransaction = new CLQ_Program_Transaction__c();
    @testsetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    
    
    
    @IsTest     
    static void testRatingFour(){
        //prepareTestData();
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            List<CLQ_OCLQS_Configuration__c> configrecords = new List<CLQ_OCLQS_Configuration__c>();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            configrecords.add(configRecord);
            
            CLQ_OCLQS_Configuration__c configRecord1 = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
            configrecords.add(configRecord1);
            if(Schema.SObjectType.CLQ_OCLQS_Configuration__c.isAccessible()){
                insert configrecords;
            }
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234',Ownership = 'Individual Ownership'); 
            insert accountrecord ;
            
            Account accountrecord1 = new Account(Name='Test Account',CLQ_DIRN__c = '1234',Ownership = 'Individual Ownership');
            if(Schema.SObjectType.Account.isAccessible()){
                insert accountrecord1;
            }
            
            //Create a program record
            List<CLQ_Program__c> programs = new List<CLQ_Program__c>();
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            if(Schema.SObjectType.CLQ_Program__c.isAccessible()){
                insert programRecord;
            }
            
            List<CLQ_Program_Transaction__c> progTransactions = new List<CLQ_Program_Transaction__c>();
            ProgramTransaction.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('SUTQ_Expedited_Registration').getRecordTypeId();
            ProgramTransaction.CLQ_Transaction_Status__c = 'In Progress';
            ProgramTransaction.CLQ_Program__c = programRecord.id;
            ProgramTransaction.CLQ_Associated_Organization__c = accountrecord.id ;
            //progTransactions.add(ProgramTransaction);
            if(Schema.SObjectType.CLQ_Program_Transaction__c.isAccessible()){
                insert ProgramTransaction; 
            }
            
            List<CLQ_Findings__c> findings = new list<CLQ_Findings__c>();
            CLQ_Findings__c finding = new CLQ_Findings__c(Rating__c = '3',Points__c = '4',Program_Transaction__c = ProgramTransaction.Id);
            if(Schema.SObjectType.CLQ_Findings__c.isAccessible()){
                insert finding;
            }
            
            
            
            
            Test.startTest();
            
            CLQ_CalulateDeskReviewRatingCtrlLWC extensionObject = new CLQ_CalulateDeskReviewRatingCtrlLWC();
            
            Test.stopTest();
        } 
    }
    @IsTest
    static void testRatingFive(){
        //prepareTestData();
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            List<CLQ_OCLQS_Configuration__c> configrecords = new List<CLQ_OCLQS_Configuration__c>();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            configrecords.add(configRecord);
            
            CLQ_OCLQS_Configuration__c configRecord1 = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
            configrecords.add(configRecord1);
            if(Schema.SObjectType.CLQ_OCLQS_Configuration__c.isAccessible()){
                insert configrecords;
            }
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234',Ownership = 'Individual Ownership'); 
            if(Schema.SObjectType.Account.isAccessible()){
                insert accountrecord;
            }
            
            Account accountrecord1 = new Account(Name='Test Account',CLQ_DIRN__c = '1234',Ownership = 'Individual Ownership'); 
            if(Schema.SObjectType.Account.isAccessible()){
                insert accountrecord1;
            }
            
            //Create a program record
            List<CLQ_Program__c> programs = new List<CLQ_Program__c>();
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            if(Schema.SObjectType.CLQ_Program__c.isAccessible()){
                insert programRecord;
            }
            
            List<CLQ_Program_Transaction__c> progTransactions = new List<CLQ_Program_Transaction__c>();
            ProgramTransaction.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_FCC').getRecordTypeId();
            ProgramTransaction.CLQ_Transaction_Status__c = 'In Progress';
            ProgramTransaction.CLQ_Program__c = programRecord.id;
            ProgramTransaction.CLQ_Associated_Organization__c = accountrecord.id ;
            //progTransactions.add(ProgramTransaction);
            if(Schema.SObjectType.CLQ_Program_Transaction__c.isAccessible()){
                insert ProgramTransaction;
            }
            
            
            List<CLQ_Findings__c> findings = new list<CLQ_Findings__c>();
            CLQ_Findings__c finding = new CLQ_Findings__c(Rating__c = '3',Points__c = '4',Program_Transaction__c = ProgramTransaction.Id);
            if(Schema.SObjectType.CLQ_Findings__c.isAccessible()){
                insert finding;
            }
            
            List<CLQ_Transaction_Document__c> transactionDocs = new list<CLQ_Transaction_Document__c>();       
            CLQ_Transaction_Document__c TD = new CLQ_Transaction_Document__c(Name = 'Test',Document_Points__c = 2,Rating__c='3',CLQ_Document_Status__c='Test',CLQ_Program_Transaction__c=ProgramTransaction.id);
            if(Schema.SObjectType.CLQ_Transaction_Document__c.isAccessible()){
                insert TD;
            }
            
            
            Id questionRecordTypeId = Schema.SObjectType.CLQ_Standard_Detail__c.getRecordTypeInfosByDeveloperName().get('CLQ_Question').getRecordTypeId();
            CLQ_Standard_Detail__c standardDetail = new CLQ_Standard_Detail__c(RecordTypeId=questionRecordTypeId ,Name = 'Test', CLQ_PossibleResponses__c = 'Test;Yes;No',
                                                                               Possible_Points__c = '3;4;5',Possible_Ratings__c = '1;2',CLQ_Met_Not_Met__c='Met',CLQ_QuestionType__c = 'Picklist');
            if(Schema.SObjectType.CLQ_Standard_Detail__c.isAccessible()){
                insert standardDetail;
            }
            Answer__c ans = new Answer__c(Name = 'Test',Answer_Text__c= 'Test',Points__c = 30, Rating_Number__c = 3,AssociatedQuestion__c = standardDetail.Id, Program_Transaction__c = ProgramTransaction.Id);
            if(Schema.SObjectType.Answer__c.isAccessible()){
                insert ans;
            }
            
            
            
            
            
            
            
            
            
            Test.startTest();
            
            CLQ_CalulateDeskReviewRatingCtrlLWC extensionObject = new CLQ_CalulateDeskReviewRatingCtrlLWC();
            extensionObject.calulateDeskReviewRating(ProgramTransaction.id);
            
            
            
            Test.stopTest();
        }
        
    }
    
    @IsTest
    static void testRatingSeven(){
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            List<CLQ_OCLQS_Configuration__c> configrecords = new List<CLQ_OCLQS_Configuration__c>();
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
            configrecords.add(configRecord);
            
            CLQ_OCLQS_Configuration__c configRecord1 = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
            configrecords.add(configRecord1);
            if(Schema.SObjectType.CLQ_OCLQS_Configuration__c.isAccessible()){
                insert configrecords;
            }
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234',Ownership = 'Individual Ownership'); 
            if(Schema.SObjectType.Account.isAccessible()){
                insert accountrecord ;
            }
            
            Account accountrecord1 = new Account(Name='Test Account',CLQ_DIRN__c = '1234',Ownership = 'Individual Ownership'); 
            if(Schema.SObjectType.Account.isAccessible()){
                insert accountrecord1 ;
            }
            
            //Create a program record
            List<CLQ_Program__c> programs = new List<CLQ_Program__c>();
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            if(Schema.SObjectType.CLQ_Program__c.isAccessible()){
                insert programRecord;
            }
            
            List<CLQ_Program_Transaction__c> progTransactions = new List<CLQ_Program_Transaction__c>();
            ProgramTransaction.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_FCC').getRecordTypeId();
            ProgramTransaction.CLQ_Program__c = programRecord.id;
            ProgramTransaction.CLQ_Associated_Organization__c = accountrecord.id ;
            //progTransactions.add(ProgramTransaction);
            if(Schema.SObjectType.CLQ_Program_Transaction__c.isAccessible()){
                insert ProgramTransaction;
            }
            
            
            
            
            
            
            
            Test.startTest();
            
            CLQ_CalulateDeskReviewRatingCtrlLWC extensionObject = new CLQ_CalulateDeskReviewRatingCtrlLWC();
            extensionObject.calulateDeskReviewRating(ProgramTransaction.id);
            
            
            
            Test.stopTest();
        }
        
    }
    
    
    
}