force-app/main/default/objects/Account/fields/CLQ_DIRN__c.field-meta.xml
<CustomField>
    <fullName>CLQ_DIRN__c</fullName>
    <description>District IRN number entered by the program during application creation.</description>
    <externalId>true</externalId>
    <label>Org IRN</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/AR_Anniv_Date_120_Days_away__c.field-meta.xml
<CustomField>
    <fullName>AR_Anniv_Date_120_Days_away__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Annual Report- Anniversary Date greater than 120 days away</description>
    <inlineHelpText>Checking this box allows a program to create an Annual Report outside of the eligible time-frame.</inlineHelpText>
    <label>Late Annual Report Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/AR_Ongoing_Reg_less_than_6_months_ago__c.field-meta.xml
<CustomField>
    <fullName>AR_Ongoing_Reg_less_than_6_months_ago__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Annual Report- Ongoing Registration less than 6 months ago</description>
    <inlineHelpText>Checking this box allows a program to create an Annual Report after it completed an Ongoing Registration in the last 6 months.</inlineHelpText>
    <label>Annual Report/Ongoing Exception Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Initial_Registration_Not_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Initial_Registration_Not_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this box allows a currently rated program to create an Initial Registration.</inlineHelpText>
    <label>Initial Registration Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/IR_Rating_Removed_12_months__c.field-meta.xml
<CustomField>
    <fullName>IR_Rating_Removed_12_months__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checking this box allows a program to create an Initial Registration less than 12 months after its rating was removed due to SRNC.</inlineHelpText>
    <label>Allow 12 Month Initial Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Program_Rating__c.field-meta.xml
<CustomField>
    <fullName>Program_Rating__c</fullName>
    <label>SUTQ Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Anniversary_Date__c</fullName>
    <description>Program rating anniversary date gets populated based on the program effective date and expiration date.</description>
    <label>Rating Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Discontinue__c.field-meta.xml
<CustomField>
    <fullName>Rating_Discontinue__c</fullName>
    <description>Rating discontinue date is used when the program rating turns to 0 either by manually or through AR process or through Ongoing registration it should get punched with the system date on that particular date</description>
    <label>Rating Discontinue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Effective_Date__c</fullName>
    <label>SUTQ Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Reduction_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Reduction_Date__c</fullName>
    <description>Adding this field to track the manual rating update with rating reasons &quot;Rating Reduced&quot;</description>
    <label>Rating Reduction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/RatingChangedDate__c.field-meta.xml
<CustomField>
    <fullName>RatingChangedDate__c</fullName>
    <description>This field gets updated when the annual report not met and the rating got lowered.</description>
    <label>RatingChangedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Unable_to_Rate_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Unable_to_Rate_Reasons__c</fullName>
    <label>Rating Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Change of Location</fullName>
            </value>
            <value>
                <fullName>Change of Owner Rating</fullName>
            </value>
            <value>
                <fullName>Does not meet requirements of the Administrative Practices</fullName>
            </value>
            <value>
                <fullName>Does not meet requirements of the Family and Community Partnership domain</fullName>
            </value>
            <value>
                <fullName>Does not meet requirements of the Learning and Development domain</fullName>
            </value>
            <value>
                <fullName>Does not meet requirements of the Staff Qualifications and Professional Development domain</fullName>
            </value>
            <value>
                <fullName>FCC change of provider type</fullName>
            </value>
            <value>
                <fullName>Intent to Revoke</fullName>
            </value>
            <value>
                <fullName>Rating Reduced</fullName>
            </value>
            <value>
                <fullName>Rating Removed</fullName>
            </value>
            <value>
                <fullName>Required Compliance</fullName>
            </value>
            <value>
                <fullName>Voluntarily Discontinue Participation in SUTQ</fullName>
            </value>
            <value>
                <fullName>Expedited Rating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License / Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/Recommended_Rating__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Rating__c</fullName>
    <label>Recommended Desk Review Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/SUTQ_Expedited_Registration.recordType-meta.xml
<RecordType>
    <fullName>SUTQ_Expedited_Registration</fullName>
    <active>true</active>
    <label>SUTQ - Expedited Registration</label>
</RecordType>

force-app/main/default/classes/CLQ_Program_TransactionTrigHdlr_Test.cls
@isTest
private  class CLQ_Program_TransactionTrigHdlr_Test {
    
    @testsetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    
    
    //test
    @IsTest
    static void beforeUpdateTest() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            //Create Config
            CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Pre School');
            insert configRecord; 
            
            //Create account record
            Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
            insert accountrecord ;
            //Create a new user
            Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
            User usr = new User(LastName = 'LIVESTON',
                                FirstName = 'JASON',
                                Alias = 'jliv',
                                Email = 'jason.liveston@asdf.com',
                                Username = 'jason.liveston@abcdefg8395023.com',
                                ProfileId = profileId.id,
                                TimeZoneSidKey = 'GMT',
                                LanguageLocaleKey = 'en_US',
                                EmailEncodingKey = 'UTF-8',
                                LocaleSidKey = 'en_US'
                               );
            insert usr;      
            
            CLQ_OCLQS_Configuration__c config = new CLQ_OCLQS_Configuration__c();
            config.Name = 'FCC - Type B Home';
            
            insert config;
            
            CLQ_Program__c programRecord = new CLQ_Program__c();
            programRecord.Name = 'Test';
            programRecord.CLQ_Associated_Organization__c = accountrecord.id;
            programRecord.CLQ_Street_Address_1__c = 'test';
            programRecord.CLQ_License_Registration_Status__c = 'Exempt';
            programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            //programRecord.AR_Anniv_Date_120_Days_away__c = false;
            //programRecord.Initial_Registration_Not_Allowed__c = false;
            //programRecord.AR_Ongoing_Reg_less_than_6_months_ago__c = false;
            //programRecord.IR_Rating_Removed_12_months__c = false;
            //programRecord.Unable_to_Rate_Reasons__c = 'Voluntarily Discontinue Participation in SUTQ';
            //programRecord.Rating_Effective_Date__c = system.today();//RR
            //programRecord.Rating_Anniversary_Date__c = system.today().addYears(1);
            //programRecord.RatingChangedDate__c = system.today();
            programRecord.Program_Rating__c='3';
            programRecord.Rating_Reduction_Date__c = system.today().addmonths(-2);
            programRecord.Rating_Discontinue__c = Date.today().addmonths(-5);
            insert programRecord;
            //Create a CLQ_Program_Transaction__c record
            CLQ_Program_Transaction__c ProgramTransaction = new CLQ_Program_Transaction__c();
            ProgramTransaction.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('SUTQ_Expedited_Registration').getRecordTypeId();
            ProgramTransaction.CLQ_Program__c = programRecord.id;
            ProgramTransaction.ownerid = UserInfo.getUserId();
            ProgramTransaction.CLQ_Transaction_Status__c  = 'Rating Assessment Complete';
            ProgramTransaction.Recommended_Rating__c = '1';
            ProgramTransaction.Annual_Report_Overall_Requirements__c = 'Not Met';
            ProgramTransaction.Recommended_Annual_Report_Rating__c = '2';
            ProgramTransaction.SUTQ_Deferral_Due_Date__c= Date.Today();
            ProgramTransaction.IsApproved_PrgTran__c = True;
            insert ProgramTransaction;
            
            
            
            //get transactions
            CLQ_Program_Transaction__c testTrans = new CLQ_Program_Transaction__c();
            testTrans.CLQ_Program__c = programRecord.Id;
            //insert testTrans;
            
        }
    }
    
}