force-app/main/default/objects/Account/fields/Provider_Type__c.field-meta.xml
<CustomField>
    <fullName>Provider_Type__c</fullName>
    <label>Provider Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FCC - Type A Home</fullName>
            </value>
            <value>
                <fullName>FCC - Type B Home</fullName>
            </value>
            <value>
                <fullName>Child Care Center</fullName>
            </value>
            <value>
                <fullName>Day Camp</fullName>
            </value>
            <value>
                <fullName>In-Home Aide</fullName>
            </value>
            <value>
                <fullName>Out of State</fullName>
            </value>
            <value>
                <fullName>School Age Child Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Is_Withdrawn__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Is_Withdrawn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Withdrawn?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Type__c</fullName>
    <inlineHelpText>Type of license issued</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
                <default>true</default>
                <label>Provisional</label>
            </value>
            <value>
                <fullName>Continuous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Proposed_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Proposed_Open_Date__c</fullName>
    <description>Only Future Date</description>
    <label>Proposed Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Street_Address_1__c</fullName>
    <label>Street Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Program_Rating__c.field-meta.xml
<CustomField>
    <fullName>Program_Rating__c</fullName>
    <label>SUTQ Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Anniversary_Date__c</fullName>
    <description>Program rating anniversary date gets populated based on the program effective date and expiration date.</description>
    <label>Rating Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Associated_Organization__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Associated_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License / Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Proposed_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Proposed_Open_Date__c</fullName>
    <label>Proposed Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/Annual_Report.recordType-meta.xml
<RecordType>
    <fullName>Annual_Report</fullName>
    <active>true</active>
    <description>Use this record type for Annual Reports</description>
    <label>SUTQ - Annual Report</label>
</RecordType>

force-app/main/default/objects/PGFField__c/PGFField__c.object-meta.xml
<CustomObject>
    <description>Fields metadata object for framework.</description>
    <label>Field</label>
    <nameField>
        <label>FB_Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFField__c/fields/CSSClasses__c.field-meta.xml
<CustomField>
    <fullName>CSSClasses__c</fullName>
    <label>CSS Classes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order Number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent sub-section</description>
    <label>Sub-Section</label>
    <referenceTo>PGFSubSection__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multi-Select</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>TextArea</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFPage__c/PGFPage__c.object-meta.xml
<CustomObject>
    <description>Page metadata object for framework.</description>
    <label>Page</label>
    <nameField>
        <label>FB_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFPage__c/fields/Success_Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Success_Message_Body__c</fullName>
    <label>Success Message Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSection__c/PGFSection__c.object-meta.xml
<CustomObject>
    <description>Section metadata object for framework.</description>
    <label>Section</label>
    <nameField>
        <label>FB_Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent page.</description>
    <label>Page</label>
    <referenceTo>PGFPage__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/PGFSubSection__c.object-meta.xml
<CustomObject>
    <description>Sub-section metadata object for framework.</description>
    <label>Sub-Section</label>
    <nameField>
        <label>FB_SubSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Field_Labels__c</fullName>
    <label>Applicable Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Form_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Form_Field_Labels__c</fullName>
    <label>Applicable Form Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFields__c</fullName>
    <description>Applicable Fields</description>
    <label>Applicable Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFormFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFormFields__c</fullName>
    <description>Applicable Form Fields</description>
    <label>Applicable Form Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent section</description>
    <label>Section</label>
    <referenceTo>PGFSection__c</referenceTo>
    <relationshipLabel>Sub Sections</relationshipLabel>
    <relationshipName>Sub_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Sub-section type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fieldset</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Textblock</fullName>
            </value>
            <value>
                <fullName>Hidden Fieldset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReviewPdfPageControllerTest.cls
@isTest
public class ReviewPdfPageControllerTest {
    @testsetup //Added method for Task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    
    @IsTest
    public static void TestMethod1(){
        system.assertEquals(True, 1==1,'Testing');
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
        
        User usr=CLQ_UnitTestUtilities.AddCustomerUser();
        Account Acc= new Account();
        Acc.Id=usr.AccountId;
        Acc.Name='test 123';
        Acc.Provider_Type__c='Child Care Center';
        Acc.Ownership='Individual Ownership';
        upsert Acc;
        
        
        
        CLQ_Program__c programRecord1 = new CLQ_Program__c();
        programRecord1.Name = 'Test';
        programRecord1.CLQ_Associated_Organization__c = usr.AccountId;
        programRecord1.CLQ_Street_Address_1__c = 'test';
        programRecord1.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
        programRecord1.CLQ_Program_Rating__c = 3;
        programRecord1.Program_Rating__c = '3';
        programRecord1.CLQ_License_Type__c = '  Continuous';
        programRecord1.CLQ_License_Registration_Status__c = 'Exempt';
        programRecord1.Rating_Anniversary_Date__c = Date.today();
        programRecord1.CLQ_Is_Withdrawn__c=false;
        Insert programRecord1;
        
        Test.startTest();
        
        
        PGFPage__c pgfP = new PGFPage__c();
        pgfP.Name = 'Licensing - New Application';
        pgfP.Success_Message_Body__c ='CLQ_Program_Name';
        insert pgfP;
        
        PGFSection__c pgfS = new PGFSection__c();
        pgfS.Parent__c = pgfP.Id;
        pgfS.Name = 'new Section';
        pgfS.OrderNumber__c = 45;
        insert pgfS;
        
        PGFSubSection__c pgfSS = new PGFSubSection__c();
        pgfSS.Parent__c = pgfS.Id;
        pgfSS.Name = 'ss Name';
        pgfSS.OrderNumber__c = 35;
        pgfSS.Type__c ='Component';
        pgfSS.Applicable_Form_Field_Labels__c = 'Open';
        pgfSS.ApplicableFormFields__c ='Open';
        pgfSS.Applicable_Field_Labels__c = 'Close';
        pgfSS.ApplicableFields__c ='Close';
        insert pgfSS;
        
        List<PGFField__c> fieldsReq = new List<PGFField__c>() ;
        fieldsReq.add(
            new PGFField__c(
                Name = 'CLQ_Proposed_Open_Date__c' ,
                CSSClasses__c ='col-md-4' ,
                Label__c ='Proposed Open Date' ,
                ObjectAPIName__c = 'CLQ_Program_Transaction__c' ,
                Type__c ='Date' ,
                OrderNumber__c = 2 ,
                Parent__c =  pgfSS.Id ,
                Required__c = true
            )   
        ); 
        
        
        INSERT fieldsReq ;
        
        
        CLQ_Program_Transaction__c programTransaction1 = new CLQ_Program_Transaction__c();
        programTransaction1.CLQ_Program__c = programRecord1.Id;
        programTransaction1.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('Annual_Report').getRecordTypeId();
        programTransaction1.CLQ_Rating_Confirmed_by_Program__c = '2';
        programTransaction1.CLQ_Transaction_Status__c = 'Not Complete';
        insert programTransaction1;
        
        Map<String, Object> fields=new Map<String, Object>();
        fields.put('label', '123');
        fields.put('Value','2' );
        fields.put('ObjectApi', 'CLQ_Program__c');
        fields.put('Type', 'Multi-Select');
        fields.put('FieldApi', 'Program_Rating__c');
        
        Map<String, Object> fields1=new Map<String, Object>();
        fields1.put('label', '123');
        fields1.put('Value', Date.today() );
        fields1.put('ObjectApi', 'CLQ_Program_Transaction__c');
        fields1.put('Type', 'Date');
        fields1.put('FieldApi', 'CLQ_Certificate_Issue_Date__c');
        
        Map<String, Object> fields2=new Map<String, Object>();
        fields2.put('label', '123');
        fields2.put('Value',5 );
        fields2.put('ObjectApi', 'CLQ_Program_Transaction__c');
        fields2.put('Type', 'Number');
        fields2.put('FieldApi', 'CLQ_Number_of_Residents__c');
        
        Map<String, Object> fields3=new Map<String, Object>();
        fields3.put('label', '123');
        fields3.put('Value',3 );
        fields3.put('ObjectApi', 'CLQ_Program__c');
        fields3.put('Type', 'Number');
        fields3.put('FieldApi', 'CLQ_Program_Rating__c');
        
        Map<String, Object> fields4=new Map<String, Object>();
        fields4.put('label', '123');
        fields4.put('Value', Date.today());
        fields4.put('ObjectApi', 'CLQ_Program__c');
        fields4.put('Type', 'Date');
        fields4.put('FieldApi', 'Rating_Anniversary_Date__c');
        
        Map<String, Object> fields5=new Map<String, Object>();
        fields5.put('label', '123');
        fields5.put('Value','2' );
        fields5.put('ObjectApi', 'CLQ_Program_Transaction__c');
        fields5.put('Type', 'Multi-Select');
        fields5.put('FieldApi', 'CLQ_Rating_Confirmed_by_Program__c');
        
        list<Map<String, Object>> fieldlist=new list<Map<String, Object>>();
        fieldlist.add(fields);
        fieldlist.add(fields1);
        fieldlist.add(fields2);
        fieldlist.add(fields3);
        fieldlist.add(fields4);
        fieldlist.add(fields5);
        
        Map<String, Object> subsection=new Map<String, Object>();
        subsection.put('label', 'Fieldset');
        subsection.put('Type', 'Fieldset');
        subsection.put('Name', pgfSS.Name);
        subsection.put('status',  pgfSS.Applicable_Form_Field_Labels__c);
        subsection.put('Fields',  fieldlist);
        
        
        list<Map<String, Object>> sectionlist=new list<Map<String, Object>>();
        list<Map<String, Object>> subsectionlist=new list<Map<String, Object>>();
        subsectionlist.add(subsection);
        
        Map<String, Object> sections=new Map<String, Object>();
        sections.put('label', 'Fieldset');
        sections.put('Name', pgfSS.Name);
        sections.put('status',  pgfSS.Applicable_Form_Field_Labels__c);
        sections.put('SubSections',  subsectionlist);
        
        sectionlist.add(sections);
        
        PageReference pageRef = Page.ReviewPdfPage;
        pageRef.getParameters().put('programTransactionId',programTransaction1.id);
        pageRef.getParameters().put('selectedProgramId',programRecord1.id);
        Test.setCurrentPage(pageRef);
        
        ReviewPdfPageController ReviewCtrl=new ReviewPdfPageController();
        Test.stopTest();
        
    }
}