force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>All questions used across OCLQS</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Checklist__mdt/Required_Checklist__mdt.object-meta.xml
<CustomObject>
    <label>Required checklist</label>
    <pluralLabel>Required checklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/Required_Checklist__mdt/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RequiredCheckListItems_Test.cls
@isTest()
public class RequiredCheckListItems_Test {
    @testSetup 
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    @IsTest
    static void requiredCheckList(){
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            Test.startTest();
            //RequiredCheckListItems req = new RequiredCheckListItems();
            RequiredCheckListItems.getChecklistRecords();
            Test.stopTest();
        }
    }
    
    @IsTest
    static void requiredCheckListOne(){
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            Test.startTest();
            //RequiredCheckListItems req = new RequiredCheckListItems();
            //RequiredCheckListItems.getChecklistRecords();
            
            RequiredCheckListItems.getChecklistRecords() ;
            
            Test.stopTest();
        }
    }
    
    @IsTest
    static void requiredCheckListTwo(){
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            Test.startTest();
            //RequiredCheckListItems req = new RequiredCheckListItems();
            //RequiredCheckListItems.getChecklistRecords();
            Required_Checklist__mdt a = new Required_Checklist__mdt(Question__c='');
            RequiredCheckListItems.getChecklistRecords();
            Test.stopTest();
        }
    }
    
    
}