force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>All questions used across OCLQS</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Checklist__mdt/Required_Checklist__mdt.object-meta.xml
<CustomObject>
    <label>Required checklist</label>
    <pluralLabel>Required checklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/Required_Checklist__mdt/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RequiredCheckListItems.cls
public with sharing class RequiredCheckListItems {
   
    @AuraEnabled
    public static List<Required_Checklist__mdt> getChecklistRecords(){
        try {
            List<Required_Checklist__mdt> lstQuestion = [Select id,Question__c from Required_Checklist__mdt];
            return lstQuestion;           
		
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        //return null;
    }
}