force-app/main/default/objects/CLQ_County__c/CLQ_County__c.object-meta.xml
<CustomObject>
    <description>List of OH county a Organization/Program can operate from</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_County__c/fields/Area_Region__c.field-meta.xml
<CustomField>
    <fullName>Area_Region__c</fullName>
    <label>Area/Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Eastern</fullName>
            </value>
            <value>
                <fullName>Northern</fullName>
            </value>
            <value>
                <fullName>Piedmont</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_County__c/fields/CCC_Field_Officers__c.field-meta.xml
<CustomField>
    <fullName>CCC_Field_Officers__c</fullName>
    <label>CCC Field Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDSS/CENTRAL LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/PIEDMONT LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS_CHILD_WELFARE_LICENSING</fullName>
                <label>VDSS/CHILD_WELFARE_LICENSING</label>
            </value>
            <value>
                <fullName>VDSS/PENINSULA LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/EASTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/VALLEY LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/FAIRFAX LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/WESTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/NORTHERN LICENSING OFFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_County__c/fields/FCC_Field_officers__c.field-meta.xml
<CustomField>
    <fullName>FCC_Field_officers__c</fullName>
    <label>FCC Field Office</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VDSS/CENTRAL LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/PIEDMONT LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/CHILD WELFARE LICENSING UNIT</fullName>
            </value>
            <value>
                <fullName>VDSS/PENINSULA LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/EASTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/VALLEY LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/FAIRFAX LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/WESTERN LICENSING OFFICE</fullName>
            </value>
            <value>
                <fullName>VDSS/NORTHERN LICENSING OFFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Licensing_Specialist__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Licensing_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensing Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Not Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_County__c</fullName>
    <formula>CLQ_Program__r.CLQ_County__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>XCounty</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Fee_Paid__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Fee Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_New_County__c.field-meta.xml
<CustomField>
    <fullName>CLQ_New_County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New County</label>
    <referenceTo>CLQ_County__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Withdrawn by Provider</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Review in Progress</fullName>
            </value>
            <value>
                <fullName>Under Specialist or Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Closed at Applicant’s Request</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Under Supervisor or Approver Review</fullName>
            </value>
            <value>
                <fullName>Application Revised</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer&apos;s Review</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approver Review in Progress</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Application</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Renew Application - Day Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLQ_ProgramTransactionHdlrLcs2Test.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_ProgramTransactionHdlrLcs2Test
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest
private class CLQ_ProgramTransactionHdlrLcs2Test {
    
    /*This test method covers CLQ_ProgramTransactionTrigHdlrLicsng class*/
    @IsTest
    static  void assignOwnerTest1() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[0]; 	//FCC - Type B Home - Application - FCC
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            system.debug('assignOwnerTest1 update');
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            //ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            //update ProgramTransaction;	
            
            ProgramTransaction.ownerid = UserInfo.getUserId();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;   
            update ProgramTransaction;
            test.stopTest();
        }
        
    }	
    @IsTest
    static void assignOwnerTest2() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[2]; //Child Care Center - Application - CC Center
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;  
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            system.debug('assignOwnerTest2 update');
            ProgramTransaction.ownerid = UserInfo.getUserId();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;   
            update ProgramTransaction;
            test.stopTest(); 
        }
        
    }	
    @IsTest
    static void assignOwnerTest3() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[4]; //In-Home Aide
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            ProgramTransaction.ownerid = UserInfo.getUserId();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;   
            update ProgramTransaction;
            system.debug('assignOwnerTest3 update');
            test.stopTest(); 
        }
    }	
    @IsTest
    static void assignOwnerTest4() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[5]; //Registration - Out of State
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            ProgramTransaction.ownerid = UserInfo.getUserId();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;   
            update ProgramTransaction;
            system.debug('assignOwnerTest4 update');
            
            test.stopTest(); 
        }
    }	
    @IsTest
    static void assignOwnerTest5() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[6]; //Application - ODE Program
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            ProgramTransaction.ownerid = UserInfo.getUserId();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;   
            update ProgramTransaction;
            system.debug('assignOwnerTest5 update');
            
            test.stopTest(); 
        }
    }	
    @IsTest
    static void assignOwnerTest6() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[8]; //Application - ODE Program
            ProgramTransaction.CLQ_Transaction_Type__c = 'Update';
            ProgramTransaction.CLQ_Registration_Status__c = 'Not Submitted'; 
            
            update ProgramTransaction; 
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false; 
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            ProgramTransaction.ownerid = UserInfo.getUserId(); 
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false; 
            update ProgramTransaction;
            test.stopTest(); //
        }
    }	
    @IsTest
    static void assignOwnerTest7() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[10]; //change loc
            
            ProgramTransaction.CLQ_Fee_Paid__c = true;
            CLQ_County__c cnty = new CLQ_County__c(Name = 'FULTON', CCC_Field_Officers__c = 'Toledo', 
                                                   Area_Region__c='NW', FCC_Field_officers__c = 'Toledo' );
            insert cnty;
            ProgramTransaction.CLQ_New_County__c = cnty.id  ;
            
            ProgramTransaction.ownerid = UserInfo.getUserId();
            update ProgramTransaction;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            //
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            //update ProgramTransaction;			
            //system.debug('assignOwnerTest7 update');
            
            test.stopTest(); 
        }
    }		
    
    @IsTest
    static void assignOwnerTest7a() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[10]; //change loc
            
            CLQ_Program__C pgm = [select id, CLQ_Licensing_Specialist__c from CLQ_Program__C where id = :ProgramTransaction.CLQ_Program__C ];
            pgm.CLQ_Licensing_Specialist__c = null;
            update pgm;
            
            ProgramTransaction.CLQ_Fee_Paid__c = true;
            CLQ_County__c cnty = new CLQ_County__c(Name = 'FULTON', CCC_Field_Officers__c = 'Toledo', Area_Region__c='NW', FCC_Field_officers__c = 'Toledo' );
            insert cnty;
            ProgramTransaction.CLQ_New_County__c = cnty.id  ;
            
            ProgramTransaction.ownerid = UserInfo.getUserId();
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved'; //remove
            update ProgramTransaction;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            //
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            update ProgramTransaction;			
            //system.debug('assignOwnerTest7 update');
            
            test.stopTest(); 
        }
    }		
    @IsTest
    static void assignOwnerTest8() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();
            system.debug('assignOwnerTest8 update');
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[9]; //day camp
            ProgramTransaction.CLQ_Transaction_Type__c = 'Update';
            ProgramTransaction.CLQ_Registration_Status__c = 'Not Submitted'; 
            
            update ProgramTransaction; 
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false; 
            
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            ProgramTransaction.ownerid = UserInfo.getUserId();
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;   
            //update ProgramTransaction;
            
            test.stopTest(); 
        }
    }
    @IsTest
    static void assignOwnerTest9() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[11]; //change loc ode
            
            ProgramTransaction.CLQ_Fee_Paid__c = true;
            CLQ_County__c cnty = new CLQ_County__c(Name = 'FULTON', CCC_Field_Officers__c = 'Toledo', 
                                                   Area_Region__c='NW', FCC_Field_officers__c = 'Toledo' );
            insert cnty;
            ProgramTransaction.CLQ_New_County__c = cnty.id  ;
            
            ProgramTransaction.ownerid = UserInfo.getUserId();
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved'; //remove
            update ProgramTransaction;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            //
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            update ProgramTransaction;			
            //system.debug('assignOwnerTest9 update');
            
            test.stopTest(); 
        }
    }		
    @IsTest
    static void assignOwnerTest10() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[11]; //change loc ode
            
            ProgramTransaction.CLQ_Fee_Paid__c = true;
            CLQ_County__c cnty = new CLQ_County__c(Name = 'FULTON', CCC_Field_Officers__c = 'Toledo', 
                                                   Area_Region__c='NW', FCC_Field_officers__c = 'Toledo' );
            insert cnty;
            ProgramTransaction.CLQ_New_County__c = cnty.id  ;
            
            ProgramTransaction.ownerid = UserInfo.getUserId();
            ProgramTransaction.CLQ_Transaction_Status__c = 'Submitted'; //remove
            update ProgramTransaction;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            //
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            update ProgramTransaction;			
            //system.debug('assignOwnerTest9 update');
            
            test.stopTest(); 
        }
    }	
    @IsTest
    static void assignOwnerTest11() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[12]; //change loc ode
            
            ProgramTransaction.CLQ_Fee_Paid__c = true;
            CLQ_County__c cnty = new CLQ_County__c(Name = 'FULTON', CCC_Field_Officers__c = 'Toledo', 
                                                   Area_Region__c='NW', FCC_Field_officers__c = 'Toledo' );
            insert cnty;
            ProgramTransaction.CLQ_New_County__c = cnty.id  ;
            
            ProgramTransaction.ownerid = UserInfo.getUserId();
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved'; //remove
            update ProgramTransaction;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            //
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            update ProgramTransaction;			
            //system.debug('assignOwnerTest9 update');
            
            test.stopTest(); 
        }
    }
    @IsTest
    static void assignOwnerTest12() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            Test.StartTest();       
            CLQ_Program_Transaction__c ProgramTransaction = ProgramTransactionMap.values()[13]; //continuous license
            ProgramTransaction.ownerid = UserInfo.getUserId();
            update ProgramTransaction;
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            CLQ_GlobalWebserviceUtility.submitProgTrans(ProgramTransaction.id,'');
            //
            CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            
            //CLQ_Program_TransactionTriggerHandler.HasUpdated = false;
            ProgramTransaction.CLQ_Transaction_Status__c = 'Approved';
            update ProgramTransaction;			
            //system.debug('assignOwnerTest9 update');
            
            test.stopTest(); 
        }
    }			
    @TestSetup
    static void testSetup()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
        CLQ_UnitTestUtilities.HardCodedTransactionCreation();
        list<Group> queueGrps = new list<group>();
        
        
    }	
}