force-app/main/default/objects/OCLQS_Integration_Settings__mdt/OCLQS_Integration_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Store environment related integration parameters
Integration Team</description>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Attribute_1_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_1_Value__c</fullName>
    <label>Attribute 1 Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Attribute_2_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_2_Value__c</fullName>
    <label>Attribute 2 Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Attribute_3_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_3_Value__c</fullName>
    <label>Attribute 3 Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Attribute_4_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_4_Value__c</fullName>
    <label>Attribute 4 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Attribute_5_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_5_Value__c</fullName>
    <label>Attribute 5 Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Capture_Messages__c.field-meta.xml
<CustomField>
    <fullName>Capture_Messages__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Capture Messages</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Enable_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <description>Name of SFDC environment for which integration connection details are captured</description>
    <label>Environment Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>DEV</fullName>
            </value>
            <value>
                <fullName>DEVBUILD</fullName>
                <default>true</default>
                <label>DEVBUILD</label>
            </value>
            <value>
                <fullName>MOCK-1</fullName>
            </value>
            <value>
                <fullName>MOCK-2</fullName>
            </value>
            <value>
                <fullName>MOCKBUILD</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>PROD</fullName>
            </value>
            <value>
                <fullName>SAT</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>TRN</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>EMER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Error_Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Error_Email_Notification_Group__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Notification_Group__c</fullName>
    <inlineHelpText>Multiple email address comma seperated</inlineHelpText>
    <label>Error Email Notification Group</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Target_Connection_Port__c.field-meta.xml
<CustomField>
    <fullName>Target_Connection_Port__c</fullName>
    <description>Target environment connection port number</description>
    <label>Target Connection Port</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Target_Connection_URL__c.field-meta.xml
<CustomField>
    <fullName>Target_Connection_URL__c</fullName>
    <description>Target environment connection url</description>
    <label>Target Connection URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Target_Credentail_Token_OAuth_Key__c.field-meta.xml
<CustomField>
    <fullName>Target_Credentail_Token_OAuth_Key__c</fullName>
    <label>Target Credentail Token/OAuth Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Target_Credentail_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Target_Credentail_User_Id__c</fullName>
    <label>Target Credentail User Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCLQS_Integration_Settings__mdt/fields/Target_Credentail_User_Password__c.field-meta.xml
<CustomField>
    <fullName>Target_Credentail_User_Password__c</fullName>
    <label>Target Credentail User Password</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Integration_Connection_Test.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Name                : Integration_Connection_Test
** Description         : This class is a test class for Integration_Connection Class
** Version             : 1.2
** Built By            : 
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Sanjeev Chahar                    June-2016                1.0                          Created
** Vamsi Velampati                   July-2016                1.1                          Modified
** Pavan Ayta					 8/24/17 			     	   1.2			Added setExecuteControlSetting() for Task - 11615
************************************************************************************/ 

@isTest(isParallel=true)
private class Integration_Connection_Test {
    @testSetup //Added for task - 11615
	public static void setExecuteControlSetting()
	{
	CLQ_UnitTestUtilities.setExecuteControlSetting();
	} 	
    @isTest static void test_positive() {
        try{
            //List <OCLQS_Integration_Settings__mdt> listIntegration;
            //OCLQS_Integration_Settings__mdt Intset= new OCLQS_Integration_Settings__mdt();
            //Intset.Environment_Name__c='DEV';
            //listIntegration.add(Intset);
            //Integration_Connection.listIntegrationDetails=listIntegration;
                // Initialize the Integration Utility
                Integration_Connection utility = new Integration_Connection();
                
                test.StartTest();
                utility.getConnectionDetails('CBOSS','Target_Credentail_User_Id__c');  
                
                test.StopTest();
                
                System.Assert(utility.getConnectionDetails('CBOSS','Target_Credentail_User_Id__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Target_Connection_Port__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Target_Connection_URL__c') != '','Testing');            
                System.Assert(utility.getConnectionDetails('CBOSS','Target_Credentail_Token_OAuth_Key__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Target_Credentail_User_Password__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Attribute_1_Value__c') != '','Testing');  
                System.Assert(utility.getConnectionDetails('CBOSS','Attribute_2_Value__c') != '','Testing');  
                System.Assert(utility.getConnectionDetails('CBOSS','Attribute_3_Value__c') != '','Testing');  
                System.Assert(utility.getConnectionDetails('CBOSS','Enable_Debug__c') != '','Testing'); 
                System.Assert(utility.getConnectionDetails('CBOSS','Capture_Messages__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Error_Email_Notification__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Attribute_4_Value__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Attribute_5_Value__c') != '','Testing');
                System.Assert(utility.getConnectionDetails('CBOSS','Error_Email_Notification_Group__c') != '','Testing');
                Integration_Connection.sendErrorMailforMissingMetadata('test', 'text');
               
            }catch(Exception e){
                System.debug(e);
            }//End Catch
    }//End Test Positive
}//End Class