force-app/main/default/objects/CLQ_Application_Progress__c/CLQ_Application_Progress__c.object-meta.xml
<CustomObject>
    <label>Application Progress</label>
    <nameField>
        <label>Application Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Application_Progress__c/fields/CLQ_Program_Application__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Application</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Application Progress</relationshipLabel>
    <relationshipName>Application_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Application_Progress__c/fields/CLQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFField__c/PGFField__c.object-meta.xml
<CustomObject>
    <description>Fields metadata object for framework.</description>
    <label>Field</label>
    <nameField>
        <label>FB_Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFField__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label</description>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <description>Object API name</description>
    <label>ObjectAPIName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>CLQ_Program__c</fullName>
            </value>
            <value>
                <fullName>CLQ_Program_Transaction__c</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>CLQ_Role__c</fullName>
            </value>
            <value>
                <fullName>CLQ_Facility_Schedule__c</fullName>
            </value>
            <value>
                <fullName>CLQ_Room_Space__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order Number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent sub-section</description>
    <label>Sub-Section</label>
    <referenceTo>PGFSubSection__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Required</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multi-Select</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>TextArea</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFPage__c/PGFPage__c.object-meta.xml
<CustomObject>
    <description>Page metadata object for framework.</description>
    <label>Page</label>
    <nameField>
        <label>FB_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFPage__c/fields/Instructions_to_Application__c.field-meta.xml
<CustomField>
    <fullName>Instructions_to_Application__c</fullName>
    <description>Provide an instruction of the application</description>
    <inlineHelpText>Provide an instruction of the application</inlineHelpText>
    <label>Instructions to Application</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/PageTitle__c.field-meta.xml
<CustomField>
    <fullName>PageTitle__c</fullName>
    <description>Page Title</description>
    <label>Page Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/PageType__c.field-meta.xml
<CustomField>
    <fullName>PageType__c</fullName>
    <label>Page Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>News</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/ProgramRecordType__c.field-meta.xml
<CustomField>
    <fullName>ProgramRecordType__c</fullName>
    <description>Program Record Type</description>
    <label>Program Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/TransactionRecordType__c.field-meta.xml
<CustomField>
    <fullName>TransactionRecordType__c</fullName>
    <description>Transaction Record Type</description>
    <label>Transaction Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSection__c/PGFSection__c.object-meta.xml
<CustomObject>
    <description>Section metadata object for framework.</description>
    <label>Section</label>
    <nameField>
        <label>FB_Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent page.</description>
    <label>Page</label>
    <referenceTo>PGFPage__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/PGFSubSection__c.object-meta.xml
<CustomObject>
    <description>Sub-section metadata object for framework.</description>
    <label>Sub-Section</label>
    <nameField>
        <label>FB_SubSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Field_Labels__c</fullName>
    <label>Applicable Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Form_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Form_Field_Labels__c</fullName>
    <label>Applicable Form Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Record_Type__c</fullName>
    <label>Applicable Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFields__c</fullName>
    <description>Applicable Fields</description>
    <label>Applicable Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFormFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFormFields__c</fullName>
    <description>Applicable Form Fields</description>
    <label>Applicable Form Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableObject__c.field-meta.xml
<CustomField>
    <fullName>ApplicableObject__c</fullName>
    <description>Applicable Object</description>
    <label>Applicable Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ComponentAPIName__c.field-meta.xml
<CustomField>
    <fullName>ComponentAPIName__c</fullName>
    <description>Choose which component to add.</description>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TableComponent</fullName>
                <default>true</default>
                <label>Table Component</label>
            </value>
            <value>
                <fullName>FileUpload</fullName>
                <label>File Upload</label>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/IsATextBlockType__c.field-meta.xml
<CustomField>
    <fullName>IsATextBlockType__c</fullName>
    <formula>ISPICKVAL(Type__c,&quot;Textblock&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsATextBlockType?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent section</description>
    <label>Section</label>
    <referenceTo>PGFSection__c</referenceTo>
    <relationshipLabel>Sub Sections</relationshipLabel>
    <relationshipName>Sub_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/QueryWhereClause__c.field-meta.xml
<CustomField>
    <fullName>QueryWhereClause__c</fullName>
    <description>Query Where Clause</description>
    <label>Query Where Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/TextBlockBody__c.field-meta.xml
<CustomField>
    <fullName>TextBlockBody__c</fullName>
    <description>Text Block Body</description>
    <label>Text Block Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Transaction_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Record_Type__c</fullName>
    <formula>Parent__r.Parent__r.TransactionRecordType__c</formula>
    <label>Transaction Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Sub-section type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fieldset</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Textblock</fullName>
            </value>
            <value>
                <fullName>Hidden Fieldset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationFormCtrl.cls
public without sharing class ApplicationFormCtrl {
    public String pageID;
    public Id programTransactionId;
    public string language;

    public ApplicationFormCtrl(String pageID, Id programTransactionId, string language) {
        this.pageID = pageID;
        this.programTransactionId = programTransactionId;
        this.language=language;
    }

    public ApplicationInfo getApplicationInfo(){
        ApplicationInfo appInfo;
        List<PGFPage__c> pages = [SELECT Id, Name, PageTitle__c, PageType__c,Instructions_to_Application__c,TransactionRecordType__c,ProgramRecordType__c FROM PGFPage__c WHERE Id =: pageID];
        System.debug(pages);

        if(pages != null && pages.size() > 0){
            appInfo = new ApplicationInfo(pages[0]);
            getPageSections(appInfo);
        }

        return appInfo;
    }

    public String getApplicationJSON(){
        return JSON.serialize(getApplicationInfo());
    }

    private void getPageSections(ApplicationInfo appInfo){
        List<PGFSection__c> sections = [SELECT Id, Name, Label__c, OrderNumber__c FROM PGFSection__c WHERE Parent__c =: appInfo.Id ORDER BY OrderNumber__c];
        List<PageSection> pageSections = new  List<PageSection>();

        System.debug(sections);
        Map<String, String> mapSectionNameProgress = new Map<String, String>();
        if(programTransactionId <> null) {
            //Query the Application Progress
            for(CLQ_Application_Progress__c oProgress : [SELECT Id, Name, CLQ_Program_Application__c, CLQ_Status__c 
                                                         FROM CLQ_Application_Progress__c 
                                                         WHERE CLQ_Program_Application__c =: programTransactionId]) {

                mapSectionNameProgress.put(oProgress.Name, oProgress.CLQ_Status__c);
            }
        }

        if(sections != null && sections.size() > 0) {
            for(PGFSection__c p : sections){
                String status = 'Draft';
                if(!mapSectionNameProgress.isEmpty() && mapSectionNameProgress.containsKey(p.Name)) {
                    status = mapSectionNameProgress.get(p.Name);
                } 
                PageSection ps = new PageSection(p, status, language);
                pageSections.add(ps);
            }
        }

        appInfo.Sections = pageSections;

        getPageSubSections(pageSections);
    }

    private List<PageSubSection> getAssociatedSubSections(String sectionId, List<PageSubSection> subSections){
        List<PageSubSection> pageSubSections = new  List<PageSubSection>();

        if(subSections != null && subSections.size() > 0){
            for(PageSubSection p : subSections){
                if(p.Section == sectionId){
                    pageSubSections.add(p);
                }
            }
        }

        return pageSubSections;
    }

    private void getPageSubSections(List<PageSection> sections){
        List<PageSubSection> pageSubSections = new  List<PageSubSection>();

        Set<Id> pageSectionIds = new Set<Id>();
        if(sections != null && sections.size() > 0){
            for(PageSection p : sections){
                pageSectionIds.add(Id.valueOf(p.Id));
            }
        }

        System.debug(pageSectionIds);

        List<PGFSubSection__c> subSections = [SELECT Id, Name, Parent__c,ComponentAPIName__c, Label__c, OrderNumber__c, Type__c, IsATextBlockType__c, 
        TextBlockBody__c, ApplicableObject__c, Applicable_Field_Labels__c, ApplicableFields__c, ApplicableFormFields__c, Applicable_Form_Field_Labels__c, Applicable_Record_Type__c, 
        Transaction_Record_Type__c, Lookup_Object__c,QueryWhereClause__c FROM PGFSubSection__c WHERE Parent__c =:pageSectionIds ORDER BY OrderNumber__c];

        System.debug(subSections);

        if(subSections != null && subSections.size() > 0){
            for(PGFSubSection__c p : subSections){
                PageSubSection ps = new PageSubSection(p, language);
                pageSubSections.add(ps);
            }
        }

        if(sections != null && sections.size() > 0){
            for(PageSection p : sections){
               p.SubSections = getAssociatedSubSections(String.valueOf(p.Id), pageSubSections);
            }
        }

        getPageSubSectionFields(pageSubSections);
    }

    private List<PageField> getAssociatedFields(String subSectionId, List<PageField> pageSubSectionFields){
        List<PageField> pageFields = new  List<PageField>();

        if(pageSubSectionFields != null && pageSubSectionFields.size() > 0){
            for(PageField p : pageSubSectionFields){
                if(p.SubSection == subSectionId){
                    pageFields.add(p);
                }
            }
        }

        return pageFields;
    }

    private void getPageSubSectionFields(List<PageSubSection> subSections){
        List<PageField> pageSubSectionFields = new  List<PageField>();

        Set<Id> pageSubSectionIds = new Set<Id>();
        if(subSections != null && subSections.size() > 0){
            for(PageSubSection p : subSections){
                pageSubSectionIds.add(Id.valueOf(p.Id));
            }
        }

        System.debug(pageSubSectionIds);

        List<PGFField__c> pageFields = [SELECT Id, Name, ObjectAPIName__c, Parent__c, Label__c, OrderNumber__c, Type__c, Required__c, ReadOnly__c, Validator__c, CSSClasses__c, Pattern__c,Pattern_Mismatch_Message__c,Copy_Options__c FROM PGFField__c WHERE Parent__c =:pageSubSectionIds ORDER BY OrderNumber__c];

        System.debug(pageFields);
        Map<String, Set<String>> mapObjApiNameSetFields = new Map<String, Set<String>>();
        Map<String, SObject> mapObjApiNameSObject = new Map<String, SObject>();

        if(pageFields != null && pageFields.size() > 0){

            if(programTransactionId <> null) {
                
                CLQ_Program_Transaction__c oProgTransaction = [SELECT Id, CLQ_Program__c, CLQ_Associated_Organization__c FROM CLQ_Program_Transaction__c WHERE Id =: programTransactionId];

                for(PGFField__c p : pageFields) {
                   
                    if(mapObjApiNameSetFields.containsKey(p.ObjectAPIName__c)) {
                        Set<String> setExistingFields = new Set<String>();
                        setExistingFields = mapObjApiNameSetFields.get(p.ObjectAPIName__c);
                        setExistingFields.add(p.Name);
                        mapObjApiNameSetFields.put(p.ObjectAPIName__c, setExistingFields);
                    } else {
                        mapObjApiNameSetFields.put(p.ObjectAPIName__c, new Set<String>{p.Name});
                    }
                }

                System.debug('Combined Map --> ' + mapObjApiNameSetFields);


                //Query the fields - It can be either part of Account, Program Transaction or Program
                for(String sObjectApiName : mapObjApiNameSetFields.keySet()) {
                    
                    List<SObject> lstRecords = new List<SObject>();
                    Set<String> setFields = new Set<String>();
                    setFields = mapObjApiNameSetFields.get(sObjectApiName);
                    String sFields = String.join(new List<String>(setFields), ',');
                    System.debug('Fields --> ' + sFields);
                    System.debug('Set Fields --> ' + setFields);

                    if(sObjectApiName == 'Account') {
                        String sQuery = 'SELECT Id, ' + sFields + ' FROM Account WHERE Id = \'' + oProgTransaction.CLQ_Associated_Organization__c + '\'';
                        lstRecords = Database.query(sQuery);
                        mapObjApiNameSObject.put(sObjectApiName, lstRecords[0]);
                    } else if(sObjectApiName == 'CLQ_Program_Transaction__c') {
                        String sQuery = 'SELECT Id, ' + sFields + ' FROM CLQ_Program_Transaction__c WHERE Id = \'' + programTransactionId + '\'';
                        lstRecords = Database.query(sQuery);
                        mapObjApiNameSObject.put(sObjectApiName, lstRecords[0]);
                    } else if(sObjectApiName == 'CLQ_Program__c') {
                        String sQuery = 'SELECT Id, ' + sFields + ' FROM CLQ_Program__c WHERE Id = \'' + oProgTransaction.CLQ_Program__c + '\'';
                        lstRecords = Database.query(sQuery);
                        mapObjApiNameSObject.put(sObjectApiName, lstRecords[0]);
                    }
                }
            }

            for(PGFField__c p : pageFields) {
                String sValue = '';
                if(mapObjApiNameSObject <> null && mapObjApiNameSetFields.containsKey(p.ObjectAPIName__c)) {
                    SObject oRecord = mapObjApiNameSObject.get(p.ObjectAPIName__c);
                    if(oRecord.get(p.Name) <> null) {
                        sValue = String.valueOf(oRecord.get(p.Name));
                    }
                }
                
                PageField pf = new PageField(p, sValue, language);
                pageSubSectionFields.add(pf);
            }
        }

        if(subSections != null && subSections.size() > 0){
            for(PageSubSection p : subSections){
               p.Fields = getAssociatedFields(String.valueOf(p.Id), pageSubSectionFields);
            }
        }
    }
}