force-app/main/default/objects/PGFPage__c/PGFPage__c.object-meta.xml
<CustomObject>
    <description>Page metadata object for framework.</description>
    <label>Page</label>
    <nameField>
        <label>FB_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/PGFSection__c.object-meta.xml
<CustomObject>
    <description>Section metadata object for framework.</description>
    <label>Section</label>
    <nameField>
        <label>FB_Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent page.</description>
    <label>Page</label>
    <referenceTo>PGFPage__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/PGFSubSection__c.object-meta.xml
<CustomObject>
    <description>Sub-section metadata object for framework.</description>
    <label>Sub-Section</label>
    <nameField>
        <label>FB_SubSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Field_Labels__c</fullName>
    <label>Applicable Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Form_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Form_Field_Labels__c</fullName>
    <label>Applicable Form Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFields__c</fullName>
    <description>Applicable Fields</description>
    <label>Applicable Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFormFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFormFields__c</fullName>
    <description>Applicable Form Fields</description>
    <label>Applicable Form Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent section</description>
    <label>Section</label>
    <referenceTo>PGFSection__c</referenceTo>
    <relationshipLabel>Sub Sections</relationshipLabel>
    <relationshipName>Sub_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Sub-section type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fieldset</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Textblock</fullName>
            </value>
            <value>
                <fullName>Hidden Fieldset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PageSubSectionTest.cls
@isTest
public class PageSubSectionTest {
    @testSetup 
    public static void testSetup()
    {
        PGFPage__c pgfPp = new PGFPage__c();
        pgfPp.Name = 'new Page';
        insert pgfPp;
    }
    @IsTest
    static void pageSubSectionMethod(){
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            PGFPage__c pgfP = new PGFPage__c();
            pgfP.Name = 'new Page';
            insert pgfP;
            
            PGFSection__c pgfS = new PGFSection__c();
            pgfS.Parent__c = pgfP.Id;
            pgfS.Name = 'new Section';
            pgfS.OrderNumber__c = 45;
            insert pgfS;
            
            PGFSubSection__c pgfSS = new PGFSubSection__c();
            pgfSS.Parent__c = pgfS.Id;
            pgfSS.Name = 'ss Name';
            pgfSS.OrderNumber__c = 35;
            pgfSS.Type__c ='Component';
            pgfSS.Applicable_Form_Field_Labels__c = 'Open';
            pgfSS.ApplicableFormFields__c ='Open';
            pgfSS.Applicable_Field_Labels__c = 'Close';
            pgfSS.ApplicableFields__c ='Close';
            insert pgfSS;
            
            Test.startTest();
            PageSubSection PSS = new PageSubSection(pgfSS); 
            Test.stopTest();
        }
    }
}