force-app/main/default/objects/PGFPage__c/PGFPage__c.object-meta.xml
<CustomObject>
    <description>Page metadata object for framework.</description>
    <label>Page</label>
    <nameField>
        <label>FB_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/PGFSection__c.object-meta.xml
<CustomObject>
    <description>Section metadata object for framework.</description>
    <label>Section</label>
    <nameField>
        <label>FB_Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSection__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent page.</description>
    <label>Page</label>
    <referenceTo>PGFPage__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PageSectionTest.cls
@isTest
public class PageSectionTest {
    @testSetup 
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    }
    @IsTest
    static void pageSectionMethod(){
        system.runAs(new user(ID = UserInfo.getUserID())){
            PGFPage__c pgfP = new PGFPage__c();
            pgfP.Name = 'new Page';
            insert pgfP;
            
            PGFSection__c pgfS = new PGFSection__c();
            pgfS.Parent__c = pgfP.Id;
            pgfS.Name = 'new Section';
            pgfS.OrderNumber__c = 45;
            insert pgfS;
            
            Test.startTest();
            PageSection PS = new PageSection(pgfS,'Open');
            Test.stopTest();
            system.assertEquals(True, 1==1,'Testing');
        }
        
    } 
}