force-app/main/default/objects/PGFPage__c/PGFPage__c.object-meta.xml
<CustomObject>
    <description>Page metadata object for framework.</description>
    <label>Page</label>
    <nameField>
        <label>FB_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFPage__c/fields/Instructions_to_Application__c.field-meta.xml
<CustomField>
    <fullName>Instructions_to_Application__c</fullName>
    <description>Provide an instruction of the application</description>
    <inlineHelpText>Provide an instruction of the application</inlineHelpText>
    <label>Instructions to Application</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/PageTitle__c.field-meta.xml
<CustomField>
    <fullName>PageTitle__c</fullName>
    <description>Page Title</description>
    <label>Page Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/PageType__c.field-meta.xml
<CustomField>
    <fullName>PageType__c</fullName>
    <label>Page Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>News</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/ProgramRecordType__c.field-meta.xml
<CustomField>
    <fullName>ProgramRecordType__c</fullName>
    <description>Program Record Type</description>
    <label>Program Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFPage__c/fields/TransactionRecordType__c.field-meta.xml
<CustomField>
    <fullName>TransactionRecordType__c</fullName>
    <description>Transaction Record Type</description>
    <label>Transaction Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationInfo.cls
public class ApplicationInfo {
    public String Id {get; set;}
    public String PageTitle {get; set;}
    public String PageType {get; set;}
    public String TransactionRecordType {get; set;}
    public String ProgramRecordType {get; set;}
    public String Instructions_to_Application {get; set;}
    public List<PageSection> Sections {get; set;}

    public ApplicationInfo(PGFPage__c page){
        this.Id = String.valueOf(page.Id);
        this.PageTitle = page.PageTitle__c;
        this.PageType=page.PageType__c;
        this.TransactionRecordType=page.TransactionRecordType__c;
        this.ProgramRecordType=page.ProgramRecordType__c;
        this.Instructions_to_Application = page.Instructions_to_Application__c;

        this.Sections = new List<PageSection>();
    }
}