force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Approved_Total_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_Total_Capacity__c</fullName>
    <label>Approved Total Capacity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Calculated_Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Calculated_Maximum_Capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Maximum Capacity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Deny_Reasons__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Deny_Reasons__c</fullName>
    <label>Deny Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CLQ_Recommendation__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Enforcement</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Rehabilitation Standards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Full_Part_Time_Options_Global__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Full_Part_Time_Options_Global__c</fullName>
    <description>Serves renamed to Full/Part -Time Options</description>
    <label>Full/Part -Time Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLQ_Serves</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Recommendation__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Recommendation__c</fullName>
    <label>Recommendation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Deny</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Reviewer_Notes__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Reviewer_Notes__c</fullName>
    <label>Reviewer Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/CLQ_Transaction_Document__c.object-meta.xml
<CustomObject>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
                <default>true</default>
                <label>Attached</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/CLQ_Serves.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Full Time</fullName>
    </customValue>
    <customValue>
        <fullName>Part Time</fullName>
    </customValue>
    <masterLabel>Serves</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLQ_TransDocumentTriggerHandler_Test.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_TransDocumentTriggerHandler_Test
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest(isParallel=true)
private class CLQ_TransDocumentTriggerHandler_Test {
    @testSetup //Added for task - 11615
    public static void setExecuteControlSetting()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting();
    } 	
    @IsTest
    static void test_method_one() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_Program_Transaction__c progTrans = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'Application - FCC');
            progTrans.CLQ_Recommendation__c = 'Approve';
            progTrans.CLQ_Full_Part_Time_Options_Global__c = 'Full Time';
            progTrans.CLQ_Approved_Total_Capacity__c=3;
            progTrans.CLQ_Calculated_Maximum_Capacity__c=3;
            update progTrans;
            CLQ_Transaction_Document__c transDoc = new CLQ_Transaction_Document__c(CLQ_Document_Status__c ='Approved',CLQ_Program_Transaction__c =CLQ_UnitTestUtilities.ProgramTransactionId);
            insert transDoc;
            CLQ_Program_Transaction__c progTrans1 = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type A Home', 'Application - FCC');
            progTrans.CLQ_Recommendation__c = 'Deny';
            update progTrans1;
            CLQ_Transaction_Document__c transDoc1 = new CLQ_Transaction_Document__c(CLQ_Document_Status__c ='Denied',Id=transDoc.Id,CLQ_Program_Transaction__c=CLQ_UnitTestUtilities.ProgramTransactionId);
            update transDoc1;
            CLQ_Transaction_Document__c transDoc2 = new CLQ_Transaction_Document__c(CLQ_Document_Status__c ='Not Verified',Id=transDoc.Id,CLQ_Program_Transaction__c=CLQ_UnitTestUtilities.ProgramTransactionId);
            update transDoc2;
        }
    }
    
    @IsTest
    static void test_method_two() {
        system.assertEquals(True, 1==1,'Testing');
        system.runAs(new user(ID = UserInfo.getUserID())){
            CLQ_Program_Transaction__c progTrans = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type B Home', 'Application - FCC');
            progTrans.CLQ_Recommendation__c = 'Deny';
            progTrans.CLQ_Reviewer_Notes__c = 'Test Comments';
            progTrans.CLQ_Deny_Reasons__c = 'Not Applicable';
            //progTrans.CLQ_Full_Part_Time_Options_Global__c = 'Full Time';
            //progTrans.CLQ_Approved_Total_Capacity__c=3;
            //progTrans.CLQ_Calculated_Maximum_Capacity__c=3;
            update progTrans;
            CLQ_Transaction_Document__c transDoc = new CLQ_Transaction_Document__c(CLQ_Document_Status__c ='Approved',CLQ_Program_Transaction__c =CLQ_UnitTestUtilities.ProgramTransactionId);
            insert transDoc;
            CLQ_Program_Transaction__c progTrans1 = CLQ_UnitTestUtilities.TransactionCreation('FCC - Type A Home', 'Application - FCC');
            progTrans.CLQ_Recommendation__c = 'Deny';
            update progTrans1;
            CLQ_Transaction_Document__c transDoc1 = new CLQ_Transaction_Document__c(CLQ_Document_Status__c ='Denied',Id=transDoc.Id,CLQ_Program_Transaction__c=CLQ_UnitTestUtilities.ProgramTransactionId);
            update transDoc1;
            CLQ_Transaction_Document__c transDoc2 = new CLQ_Transaction_Document__c(CLQ_Document_Status__c ='Not Verified',Id=transDoc.Id,CLQ_Program_Transaction__c=CLQ_UnitTestUtilities.ProgramTransactionId);
            update transDoc2;
        }
    }
    
}