force-app/main/default/objects/CLQ_Findings__c/CLQ_Findings__c.object-meta.xml
<CustomObject>
    <label>Findings</label>
    <nameField>
        <displayFormat>Findings-{000000}</displayFormat>
        <label>Findings No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Findings__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Findings</relationshipLabel>
    <relationshipName>Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Findings__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Findings__c/fields/Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Findings</relationshipLabel>
    <relationshipName>Findings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Onsite_Rating__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Rating__c</fullName>
    <label>Onsite Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Child_Care_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Child_Care_Center</fullName>
    <active>true</active>
    <description>VDSS - Child Care Centers</description>
    <label>Child Care Center</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Pre_School.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Pre_School</fullName>
    <active>true</active>
    <description>ODE - PS (Pre-School)</description>
    <label>Pre School</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_School_Age_Child_Care.recordType-meta.xml
<RecordType>
    <fullName>CLQ_School_Age_Child_Care</fullName>
    <active>true</active>
    <description>ODE- SACC (School Age Child Care)</description>
    <label>School Age Child Care</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_Type_A_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Type_A_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type A Homes: 7 to 12</description>
    <label>FCC - Type A Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Standard_Detail__c/CLQ_Standard_Detail__c.object-meta.xml
<CustomObject>
    <label>Standard Detail</label>
    <nameField>
        <label>Standard Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/CLQ_Transaction_Document__c.object-meta.xml
<CustomObject>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
                <default>true</default>
                <label>Attached</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/CLQ_Standard_Detail_Document__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Standard_Detail_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard Detail Document</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CLQ_Standard_Detail__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Document</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CLQ_Standard_Detail__c</referenceTo>
    <relationshipLabel>Transaction Documents</relationshipLabel>
    <relationshipName>Transaction_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/Document_Points__c.field-meta.xml
<CustomField>
    <fullName>Document_Points__c</fullName>
    <label>Document Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Transaction_Document__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Document Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardFindingstoExclude__c/StandardFindingstoExclude__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Standard Findings to Exclude</label>
</CustomObject>

force-app/main/default/classes/CLQ_CalulateOnsiteVisitRatingCtrlLWC.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_CalulateOnsiteVisitRatingController 
** Description      : Controller for calculating onsite visit rating LWC
** Version          : 1.2
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer					Date				Version					Description
** Ankush R Relekar			  12/21/2021			  1.0					Initial Build (Controller for LWC component)

************************************************************************************/
public with sharing class CLQ_CalulateOnsiteVisitRatingCtrlLWC{
    
    public ID                                               inspectionId;
  	public static final String ONE = '1';
    public static final String TWO = '2';
    public static final String THREE = '3';
    public static final String FOUR = '4';
    public static final String FIVE = '5';
    public static final String D_LETTER = 'D';
    public static final String Message = 'Desk Review Rating success';
    
    public String calulateOnsiteVisitRating(string inspectionId){
    String redirectUrl;
    
    list<CLQ_Findings__c>                            listFindings;
    list<CLQ_Findings__c>                  listFindingswithPoints;
    list<CLQ_Transaction_Document__c>           listTransDocument;
    list<CLQ_Transaction_Document__c> listTransDocumentwithPoints;  
    Set<String> standardDetails                      = new Set<String>();
        string msg;
       try{
            //List we'll be updating
            List<CLQ_Inspection__c> inspectionToUpdate = new List<CLQ_Inspection__c>();
            
            //Static data declared for comparison to determine Onsite Rating (check nested if/else statements below)
            
            String preSchool = Schema.Sobjecttype.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Pre_School').getRecordTypeId();
            String fccTypeA  = Schema.Sobjecttype.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Type_A_Home').getRecordTypeId();
            String fccTypeB  = Schema.Sobjecttype.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
            String sacc      = Schema.Sobjecttype.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_School_Age_Child_Care').getRecordTypeId();
            String center    = Schema.Sobjecttype.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_Child_Care_Center').getRecordTypeId();
            
            Set<String> odeCenterSet = new Set<String>();
            odeCenterSet.add(preSchool);
            odeCenterSet.add(sacc);
            odeCenterSet.add(center);

            Set<String> fccTypeABSet = new Set<String>();
            fccTypeABSet.add(fccTypeB);
            fccTypeABSet.add(fccTypeA);
            //End static data declaration

            //Get Inspection id from page
            //inspectionId=ApexPages.currentPage().getParameters().get('id');
            //Query for inspection record
            CLQ_Inspection__c inspection;
           if(inspectionId!=null){
               inspection = [SELECT Id,Name 
                                            FROM CLQ_Inspection__c PT  
                                            WHERE Id = : inspectionId
                                           ];
           }
            
            //Extract from custom settings the Standard Findings to exclude

            List<StandardFindingstoExclude__c> sdToExclude = StandardFindingstoExclude__c.getall().values();
            if(sdToExclude != NULL){
                for(StandardFindingstoExclude__c  sd : sdToExclude){
                    standardDetails.add(sd.Name);
                }//end for loop
            }//end if
            
            //Get all inspections that have no Deferral ratings in associated findings
            Map<Id,CLQ_Inspection__c> mapInspection;
           	if(inspectionId!=null){
               	mapInspection = new Map<Id,CLQ_Inspection__c>([SELECT Id,CLQ_Program_Transaction__c,CLQ_Program__r.RecordTypeId,
                                                                                        (SELECT Id,Points__c,Rating__c 
                                                                                         FROM Findings__r 
                                                                                         WHERE Rating__c != 'D' 
                                                                                         AND Rating__c != null 
                                                                                         ORDER BY Rating__c asc) 
                                                                                    FROM CLQ_Inspection__c 
                                                                                    WHERE Id = : inspectionId
                                                                                    ]);
           	}
            
            //Get all the findings for this inspection
            if(mapInspection.size()!=0 && mapInspection.get(inspectionId).Findings__r != null){
                listFindings = mapInspection.get(inspectionId).Findings__r;
            }//end if
           	if(inspectionId!=null){
                listFindingswithPoints =  new List<CLQ_Findings__c>([SELECT Id,Points__c,Rating__c 
                                                                 FROM CLQ_Findings__c 
                                                                 WHERE Points__c != null 
                                                                 AND CLQ_Inspection__c =: inspectionId
                                                                ]);
           	}
            
            
            //13359 - Added where clause for CLQ_Document_Status__c for Not Verified 
            //13783 TODO: remove query since its from PT
            /*
            listTransDocument = new List<CLQ_Transaction_Document__c>([SELECT Id,Document_Points__c,Rating__c 
                                                                       FROM CLQ_Transaction_Document__c 
                                                                       WHERE  CLQ_Program_Transaction__c =: mapInspection.get(inspectionId).CLQ_Program_Transaction__c 
                                                                       AND Rating__c != null 
                                                                       AND CLQ_Document_Status__c != 'Not Verified'
                                                                       ORDER BY Rating__c asc
                                                                     ]);
			//13359 - Added where clause for CLQ_Document_Status__c for Not Verified 
			//13783 TODO: remove query since its from PT
            System.debug('@@@@@list of Document with Rating'+ listTransDocument);
            listTransDocumentwithPoints =  new List<CLQ_Transaction_Document__c>([SELECT Id,Document_Points__c,Rating__c 
                                                                                  FROM CLQ_Transaction_Document__c 
                                                                                  WHERE  CLQ_Standard_Detail_Document__r.Name IN :standardDetails 
                                                                                  AND Document_Points__c != null 
                                                                                  AND CLQ_Document_Status__c != 'Not Verified'
                                                                                  AND CLQ_Program_Transaction__c =: mapInspection.get(inspectionId).CLQ_Program_Transaction__c 
                                                                                ]);
            System.debug('@@@@list of Document with Points'+ listTransDocumentwithPoints);
            */
            
            Integer OnsiteVisitRating = 0;
            
            
        if(listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3 && listFindingswithPoints.size() !=0){
                    for(CLQ_Findings__c finding : listFindingswithPoints){
                        if(finding.Points__c != null){
                            OnsiteVisitRating = OnsiteVisitRating + Integer.valueOf(finding.Points__c);
                        }//end if
                    }//end for loop
                }//end if
                
                //13783 TODO: remove query since its from PT
                /*
                if(listTransDocumentwithPoints.size() >0){
                    for(CLQ_Transaction_Document__c transDoc : listTransDocumentwithPoints){
                        if(transDoc.Document_Points__c != null){
                            OnsiteVisitRating = OnsiteVisitRating + Integer.valueOf(transDoc.Document_Points__c);
                        }//end if
                    }//end for loop
                }//end if
                */
                if((listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3) && (mapInspection.size()!=0 && OnsiteVisitRating >=35 && OnsiteVisitRating <= 55 && odeCenterSet.contains(String.valueOf(mapInspection.get(inspectionId).CLQ_Program__r.RecordTypeId)))){
                    inspection.Onsite_Rating__c = FOUR;
                    //System.debug('(Center/ODE) DomainRating expected is 4, my value is = ' + OnsiteVisitRating);
                                                                             
                }//end if 
                else if((listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3) && (mapInspection.size()!=0 && OnsiteVisitRating > 55 && odeCenterSet.contains(String.valueOf(mapInspection.get(inspectionId).CLQ_Program__r.RecordTypeId)))){
	
                    inspection.Onsite_Rating__c = FIVE;
                }//end else if
                else if((listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3) && (mapInspection.size()!=0 && OnsiteVisitRating >=30 && OnsiteVisitRating <= 45 && fccTypeABSet.contains(String.valueOf(mapInspection.get(inspectionId).CLQ_Program__r.RecordTypeId)))){
                    inspection.Onsite_Rating__c = FOUR;
                   }//end else if
                else if((listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3) && (mapInspection.size()!=0 && OnsiteVisitRating > 45 && fccTypeABSet.contains(String.valueOf(mapInspection.get(inspectionId).CLQ_Program__r.RecordTypeId)))){
                    
                    inspection.Onsite_Rating__c = FIVE;
               }//end else if
                else if ((listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3) && (mapInspection.size()!=0 && OnsiteVisitRating < 30 && fccTypeABSet.contains(String.valueOf(mapInspection.get(inspectionId).CLQ_Program__r.RecordTypeId)))){
                    inspection.Onsite_Rating__c = THREE;
              }//end else if
                
                else if ((listFindings.size()!=0 && Integer.valueOf(listFindings.get(0).Rating__c ) == 3) && (mapInspection.size()!=0 && OnsiteVisitRating < 35 && odeCenterSet.contains(String.valueOf(mapInspection.get(inspectionId).CLQ_Program__r.RecordTypeId)))){
                    inspection.Onsite_Rating__c = THREE;
           }//end else if
     
            else{
                //Only set the OnsiteVisitRating value to the Findings value if it doensn't have a value of 'D'
                if(listFindings.size()!=0 && listFindings.get(0).Rating__c != D_LETTER){
                    OnsiteVisitRating = Integer.valueOf(listFindings.get(0).Rating__c );
                    inspection.Onsite_Rating__c = String.valueOf(OnsiteVisitRating);
                }//end if
            }//end else
            
            inspectionToUpdate.add(inspection);
            
            try{
                if(inspectionToUpdate != null && inspectionToUpdate.size() != 0){
                    update inspectionToUpdate;
                    msg = Message;
                }//end if
            }//end try
            catch(Exception e){
            //If DML operation fails, catch exception and show on ApexPage
                //System.debug('Exception: '   + e);
                //System.debug('Cause: '       + e.getCause());
                //System.debug('Line Number: ' + e.getLineNumber());
                //System.debug('Stack Trace: ' + e.getStackTraceString());
                msg='error from ctrl in update:'+e;
                //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));

            }//end catch
            
            //redirecturl ='/'+inspectionId;
            //pageReference newpage=new pagereference(redirecturl);
            //newpage.setRedirect(true);
            //return newpage;
        }//end try
        catch(Exception e){
        //If there's a breakage in the method, catch exception and show on ApexPage
            //System.debug('Exception: '   + e);
            //System.debug('Cause: '       + e.getCause());
            //System.debug('Line Number: ' + e.getLineNumber());
            //System.debug('Stack Trace: ' + e.getStackTraceString());
            msg= 'error from ctrl:'+e;
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            //return null;
        }//end catch
        return msg;
    }//end method
    
}//end class