force-app/main/default/objects/PGFSubSection__c/PGFSubSection__c.object-meta.xml
<CustomObject>
    <description>Sub-section metadata object for framework.</description>
    <label>Sub-Section</label>
    <nameField>
        <label>FB_SubSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Field_Labels__c</fullName>
    <label>Applicable Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Form_Field_Labels__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Form_Field_Labels__c</fullName>
    <label>Applicable Form Field Labels</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Applicable_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Record_Type__c</fullName>
    <label>Applicable Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFields__c</fullName>
    <description>Applicable Fields</description>
    <label>Applicable Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableFormFields__c.field-meta.xml
<CustomField>
    <fullName>ApplicableFormFields__c</fullName>
    <description>Applicable Form Fields</description>
    <label>Applicable Form Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ApplicableObject__c.field-meta.xml
<CustomField>
    <fullName>ApplicableObject__c</fullName>
    <description>Applicable Object</description>
    <label>Applicable Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/ComponentAPIName__c.field-meta.xml
<CustomField>
    <fullName>ComponentAPIName__c</fullName>
    <description>Choose which component to add.</description>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TableComponent</fullName>
                <default>true</default>
                <label>Table Component</label>
            </value>
            <value>
                <fullName>FileUpload</fullName>
                <label>File Upload</label>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/IsATextBlockType__c.field-meta.xml
<CustomField>
    <fullName>IsATextBlockType__c</fullName>
    <formula>ISPICKVAL(Type__c,&quot;Textblock&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsATextBlockType?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent section</description>
    <label>Section</label>
    <referenceTo>PGFSection__c</referenceTo>
    <relationshipLabel>Sub Sections</relationshipLabel>
    <relationshipName>Sub_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/QueryWhereClause__c.field-meta.xml
<CustomField>
    <fullName>QueryWhereClause__c</fullName>
    <description>Query Where Clause</description>
    <label>Query Where Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/TextBlockBody__c.field-meta.xml
<CustomField>
    <fullName>TextBlockBody__c</fullName>
    <description>Text Block Body</description>
    <label>Text Block Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PGFSubSection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Sub-section type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fieldset</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Textblock</fullName>
            </value>
            <value>
                <fullName>Hidden Fieldset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PageSubSection.cls
public class PageSubSection {
    public String Id {get; set;}
    public Decimal OrderNumber {get; set;}
    public String Type {get; set;}
    public String ComponentType {get; set;}
    public Boolean IsATextBlockType {get; set;}
    public String TextBlockBody {get; set;}
    public String Label {get; set;}
    public String ObjectName {get; set;}
    public String LookupObjectName {get; set;}
    public List<FormComponent> FormComponents {get; set;}
    public String RecordType {get; set;}
    public List<FormComponent> TableInfo {get; set;}
    public String WhereClause {get; set;}
    public String Section {get; set;}
    public list<sobject> lstObjs {get;set;}

    public List<PageField> Fields {get; set;}

    public PageSubSection(PGFSubSection__c subSection, string language){
        this.Id = String.valueOf(subSection.Id);
        this.OrderNumber = subSection.OrderNumber__c;
        this.Label = subSection.Label__c;
        this.Type = subSection.Type__c;
        this.IsATextBlockType = subSection.IsATextBlockType__c;
        this.TextBlockBody = subSection.TextBlockBody__c;
        this.Section = String.valueOf(subSection.Parent__c);
        this.ComponentType = subSection.ComponentAPIName__c;
        
        if(subSection.Type__c == 'Component'){
            this.ObjectName = subSection.ApplicableObject__c;
            this.LookupObjectName = subSection.Lookup_Object__c;
            this.RecordType = subSection.Applicable_Record_Type__c;
            this.WhereClause = subSection.QueryWhereClause__c;

            List<String> formLabels = subSection.Applicable_Form_Field_Labels__c != null ? subSection.Applicable_Form_Field_Labels__c.split(';') : new List<String>{};
            List<String> formFields = subSection.ApplicableFormFields__c != null ? subSection.ApplicableFormFields__c.split(';') : new List<String>{};
            this.FormComponents = new List<FormComponent>();

            for(Integer i = 0; i < formLabels.size(); i++){
                FormComponent formCmp = new FormComponent();
                formCmp.Label = formLabels[i];
                formCmp.FieldName = formFields[i];

                this.FormComponents.add(formCmp);
            }

            List<String> tableLabels = subSection.Applicable_Field_Labels__c != null ? subSection.Applicable_Field_Labels__c.split(';') : new List<String>{};
            List<String> tableFields = subSection.ApplicableFields__c != null ? subSection.ApplicableFields__c.split(';') : new List<String>{};

            this.TableInfo = new List<FormComponent>();

            for(Integer i = 0; i < tableLabels.size(); i++){
                FormComponent formCmp = new FormComponent();
                formCmp.Label = tableLabels[i];
                formCmp.FieldName = tableFields[i];

                this.TableInfo.add(formCmp);
            }
        }
        this.Fields = new List<PageField>();
    }

    public class FormComponent {
        public String Label {get; set;}
        public String FieldName {get; set;}
    }
}