force-app/main/default/objects/PGFField__c/PGFField__c.object-meta.xml
<CustomObject>
    <description>Fields metadata object for framework.</description>
    <label>Field</label>
    <nameField>
        <label>FB_Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGFField__c/fields/Copy_Options__c.field-meta.xml
<CustomField>
    <fullName>Copy_Options__c</fullName>
    <label>Copy Options</label>
    <length>50768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/CSSClasses__c.field-meta.xml
<CustomField>
    <fullName>CSSClasses__c</fullName>
    <label>CSS Classes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label</description>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <description>Object API name</description>
    <label>ObjectAPIName</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>CLQ_Program__c</fullName>
            </value>
            <value>
                <fullName>CLQ_Program_Transaction__c</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>CLQ_Role__c</fullName>
            </value>
            <value>
                <fullName>CLQ_Facility_Schedule__c</fullName>
            </value>
            <value>
                <fullName>CLQ_Room_Space__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Order Number</description>
    <label>Order Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Parent sub-section</description>
    <label>Sub-Section</label>
    <referenceTo>PGFSubSection__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Pattern__c.field-meta.xml
<CustomField>
    <fullName>Pattern__c</fullName>
    <description>Set Pattern for validation</description>
    <label>Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Pattern_Mismatch_Message__c.field-meta.xml
<CustomField>
    <fullName>Pattern_Mismatch_Message__c</fullName>
    <label>Pattern Mismatch Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Read-Only</description>
    <label>Read-Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Required</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multi-Select</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>TextArea</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGFField__c/fields/Validator__c.field-meta.xml
<CustomField>
    <fullName>Validator__c</fullName>
    <description>UI Validation</description>
    <label>Validator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Text-Only</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Zip</fullName>
            </value>
            <value>
                <fullName>PhoneExtn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PageField.cls
public with sharing class PageField {
    public String Id {get; set;}
    public Decimal OrderNumber {get; set;}
    public String Type {get; set;}
    public String Label {get; set;}
    public Boolean Required {get; set;}
    public Boolean ReadOnly {get; set;}
    public String Validator {get; set;}
    public String CSSClasses {get; set;}
    public String ObjectApi {get; set;}
    public String Value {get; set;}
    public String FieldApi {get; set;}
    public String SubSection {get; set;}
    public String Label_Lang {get; set;}
    public String language {get; set;}
    public String Pattern {get; set;}
    public String Pattern_Mismatch_Message {get; set;}
    public String copy_options {get; set;}
    //public List<String> PicklistValues {get; set;}
    public List<Map<String, String>> PicklistValues {get; set;}
    
    public PageField(PGFField__c pageField, String sValue, string language) {
        this.Id = String.valueOf(pageField.Id);
        this.OrderNumber = pageField.OrderNumber__c;
        this.Label = pageField.Label__c;
        this.Type = pageField.Type__c;
        this.Required = pageField.Required__c;
        this.ReadOnly = pageField.ReadOnly__c;
        this.Validator = pageField.Validator__c;
        this.CSSClasses = pageField.CSSClasses__c;
        this.SubSection = pageField.Parent__c;
        this.ObjectApi = pageField.ObjectAPIName__c;
        this.FieldApi = pageField.Name;
        this.Value= sValue;
        this.language=language;
        this.Label_Lang =pageField.Label__c;
        this.Pattern=pageField.Pattern__c;
        this.Pattern_Mismatch_Message=pageField.Pattern_Mismatch_Message__c;
        this.copy_options=pageField.Copy_Options__c;
        
        /*if(this.language=='German'){
            if(!String.isBlank(pageField.German__c)){
                this.Label=pageField.German__c;
                this.Label_Lang=pageField.German__c;
            }
        }
        else if(this.language=='Spanish'){
            if(!String.isBlank(pageField.Spanish__c)){
                this.Label=pageField.Spanish__c;
                this.Label_Lang=pageField.Spanish__c;
            }
        }
        else{
            this.Label=pageField.Label__c;
            this.Label_Lang=pageField.Label__c;
        }*/
        
        if(pageField.Type__c == 'Picklist' || pageField.Type__c == 'Multi-Select'){
            this.PicklistValues = GetPickListValues(pageField.ObjectAPIName__c, pageField.Name);  
        }else{
            //this.PicklistValues = new List<String>();
        }
    }
    
    /**
* Used to obtain picklist values of a field
* 
* @param objName - Name of the SObject Ex: Account, Category__c
* @param fieldName - API name of the field
* 
* @return List<String> - List of picklist values
*/
    private List<Map<String, String>> GetPickListValues(String objName, String fieldName){
        
        List<Map<String, String>> values = new List<Map<String, String>>();
        
        try{
            Schema.SObjectType objType = Schema.getGlobalDescribe().get(objName);
            Schema.DescribeSobjectResult objTypeDesc = objType.getDescribe();
            Map<String,Schema.SObjectField> fields = objTypeDesc.fields.getMap() ;
            Schema.DescribeFieldResult fieldResult = fields.get(fieldName).getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for( Schema.PicklistEntry pickListVal : ple){
                //values.add(pickListVal.getValue());
                Map<String, String> optionsMap = new Map<String, String>();
                
                optionsMap.put('label',pickListVal.getValue());
                optionsMap.put('value',pickListVal.getValue());
                values.add(optionsMap);
            }
        }
        catch(Exception ex){
            throw new DMLException('Could not find specified object / field');
        }
        
        return values;
    }
}