force-app/main/default/objects/CLQ_Alleged_Rule_Violation__c/CLQ_Alleged_Rule_Violation__c.object-meta.xml
<CustomObject>
    <description>Rules that apply to the programs</description>
    <label>Alleged Rule Violation</label>
    <nameField>
        <displayFormat>ARV-{00000000}</displayFormat>
        <label>Alleged Rule Violation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alleged Rule Violations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Alleged_Rule_Violation__c/fields/CLQ_Domain_Rule__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Domain_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Domain Rule</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>NOT (1)</booleanFilter>
        <filterItems>
            <field>CLQ_Domain_Rule__c.CLQ_Domain__r.Name</field>
            <operation>startsWith</operation>
            <value>Conversion</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CLQ_Domain_Rule__c</referenceTo>
    <relationshipLabel>Alleged Rule Violations</relationshipLabel>
    <relationshipName>Alleged_Rule_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Alleged_Rule_Violation__c/fields/CLQ_Rule_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Rule_Effective_Date__c</fullName>
    <description>Used in custom look up search</description>
    <label>Rule Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Domain__c/CLQ_Domain__c.object-meta.xml
<CustomObject>
    <description>Object to store the domain information for inspection rules</description>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Domain_Rule__c/CLQ_Domain_Rule__c.object-meta.xml
<CustomObject>
    <description>Junction object between Rules and Domain</description>
    <label>Domain Rule</label>
    <nameField>
        <displayFormat>DR#-{000000}</displayFormat>
        <label>Domain Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Domain Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Domain_Rule__c/fields/CLQ_ApplicableTo_Txt__c.field-meta.xml
<CustomField>
    <fullName>CLQ_ApplicableTo_Txt__c</fullName>
    <description>Text field to hold Applicable To values. Used in look up search</description>
    <label>Applicable To</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CLQ_Domain_Rule__c/fields/CLQ_Domain__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Domain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Domain</label>
    <referenceTo>CLQ_Domain__c</referenceTo>
    <relationshipLabel>Domain Rules</relationshipLabel>
    <relationshipName>Domain_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Domain_Rule__c/fields/CLQ_Rule__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rule</label>
    <referenceTo>CLQ_Rule__c</referenceTo>
    <relationshipLabel>Domain Rules</relationshipLabel>
    <relationshipName>Domain_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Domain_Rule__c/fields/CLQ_Rule_Number__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Rule_Number__c</fullName>
    <formula>CLQ_Rule__r.CLQ_Rule_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rule Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Rule__c/CLQ_Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Rule__c/fields/CLQ_Domain__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Domain__c</fullName>
    <label>Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staff Files (FT)</fullName>
            </value>
            <value>
                <fullName>Written Policies &amp; Procedures(FT)</fullName>
            </value>
            <value>
                <fullName>Indoor-Outdoor Space(FT)</fullName>
            </value>
            <value>
                <fullName>Health &amp; Safety (FT)</fullName>
            </value>
            <value>
                <fullName>Safe &amp; Sanitary Envt (RST)</fullName>
            </value>
            <value>
                <fullName>Program Info(FT)</fullName>
            </value>
            <value>
                <fullName>Children&apos;s Files (FT)</fullName>
            </value>
            <value>
                <fullName>Postings &amp; Equipment (RST)</fullName>
            </value>
            <value>
                <fullName>Ratio Info (FT)</fullName>
            </value>
            <value>
                <fullName>Observations (RST)</fullName>
            </value>
            <value>
                <fullName>License &amp; Approvals(FT)</fullName>
            </value>
            <value>
                <fullName>Diapering &amp; InfantCare(FT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Rule__c/fields/CLQ_Rule_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Rule_Effective_Date__c</fullName>
    <label>Rule Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Rule__c/fields/CLQ_Rule_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Rule_Expiration_Date__c</fullName>
    <label>Rule Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Rule__c/fields/CLQ_Rule_Number__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Rule_Number__c</fullName>
    <label>Rule Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Rule__c/fields/CLQ_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Short_Name__c</fullName>
    <label>Short Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CLQ_DomainRuleLookupSearchController.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CCLQ_DomainRuleLookupSearchController
** Description      : CLQ_DomainRuleLookupSearch Page Controller
** Version          : 1.0
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer           Date                Version         Description
**  Neetu Ojha          11/08/2017          1.0             TFS#11415 : Initial Version 
**************************************************************************************************************/

public with sharing class CLQ_DomainRuleLookupSearchController{
	public CLQ_Alleged_Rule_Violation__c arvObject{get;set;}
	public String domainRuleName {get;set;}
	public String domainName {get;set;}
	public String ruleShortName {get;set;}	
	public String ruleNumber {get;set;}
	public String applicableTo {get;set;}
	public integer totalRecs{get;set;}
	public static final string EMPTY = '';
	List<string> conditions = new List<string>();
	
	private integer offsetSize = 0;
	private integer limitSize = Integer.valueOf(Label.LookUpSearch_RowSize);

	public CLQ_DomainRuleLookupSearchController(){
		arvObject = new CLQ_Alleged_Rule_Violation__c();
 		totalRecs = 0;
 		domainRuleName = system.currentPageReference().getParameters().get('lksrch');
 		
 		if(domainRuleName != null && domainRuleName != EMPTY){
 			searchDomainRule();
 		}
	}
  	
  	// used by the visualforce page to send the link to the right dom element
  	public string getFormTag() {
    	return system.currentPageReference().getParameters().get('frm');
  	}

  	// used by the visualforce page to send the link to the right dom element for the text box
  	public string getTextBox() {
    	return system.currentPageReference().getParameters().get('txt');
  	}	

	public void searchDomainRule(){
		totalRecs = 0;
		offsetSize = 0;
	}

	//Method to get all fields from field set
	private List<Schema.FieldSetMember> getFields() {
        return SObjectType.CLQ_Domain_Rule__c.FieldSets.LookUpSearchFS.getFields();
    }
    
    //Method to form query
    private string formBasicQuery(){
    	String strQuery = 'SELECT ';
    	conditions.clear();
    	
        for(Schema.FieldSetMember f : this.getFields()) {
            strQuery += f.getFieldPath() + ', ';
        }
        strQuery += 'Id FROM CLQ_Domain_Rule__c';
        
        conditions.add('(NOT CLQ_Domain__r.Name Like \'Conversion%\')');
        conditions.add('(CLQ_Rule_Expiration_Date__c = null OR CLQ_Rule_Expiration_Date__c >= TODAY)');
        conditions.add('(CLQ_Rule_Effective_Date__c = null OR CLQ_Rule_Effective_Date__c <= TODAY)');
        
        return strQuery;
    }
    
    //To get the list of Domain Rule
    public List<CLQ_Domain_Rule__c> getLstDomainRule(){
    	String strQuery = formBasicQuery();
		
		if(domainRuleName != EMPTY && domainRuleName != null){
        	conditions.add('Name Like \'%' +domainRuleName +'%\'');
        }
        
        if(domainName != EMPTY && domainName != null){
        	conditions.add('CLQ_Domain__r.Name Like \'%' +domainName +'%\'');
        }
        
        if(ruleShortName != EMPTY && ruleShortName != null){
        	conditions.add('CLQ_Rule__r.CLQ_Short_Name__c Like \'%' +ruleShortName +'%\'');
        }
         
        if(ruleNumber != EMPTY && ruleNumber != null){
        	conditions.add('CLQ_Rule__r.CLQ_Rule_Number__c Like \'%' +ruleNumber +'%\'');
        }
         
        if(applicableTo != EMPTY && applicableTo != null){
        	conditions.add('CLQ_ApplicableTo_Txt__c Like \'%' +applicableTo +'%\'');
        } 

        if(arvObject.CLQ_Rule_Effective_Date__c != null){
        	String strDt = arvObject.CLQ_Rule_Effective_Date__c+'';
        	conditions.add('CLQ_Rule_Effective_Date__c =' +strDt.split(' ',0)[0]);
        } 
		
		if (conditions.size() > 0) {
			strQuery += '  WHERE ' + conditions[0];
			for (Integer i = 1; i < conditions.size(); i++)
				strQuery += '  AND ' + conditions[i];
		}

		List<CLQ_Domain_Rule__c> domainRuleTemp = Database.query(strQuery);
		totalRecs = (domainRuleTemp !=null && domainRuleTemp.size()>0)?domainRuleTemp.size():0;
		
		strQuery += ' ORDER BY Name ASC LIMIT :LimitSize OFFSET :offsetSize';
		
		system.debug('strQuery ==>'+strQuery );
		
		return Database.query(strQuery);    	
    }

	//Pagination Starts
	public void firstPage(){
        offsetSize = 0;
    }
    
	public void previous(){
        offsetSize = offsetSize - limitSize;
    }
    
    public void next(){
        offsetSize = offsetSize + limitSize;
    }

    public void lastPage(){
        offsetSize = totalrecs - math.mod(totalRecs,limitSize);
    }        
    
    public boolean getprev(){
        if(offsetSize == 0) {return true;}
        else{
            return false; 
        } 
    }  
    
    public boolean getnxt() {
        if((offsetSize + limitSize) > totalRecs) {return true;}
        else{
            return false;
        } 
    }
    //Pagination Ends
}