force-app/main/default/objects/CAPQuickActionController__mdt/CAPQuickActionController__mdt.object-meta.xml
<CustomObject>
    <label>CAP QuickAction Controller</label>
    <pluralLabel>CAP QuickAction Controllers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/CLQ_Corrective_Action_Plan__c.object-meta.xml
<CustomObject>
    <description>This object links Inspection and Findings</description>
    <label>Corrective Action Plan</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Corrective Action No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corrective Action Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_CAP_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_CAP_Status__c</fullName>
    <label>CAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed - Not Addressed</fullName>
            </value>
            <value>
                <fullName>Report Revised - Not Required</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>CAP Revised</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Corrective_Action_Plan__c/fields/CLQ_Reviewer_Comments__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Reviewer_Comments__c</fullName>
    <label>Reviewer Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CAPQuickActionController.cls
public with sharing class CAPQuickActionController implements IRequest{
    public static final string updateCAPonQuickActionClickString = 'updateCAPonQuickActionClick';
    public static final string Approve = 'Approve';
    public static final string Deny = 'Deny';
    public static final string Not_Required = 'Not_Required';
    public static final string ReturnRev = 'ReturnRev';
    public static final string Approved = 'Approved';
    public static final string Report_Revised_Not_Required = 'Report_Revised_Not_Required';
    public static final string Closed_Not_Addressed = 'Closed_Not_Addressed';
    public static final string Returned_for_Revision = 'Returned for Revision';
    public static final string Invalid_method_name = 'Invalid method name';
    public static final string boolStatus = 'boolStatus';
    public static final string boolReviewerCommAdded = 'boolReviewerCommAdded';
    public static final string StringTrue = 'true';
    public static final string StringFalse = 'false';
	public static final String EMPTY_STRING = '';    
    public static Map<String,Object> mapAssign = new Map<String,Object>();
    
    public static Map<String, String> capMetadataValueMap = new  Map<String, String>();
    
    public JsonResponse validate(String methodName, String jsonParam) {
        JsonResponse response = null;
        
        try {
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
            
            if(capMetadataValueMap.size()!=0 && methodName == capMetadataValueMap.get(updateCAPonQuickActionClickString)) {
                response = updateCAPonQuickActionClick(jsonParam,jsonParam);
            }  else {
                response = new JsonResponse();
                response.status = RequestStatus.ERROR;
                response.data = new Map<String, Object>();
                response.errors = new List<String>();
                response.errors.add(Invalid_method_name);
            }
            
        } catch(Exception ex) {
            response = new JsonResponse();
            response.status = RequestStatus.ERROR;
            response.data = new Map<String, Object>();
            response.errors = new List<String>();
            response.errors.add(ex.getMessage());
        }
        
        return response;
    }
    
    public JsonResponse processRequest(String methodName, String jsonParam) {
        JsonResponse response;
        
        try {
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
            if(capMetadataValueMap.size()!=0 && methodName == capMetadataValueMap.get(updateCAPonQuickActionClickString)) {
                response = updateCAPonQuickActionClick(jsonParam,jsonParam);
            }  else {
                response = new JsonResponse();
                response.status = RequestStatus.ERROR;
                response.data = new Map<String, Object>();
                response.errors = new List<String>();
                response.errors.add(Invalid_method_name);
            }
        } catch(Exception ex){
            response = new JsonResponse();
            response.status = RequestStatus.ERROR;
            response.data = new Map<String, Object>();
            response.errors = new List<String>();
            response.errors.add(ex.getMessage());
        }
        
        return response;
    }
    @AuraEnabled
    public static JsonResponse updateCAPonQuickActionClick(String strRecordId,String strQuickAction){
        JsonResponse response;
        system.debug('strRecordId=='+strRecordId);
        
        system.debug('str--'+strRecordId);
        system.debug('strQuickAction--'+strQuickAction);
        Boolean boolStatusChanged = false;
        //  CAPWrapper objCAPMain = new CAPWrapper();
        CLQ_Corrective_Action_Plan__c objCAP;
        try {
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
            if(strRecordId != null) {
                objCAP = [SELECT Id,CLQ_CAP_Status__c,CLQ_Reviewer_Comments__c FROM CLQ_Corrective_Action_Plan__c where Id=:strRecordId];
                system.debug('objCAP=='+objCAP);
                if(capMetadataValueMap.size()!=0 && strQuickAction == capMetadataValueMap.get(Approve)) {
                    response = approveCAP(objCAP);
                } else if(capMetadataValueMap.size()!=0 && strQuickAction == capMetadataValueMap.get(Deny)) {
                    response = DenyCAP(objCAP);
                } else if(capMetadataValueMap.size()!=0 && strQuickAction == capMetadataValueMap.get(Not_Required)) {
                    response = NotRequiredCAP(objCAP);
                } else if(capMetadataValueMap.size()!=0 && strQuickAction == capMetadataValueMap.get(ReturnRev)) {
                    response = ReturnRevCAP(objCAP);
                }                               
            }
            system.debug('resp=='+response);
        } catch (Exception ex) {
            system.debug('e'+ex);
            throw new AuraHandledException(ex.getMessage());
        }
        
        return response;
    }
    
    public static JsonResponse approveCAP(CLQ_Corrective_Action_Plan__c objCAPlan){                     
        try {           
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
            JsonResponse response = new JsonResponse();  
            if(capMetadataValueMap.size()!=0 && objCAPlan.CLQ_CAP_Status__c != capMetadataValueMap.get(Approved)) {
                objCAPlan.CLQ_CAP_Status__c = capMetadataValueMap.get(Approved);
                if(objCAPlan!=null){
                    update objCAPlan;
                }
                
                mapAssign.put(boolStatus, StringTrue);
                response.data = mapAssign; 
            }  else {
                mapAssign.put(boolStatus, StringFalse);
                response.data = mapAssign;
            }
            system.debug('responseApp=='+response);
            return response;
        } catch(Exception ex) {
            system.debug('ex==0'+ex.getMessage());
            JsonResponse response = new JsonResponse();
            response.status = RequestStatus.UNKNOWN_ERROR;
            response.data = null;
            response.errors = new List<String>();
            response.errors.add(ex.getStackTraceString() + ' ' + ex.getLineNumber());
            return response;
        }                
    }
    
    public static JsonResponse NotRequiredCAP(CLQ_Corrective_Action_Plan__c objCAPlan){
        try { 
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
            JsonResponse response = new JsonResponse();  
            if(objCAPlan.CLQ_Reviewer_Comments__c == EMPTY_STRING || objCAPlan.CLQ_Reviewer_Comments__c == null) {
                mapAssign.put(boolReviewerCommAdded, StringFalse);
                response.data = mapAssign;             
            } else if(capMetadataValueMap.size()!=0 && objCAPlan.CLQ_CAP_Status__c != capMetadataValueMap.get(Report_Revised_Not_Required)) {
                objCAPlan.CLQ_CAP_Status__c = capMetadataValueMap.get(Report_Revised_Not_Required);
                if(objCAPlan!=null){
                    update objCAPlan;
                }
                mapAssign.put(boolStatus, StringTrue);
                mapAssign.put(boolReviewerCommAdded, StringTrue);
                response.data = mapAssign;
            } else {
                mapAssign.put(boolReviewerCommAdded, StringTrue);
                response.data = mapAssign;
            }
            return response;
        } catch(Exception ex) {
            JsonResponse response = new JsonResponse();
            response.status = RequestStatus.UNKNOWN_ERROR;
            response.data = null;
            response.errors = new List<String>();
            response.errors.add(ex.getStackTraceString() + ' ' + ex.getLineNumber());
            return response;
        } 
    }
    
    public static JsonResponse DenyCAP(CLQ_Corrective_Action_Plan__c objCAPlan){
        try {
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }
            JsonResponse response = new JsonResponse();  
            if(objCAPlan.CLQ_Reviewer_Comments__c == EMPTY_STRING || objCAPlan.CLQ_Reviewer_Comments__c == null) {
                mapAssign.put(boolReviewerCommAdded, StringFalse);
                response.data = mapAssign;
            } else if(capMetadataValueMap.size()!=0 && objCAPlan.CLQ_CAP_Status__c != capMetadataValueMap.get(Closed_Not_Addressed)) {
                objCAPlan.CLQ_CAP_Status__c = capMetadataValueMap.get(Closed_Not_Addressed);
                if(objCAPlan!=null){
                    update objCAPlan;
                }
                mapAssign.put(boolStatus, StringTrue);
                mapAssign.put(boolReviewerCommAdded, StringTrue);
                response.data = mapAssign;
            }else {
                mapAssign.put(boolReviewerCommAdded, StringTrue);
                response.data = mapAssign;
            }
            return response;
        } catch(Exception ex) {
            JsonResponse response = new JsonResponse();
            response.status = RequestStatus.UNKNOWN_ERROR;
            response.data = null;
            response.errors = new List<String>();
            response.errors.add(ex.getStackTraceString() + ' ' + ex.getLineNumber());
            return response;
        } 
    }
    
    public static JsonResponse ReturnRevCAP(CLQ_Corrective_Action_Plan__c objCAPlan){
        try { 
            for(CAPQuickActionController__mdt mdt : [Select label,QualifiedApiName from CAPQuickActionController__mdt]){
                capMetadataValueMap.put(mdt.QualifiedApiName,mdt.label);
            }           
            JsonResponse response = new JsonResponse();  
            if(objCAPlan.CLQ_Reviewer_Comments__c == EMPTY_STRING || objCAPlan.CLQ_Reviewer_Comments__c == null) {            
                mapAssign.put(boolReviewerCommAdded, StringFalse);
                response.data = mapAssign;
            } else if(capMetadataValueMap.size()!=0 && objCAPlan.CLQ_CAP_Status__c != capMetadataValueMap.get(Returned_for_Revision)) {
                objCAPlan.CLQ_CAP_Status__c = capMetadataValueMap.get(Returned_for_Revision);
                if(objCAPlan!=null){
                    update objCAPlan;
                }
                mapAssign.put(boolStatus, StringTrue);
                mapAssign.put(boolReviewerCommAdded, StringTrue);
                response.data = mapAssign;
            } else {
                mapAssign.put(boolReviewerCommAdded, StringTrue);
                response.data = mapAssign;
            }
            return response;
        } catch(Exception ex) {
            JsonResponse response = new JsonResponse();
            response.status = RequestStatus.UNKNOWN_ERROR;
            response.data = null;
            response.errors = new List<String>();
            response.errors.add(ex.getStackTraceString() + ' ' + ex.getLineNumber());
            return response;
        } 
    }
    
}