force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-license</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Incident / Injury / Illness</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Amendment - change of location</fullName>
            </value>
            <value>
                <fullName>Amendment - change of capacity</fullName>
            </value>
            <value>
                <fullName>Initial Registration</fullName>
            </value>
            <value>
                <fullName>Ongoing Registration</fullName>
            </value>
            <value>
                <fullName>Technical Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Last_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Last_Visit_Date__c</fullName>
    <description>The date stamp when we complete the visit. Initially it is being used in CAP</description>
    <label>Last Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Original_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Original_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Associated Inspections (Follow-Ups)</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Last_Inspection_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Last_Inspection_Date__c</fullName>
    <description>Track the last inspection visit date from Annual, Provisional and Compliance inspections</description>
    <label>Last Inspection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CLQ_UpdateProgramInspectionDate.cls
/* 
** Name: CLQ_UpdateProgramInspectionDate
** Description: Used in PB: Update_PT_status_from_inspection_status / Update Program based on Inspection and CLQ_InspectionTriggerHandler
** 
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version         Description
**  Soufin Rahimeen         9/21/2018       1.1             TFS : 13857 - Re-wrote logic to get the latest Last Visit Date from Inspection and display that on Program's Last Inspection Date
**  Pradeep Ravi            8/21/2019       1.2             TFS : 15786 - Updated the status of the inspection 
**************************************************************************************************************/
public with sharing class CLQ_UpdateProgramInspectionDate {
    
    //13857 this can be called by both methods
    public static void updateProgramsFromProgramList(List<CLQ_Program__c> programsToCheck) {
    	
    	try{
    		
    		List<CLQ_Program__c> progLstToUpdate = new List<CLQ_Program__c>();

            Boolean updated = false; //has the prog been updated

            for(CLQ_Program__c prog : programsToCheck) { //go through all the programs
                if(prog.Inspections__r.isEmpty()) { //if no inspections exist

                    prog.CLQ_Last_Inspection_Date__c = null;
                    progLstToUpdate.add(prog);
                    }
                else {
                    for(CLQ_Inspection__c ins : prog.Inspections__r) { //else get the first in list and set
                        if(updated ==false && ins.CLQ_Last_Visit_Date__c != null) {

                            prog.CLQ_Last_Inspection_Date__c = ins.CLQ_Last_Visit_Date__c;
                            progLstToUpdate.add(prog);
                            updated = true;
                        }   
                    }
                }
                
            }


            if(!progLstToUpdate.isEmpty())
            {
                CLQ_ProgramTriggerHandler.BypassTrigger = true; //added after review
                update progLstToUpdate;
                CLQ_ProgramTriggerHandler.BypassTrigger = false;
            }   
            
    	} catch(exception e)
        {
            system.debug('Exception::'+e.getMessage());
            Integration_Transaction_Logs.LogErrorRealTime('SFDC-001.2',e.getMessage()  , 'Update Program From Inspection for Last Inspection Date Cause:' + e.getCause(), 'Line:'+e.getLineNumber(), e.getStackTraceString(), e.getTypeName());
        }	
    	
    }
    
    //this method is called from process builder and is designed to be independent from triggers
    @InvocableMethod
    public static void updatePro(List<Id> ids)
    {
        final String ANNUAL = 'Annual';
        final String COMPLIANCE = 'Compliance';
        final String PROVISIONAL = 'Provisional';
        
        try
        {
           
            //13857 start
            Set<String> inspectionTypes = new Set<String>{ANNUAL, COMPLIANCE, PROVISIONAL}; //all the inspection types to consider
            Set<Id> programIds = new Set<Id>();
            List<CLQ_Program__c> progLstToUpdate = new List<CLQ_Program__c>();
            
            //have to get all inspection, the condition will be in the programsToCheck query
            List<CLQ_Inspection__c> insList;
            if(ids != null){
                insList = [Select Id, CLQ_Program__c, CLQ_Inspection_Status__c, CLQ_Inspection_Type__c
                                    FROM CLQ_Inspection__c 
                                    WHERE Id in : ids];
            }                      

            
            
            if (!insList.isEmpty()) {
                
                for(CLQ_Inspection__c ins : insList) {
                    programIds.add(ins.CLQ_Program__c);
                }
                
                
                
                                    
                //get the programs along with all the related inspections sorted by latest first
                List<CLQ_Program__c> programsToCheck = [SELECT Id, CLQ_Last_Inspection_Date__c, (SELECT Id, CLQ_Last_Visit_Date__c,CLQ_Inspection_Type__c FROM Inspections__r WHERE CLQ_Inspection_Status__c='Under Approver Review' AND CLQ_Inspection_Type__c in: inspectionTypes ORDER BY CreatedDate DESC) FROM CLQ_Program__c WHERE Id in: programIds];
                                            
                updateProgramsFromProgramList(programsToCheck); //this will update the programs


            }

            //13857 end

        }
        catch(exception e)
        {
            system.debug('Exception::'+e.getMessage());
            Integration_Transaction_Logs.LogErrorRealTime('SFDC-001.2',e.getMessage()  , 'Update Program From Inspection for Last Inspection Date Cause:' + e.getCause(), 'Line:'+e.getLineNumber(), e.getStackTraceString(), e.getTypeName());
        }
    }
}