force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/Approved_Total_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Approved_Total_Capacity__c</fullName>
    <description>Approved Total Capacity for TFS 11180</description>
    <label>Recommended Total Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Approved_Total_Capacity_Under_2_1_2__c.field-meta.xml
<CustomField>
    <fullName>Approved_Total_Capacity_Under_2_1_2__c</fullName>
    <description>Field getting updated from Max. Number of Children Under 2 1/2 from Room Space Inspection</description>
    <label>Recommended Total Capacity Under 2 1/2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_CAP_Generated__c.field-meta.xml
<CustomField>
    <fullName>CLQ_CAP_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAP Generated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-license</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Incident / Injury / Illness</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Amendment - change of location</fullName>
            </value>
            <value>
                <fullName>Amendment - change of capacity</fullName>
            </value>
            <value>
                <fullName>Initial Registration</fullName>
            </value>
            <value>
                <fullName>Ongoing Registration</fullName>
            </value>
            <value>
                <fullName>Technical Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_On_Site_Representative__c.field-meta.xml
<CustomField>
    <fullName>CLQ_On_Site_Representative__c</fullName>
    <label>On- Site Representative</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_On_Site_Representative_Present__c.field-meta.xml
<CustomField>
    <fullName>CLQ_On_Site_Representative_Present__c</fullName>
    <label>On-Site Representative Present</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Representative_Email__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Representative_Email__c</fullName>
    <label>Representative Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Visit_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Visit_Status__c</fullName>
    <label>Visit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be Scheduled</fullName>
                <default>true</default>
                <label>To be Scheduled</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Visit Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GLC_ESignature__mdt/GLC_ESignature__mdt.object-meta.xml
<CustomObject>
    <label>GLC ESignature</label>
    <pluralLabel>GLCESignatures</pluralLabel>
</CustomObject>

force-app/main/default/classes/GLC_ESignatureCtrl.cls
public with sharing class GLC_ESignatureCtrl {
    public static final String EMPTY_STRING = '';
    public static final String I_LETTER = 'I';
    public static final String SUCCESS_STRING = 'Success';
    public static final String Representative_Signature = 'Representative_Signature';
	public static final String png = 'png'; 
    public static final String Visit_Completed = 'Visit_Completed';
    public static final String Approved = 'Approved';
    public static final String Closed =  'Closed';
    public static final String Revised = 'Revised';
    @AuraEnabled
    public static String signDocuments(String signature, String recordId, String approvedTotCapacity, String approvedTotCapacityUnderTH, String siteRepName, String siteRepEmail) {
		Map<String, String> GLCeSignature = new  Map<String, String>();
    
        for(GLC_ESignature__mdt mdt : [Select label,QualifiedApiName from GLC_ESignature__mdt]){
                GLCeSignature.put(mdt.QualifiedApiName,mdt.label);
            }
        try {
            Blob blbSignature = EncodingUtil.base64Decode(signature);
            
            ContentVersion oCvNew = new ContentVersion();
            if(GLCeSignature.size()!=0){
            oCvNew.Title = GLCeSignature.get(Representative_Signature);
            oCvNew.PathOnClient = GLCeSignature.get(Representative_Signature) + GLCeSignature.get(png);
            }
            oCvNew.VersionData = blbSignature;
            oCvNew.IsMajorVersion = false;
            List<ContentVersion> CvList = new List<ContentVersion>();
            CvList.add(oCvNew);
            if(!CvList.isEmpty()){
                insert CvList;
            } 
            ContentVersion objConVer;
            if(oCvNew.Id!=null){
                objConVer = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :oCvNew.Id];
            }
            
            Id ContentDocumentId = objConVer.ContentDocumentId;

            ContentDocumentLink oCDL = New ContentDocumentLink();
            oCDL.LinkedEntityId = recordId;
            oCDL.ContentDocumentId = ContentDocumentId;
            oCDL.shareType = I_LETTER;
            List<ContentDocumentLink> CDLList = new List<ContentDocumentLink>();
            CDLList.add(oCDL);
            if(!CDLList.isEmpty()){
                insert CDLList;
            } 
            CLQ_Inspection__c oInspection;
            if(recordId!=null){
                oInspection = [SELECT Id, CLQ_Inspection_Type__c, CLQ_Inspection_Status__c, OwnerId, CLQ_Visit_Status__c, CLQ_CAP_Generated__c, CLQ_On_Site_Representative__c, CLQ_On_Site_Representative_Present__c, CLQ_Representative_Email__c, Approved_Total_Capacity__c, Approved_Total_Capacity_Under_2_1_2__c FROM CLQ_Inspection__c WHERE Id =: recordId];
            }
            

            oInspection.CLQ_On_Site_Representative__c = siteRepName;
            oInspection.CLQ_Representative_Email__c = siteRepEmail;
            if( approvedTotCapacity!=EMPTY_STRING){
            oInspection.Approved_Total_Capacity__c = Decimal.valueOf(approvedTotCapacity);
            }
            if(approvedTotCapacityUnderTH!=EMPTY_STRING){
            oInspection.Approved_Total_Capacity_Under_2_1_2__c = Decimal.valueOf(approvedTotCapacityUnderTH);
            }
            if(GLCeSignature.size()!=0){
            oInspection.CLQ_Visit_Status__c = GLCeSignature.get(Visit_Completed);
            }
            if(GLCeSignature.size()!=0 && oInspection.CLQ_Inspection_Status__c <> GLCeSignature.get(Approved) && oInspection.CLQ_Inspection_Status__c <> GLCeSignature.get(Closed) && oInspection.CLQ_Inspection_Status__c <> GLCeSignature.get(Revised)) {
                oInspection.CLQ_CAP_Generated__c = true;
            }
            List<CLQ_Inspection__c> InspectionList = new List<CLQ_Inspection__c>();
            InspectionList.add(oInspection);
            if(!InspectionList.isEmpty()){
                update InspectionList;
            } 
        } catch(Exception oEx) {
			system.debug('Exception:'+oEx);
        }
        return SUCCESS_STRING;


    }
}