force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Tool__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Tool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Tool</label>
    <referenceTo>CLQ_Inspection_Tools__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/recordTypes/CLQ_Inspection.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/objects/CLQ_Inspection_Tools__c/CLQ_Inspection_Tools__c.object-meta.xml
<CustomObject>
    <label>Inspection Tools</label>
    <nameField>
        <label>Inspection Tools Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Tools</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection_Tools__c/fields/CLQ_Applicable_To__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Applicable_To__c</fullName>
    <label>Applicable To</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alleged Ops</fullName>
            </value>
            <value>
                <fullName>Child Care Center</fullName>
            </value>
            <value>
                <fullName>Day Camp</fullName>
            </value>
            <value>
                <fullName>In-Home Aid</fullName>
            </value>
            <value>
                <fullName>Out of State Registration</fullName>
            </value>
            <value>
                <fullName>Pre School</fullName>
            </value>
            <value>
                <fullName>School Age Child Care</fullName>
            </value>
            <value>
                <fullName>FCC - Type A Home</fullName>
            </value>
            <value>
                <fullName>FCC - Type B Home</fullName>
            </value>
            <value>
                <fullName>Type A Home</fullName>
                <isActive>false</isActive>
                <label>Type A Home</label>
            </value>
            <value>
                <fullName>Type B Home</fullName>
                <isActive>false</isActive>
                <label>Type B Home</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection_Tools__c/fields/CLQ_Applicable_To_Scope__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Applicable_To_Scope__c</fullName>
    <label>Applicable To (Scope)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
                <default>true</default>
                <label>Full</label>
            </value>
            <value>
                <fullName>Focused</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection_Tools__c/fields/CLQ_Application_To_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Application_To_Inspection_Type__c</fullName>
    <label>Application To(Inspection Type)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-license</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Incident / Injury / Illness</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Amendment - change of location</fullName>
            </value>
            <value>
                <fullName>Amendment - change of capacity</fullName>
            </value>
            <value>
                <fullName>Technical Assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/CLQ_Room_Space__c.object-meta.xml
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Approved_Room_Space__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Approved_Room_Space__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Rooms/Group Information</relationshipLabel>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Length_Feet__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Length_Feet__c</fullName>
    <label>Length1 Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Number_of_Children_Under_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Number_of_Children_Under_2__c</fullName>
    <label>Max. Number of Children Under 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Used_By_Under_or_Over_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Used_By_Under_or_Over_2__c</fullName>
    <label>Used by Under or Over 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under</fullName>
            </value>
            <value>
                <fullName>Over</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/fields/CLQ_Width_Feet__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Width_Feet__c</fullName>
    <label>Width1 Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space__c/recordTypes/CLQ_Indoor_Room_Space.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Indoor_Room_Space</fullName>
    <active>true</active>
    <label>Indoor Room/Space</label>
</RecordType>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/CLQ_Room_Space_Inspection__c.object-meta.xml
<CustomObject>
    <description>Junction object between Room/Space and Inspection</description>
    <label>Room/Space Inspection</label>
    <nameField>
        <label>Room/Space Inspection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Space Inspection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Currently_In_Use__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Currently_In_Use__c</fullName>
    <label>In Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Rooms/Space Inspection</relationshipLabel>
    <relationshipName>Rooms_Space_Inspection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Number_of_Children_Under_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Number_of_Children_Under_2__c</fullName>
    <label>Max. Number of Children Under 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Rooms_Spaces_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipName>Rooms_Spaces_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Room_Space_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Room_Space_Type__c</fullName>
    <label>Room/Space Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Space</fullName>
            </value>
            <value>
                <fullName>Additional Space</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Used_By_Under_or_Over_2__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Used_By_Under_or_Over_2__c</fullName>
    <label>Used By Under or Over 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under</fullName>
            </value>
            <value>
                <fullName>Over</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/fields/CLQ_Width_Feet__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Width_Feet__c</fullName>
    <label>Width1 Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Room_Space_Inspection__c/recordTypes/CLQ_Indoor_Room_Space.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Indoor_Room_Space</fullName>
    <active>true</active>
    <label>Indoor Room/Space</label>
</RecordType>

force-app/main/default/classes/CLQ_UtilityClassTest.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : CLQ_UtilityClassTest
** Description      : N/A
** Version          : 1.1
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
**  N/A     				N/A				1.0         Initial Build 
**  Pavan Ayta				8/23/17			1.1			Added setExecuteControlSetting() for Task - 11615
**************************************************************************************************************/
@isTest
private class CLQ_UtilityClassTest {
    @IsTest
    static void utilityTest() {
        system.runAs(new user(ID = UserInfo.getUserID())){
            
            
            CLQ_Program_Transaction__c ProgramTransaction = CLQ_UnitTestUtilities.ProgramTransactions.values()[0];
            system.AssertNotEquals(null,ProgramTransaction,'Testing');
            CLQ_Program__c programRecord = Database.query(CLQ_UtilityClass.createSOQLQuery('CLQ_Program__c',' id=\''+ProgramTransaction.CLQ_Program__c+'\'', null));
            
            contact c = new contact();
            c.lastname = 'test';
            insert  c;
            
            CLQ_Room_Space__c RorGrecord = new CLQ_Room_Space__c(CLQ_Length_Feet__c = 30,CLQ_Width_Feet__c = 30,CLQ_Currently_In_Use__c = 'Yes',CLQ_Approved_Room_Space__c = true, CLQ_Number_of_Children_Under_2__c = 2,CLQ_Used_By_Under_or_Over_2__c = 'Over',name='dining area', CLQ_Room_Space_Type__c='Primary Space', CLQ_Program__c= programRecord.id,CLQ_Program_Transaction__c=ProgramTransaction.id);
            RorGrecord.RecordTypeId = Schema.SObjectType.CLQ_Room_Space__c.getRecordTypeInfosByDeveloperName().get('CLQ_Indoor_Room_Space').getRecordTypeId();
            list<CLQ_Room_Space__c> roomSpaceList = new list<CLQ_Room_Space__c>();
            roomSpaceList.add(RorGrecord);
            //insert roomSpaceList; 
            
            test.starttest();
            CLQ_UtilityClass.createInspectionrecord('Provisional', 'Full', 'Pending Processing');
            CLQ_UtilityClass.redirecttoPage('test');
            
            CLQ_UtilityClass.createTaskrecord(c.id,programRecord.id,system.Date.today(),'test','test');
            CLQ_UtilityClass.createTaskrecord(ProgramTransaction,system.Date.today(),'test','test');
            
            map<Id,CLQ_Program_Transaction__c> ProgramTransactionMap = CLQ_UnitTestUtilities.ProgramTransactions;
            CLQ_UtilityClass.copyRelatedListfromPTtoProgram(ProgramTransactionMap.keyset());
            
            Id RtId = Schema.SObjectType.CLQ_Inspection__c.getRecordTypeInfosByDeveloperName().get('CLQ_Inspection').getRecordTypeId();        
            
            CLQ_Inspection_Tools__c Inspect1= new CLQ_Inspection_Tools__c();
            Inspect1.CLQ_Applicable_To_Scope__c='Full';
            Inspect1.CLQ_Application_To_Inspection_Type__c='Complaint';
            Inspect1.CLQ_Applicable_To__c='Day Camp';
            insert Inspect1; 
            CLQ_Inspection__c Inspect = new CLQ_Inspection__c();
            Inspect.CLQ_Inspection_Tool__c = Inspect1.Id;
            Inspect.CLQ_Program_Transaction__c=ProgramTransaction.Id;
            insert Inspect; 
            CLQ_Room_Space_Inspection__c Inspect3 = new CLQ_Room_Space_Inspection__c();
            Inspect3.CLQ_Inspection__c = Inspect.id;
            set<Id> insp = new set<Id>();
            insp.add(Inspect.id);
            set<Id> progtrans = new set<Id>();
            progtrans.add(ProgramTransaction.Id);
            CLQ_UtilityClass utilCls = new CLQ_UtilityClass();
            utilCls.copyRoomSpactionInspectiontoTransaction(insp);
            CLQ_UtilityClass.copyBuildingApprovaltoinspection(programRecord.id,Inspect.id);
            CLQ_UtilityClass.queryRoomSpacefromProgram(programRecord.id);
            CLQ_UtilityClass.createRoomSpaceInspection( roomSpaceList ,Inspect);
            CLQ_UtilityClass.cloneFromOneObjectToanother(programRecord,'clq_program__c');
            CLQ_UtilityClass.copyRoomSpaceTransactiontoProgram(progtrans);
            CLQ_UtilityClass.ifInspectionAlreadyExists(Inspect.Id, True, 'Complaint');
            CLQ_UtilityClass.getCombinedCounties('Adam County');
            //CLQ_UtilityClass.retriveInspectionToolForInspection(Inspect,'Full','Complaint','Day Camp');
            
            
            test.stoptest();  
            system.assertEquals(True, 1==1,'Testing');
        }
    }  
    
    
    
    @TestSetup
    static void testSetup()
    {
        CLQ_UnitTestUtilities.setExecuteControlSetting(); //11615
        CLQ_UnitTestUtilities.HardCodedTransactionCreation();
        
    }
    
    
}