force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Start_Date__c</fullName>
    <description>Start Date for Day Camp&apos;s Program</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/CLQ_Role__c.object-meta.xml
<CustomObject>
    <description>Role of a contact in an organization</description>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Contact__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Role is a junction object between Program and Contact</description>
    <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Associated Individuals</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Role__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Role__c</fullName>
    <description>Role of a contact in an organization or program.</description>
    <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
    <label>Program Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
            <value>
                <fullName>On-site Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Representative</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Alternate On Site Contact</fullName>
            </value>
            <value>
                <fullName>Parent_Guardian</fullName>
                <label>Parent - Guardian</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Start_Date__c</fullName>
    <inlineHelpText>Date the individual started in this role</inlineHelpText>
    <label>Role Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Role__c/fields/CLQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Status__c</fullName>
    <description>This field describes the current role status of the contact on the program.</description>
    <label>Program Role Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Pending Removal</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Staff_Record__c/CLQ_Staff_Record__c.object-meta.xml
<CustomObject>
    <description>Provides an overview of all staff members employed by the Program.</description>
    <label>Staff Record</label>
    <nameField>
        <displayFormat>Staff #{000000}</displayFormat>
        <label>Staff Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Staff_Record__c/fields/CLQ_Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Hire_Date__c</fullName>
    <label>Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Staff_Record__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Staff Records</relationshipLabel>
    <relationshipName>Staff_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Staff_Record__c/fields/CLQ_Name__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff Records</relationshipLabel>
    <relationshipName>Staff_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Staff_Record__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Staff Records</relationshipLabel>
    <relationshipName>Staff_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Staff_Record__c/fields/CLQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Status__c</fullName>
    <label>PD Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLQ_StaffRecordTriggerHandler.cls
//Class to contains all the method related to CLQ_StaffRecordTrigger
//Developer : Vrajesh Sheth (vsheth@incapsulate.com)
//Date : 09/07/2016
public with sharing class CLQ_StaffRecordTriggerHandler extends CLQ_Trigger  {
    
    ////////////////////////////////     Boilerplate implementation  ////////////////////////////
    //Allows only this trigger to be bypassed. Useful in Unit Test data setup and some bulk data loads.
    public static final string ONSITE_VISIT_PENDING='Onsite Visit Pending';
    public static final string APPROVER_STATE_USER='Approver - State User';
    public static final string SUTQ_REVIEWER_STATE_USER='Lic and SUTQ Reviewer - State User';
    public static final string ODJFS_FCC_APPROVER='ODJFS FCC Approver - State User';
    public static boolean BypassTrigger {
        get {
            if (BypassTrigger == null){
                BypassTrigger = false;
            } 
            return BypassTrigger;
        }
        set;
    }
    
    static boolean HasUpdated;
    public override boolean getUpdateFlag()                 {   return HasUpdated;    }
    public override void setUpdateFlag(boolean newVal)      {   HasUpdated = newVal;    }
    
    //Calls the Base class Constructor
    public CLQ_StaffRecordTriggerHandler(list < sObject > newlistin, map < id, sObject > newMapin, list < sObject > oldlistin,map < id, sObject > oldMapin,
            boolean isExecutingin, boolean isInsertin, boolean isUpdatein, boolean isDeletein,
            boolean isBeforein, boolean isAfterin, boolean isUndeletein, integer sizein) {
            super(newlistin, newMapin, oldlistin, oldMapin,
                isExecutingin, isInsertin, isUpdatein, isDeletein,
                isBeforein, isAfterin, isUndeletein, sizein);
            BypassInheritedTrigger = BypassTrigger;
                if(!(BypassInheritedTrigger || BypassAllTriggers)){            
                                            BypassInheritedTrigger = BypassSelectiveTriggers;
                                        }
        }
    
    ////////////////////////////////     Boilerplate implementation  ////////////////////////////
    
    //after insert logic method
    //@param : triggernew, triggernewmap
    //@return : null
    public override void afterinsert() {
    	//Mod by LD on 12/16/16 - Commented out the below line that creates a ContactRole when a Staff Record is created based on a changed requirement.
        //onafterinsert((list<CLQ_Staff_Record__c>) newlist, (map<id,CLQ_Staff_Record__c>) newMap);
    }
    
    //after update logic method
    //@param : triggerold, triggeroldmap,triggernew, triggernewmap
    //@return : null
    public override void afterupdate() {
    	//Mod by LD on 12/16/16 - Commented out the below line that creates a ContactRole when a Staff Record is updated based on a changed requirement.
        //onafterupdate((list<CLQ_Staff_Record__c>) oldlist, (map<id,CLQ_Staff_Record__c>) oldMap,(list<CLQ_Staff_Record__c>) newlist, (map<id,CLQ_Staff_Record__c>) newMap);
    }
    //before delete added by Vamshi Panuganti 
    // If the status of the program transaction is Onsite Visit Peding then certain profiles not allowed to delete the staff records manually.
     public override void beforedelete() {
        onbeforedelete((list<CLQ_Staff_Record__c>) oldlist);
        }
     public void onbeforedelete(list<CLQ_Staff_Record__c> oldlist)
     {
     Profile ProfileName = [select Name from profile where id = :userinfo.getProfileId()];
     system.debug('Profile name::::::::'+ProfileName);
     List<Id> staffIds = new List<Id>();
      for(CLQ_Staff_Record__c cr:oldlist){
          staffIds.add(cr.Id);
      }
         Map<Id,CLQ_Staff_Record__c> staffMap;
         if(staffIds != null){
             staffMap = new Map<Id,CLQ_Staff_Record__c> ([SELECT Id,CLQ_Program_Transaction__r.CLQ_Transaction_Status__c from CLQ_Staff_Record__c WHERE Id IN :staffIds]);
         }
         
    for(CLQ_Staff_Record__c cr:oldlist){
    //system.debug('Status ::::::::'+staffMap.get(cr.Id).CLQ_Program_Transaction__r.CLQ_Transaction_Status__c);
          if(staffMap.size()!=0 && staffMap.get(cr.Id)!=null && staffMap.get(cr.Id).CLQ_Program_Transaction__r.CLQ_Transaction_Status__c ==ONSITE_VISIT_PENDING 
          && (ProfileName.Name==APPROVER_STATE_USER || ProfileName.Name==SUTQ_REVIEWER_STATE_USER || ProfileName.Name==ODJFS_FCC_APPROVER))
          {             
             cr.addError('Deletion of staff record is not allowed');
            
          }     
         }
     }
    
    //Method to call on afterinsert 
   /* public void onafterinsert(list<CLQ_Staff_Record__c> triggernew, map<id,CLQ_Staff_Record__c> triggernewMap){
        list<id> insertedstaffrecordidlist = new list<id>();
        list<id> contactIDlist = new list<id>();
        for(CLQ_Staff_Record__c staffrecord : triggernew){
            insertedstaffrecordidlist.add(staffrecord.id);
            contactIDlist.add(staffrecord.CLQ_Name__c);
        }
        insertSaffContactRole(insertedstaffrecordidlist,contactIDlist);
    }
    
    //Method to call on afterupdate
    public void onafterupdate(list<CLQ_Staff_Record__c> triggerold, map<id,CLQ_Staff_Record__c> triggeroldMap,list<CLQ_Staff_Record__c> triggernew, map<id,CLQ_Staff_Record__c> triggernewMap){
        list<id> insertedstaffrecordidlist = new list<id>();
        list<id> contactIDlist = new list<id>();
        for(CLQ_Staff_Record__c staffrecord : triggernew){
            if(staffrecord.CLQ_Name__c != null 
            && staffrecord.CLQ_Name__c != (triggeroldMap.get(staffrecord.id).CLQ_Name__c)){
                insertedstaffrecordidlist.add(staffrecord.id);
                contactIDlist.add(staffrecord.CLQ_Name__c);
            }
            
        }
        insertSaffContactRole(insertedstaffrecordidlist,contactIDlist);
    }
    
    //logic to insert contact role of staff for given staff record
    public static void insertSaffContactRole(list<id> staffrecordIDlist,list<id> contactIDset){
        
        //Query staff record informaton
        map<id,CLQ_Staff_Record__c> staffrecordmap = new map<id,CLQ_Staff_Record__c>([SELECT id
                                                                                            ,CLQ_Name__c
                                                                                            ,CLQ_Hire_Date__c
                                                                                            ,CLQ_Inspection__c
                                                                                            ,CLQ_Inspection__r.CLQ_Program__c
                                                                                    FROM CLQ_Staff_Record__c
                                                                                    WHERE id in :staffrecordIDlist]);
        
        //Query exsting Staff Role record
        list<CLQ_Role__c> existingRoleList = new list<CLQ_Role__c>();
        existingRoleList = [SELECT  id
                                    ,CLQ_Contact__c
                                    ,CLQ_Program__c
                                    ,CLQ_Role__c
                            FROM CLQ_Role__c 
                            WHERE CLQ_Contact__c in :contactIDset
                            AND CLQ_Role__c = 'Staff'];
        //CreateMap of existing record 
        map<string,CLQ_Role__c> existingStaffRoleKeyRecordMap = new map<string,CLQ_Role__c>();
        for(CLQ_Role__c existingRecord : existingRoleList){
            existingStaffRoleKeyRecordMap.put(String.valueof(existingRecord.CLQ_Contact__c) + String.valueof(existingRecord.CLQ_Program__c) , existingRecord);
        }
        
        //list to store new contact role
        list<CLQ_Role__c> contactRoleToInsert = new list<CLQ_Role__c>();
        for(CLQ_Staff_Record__c staffRecord : staffrecordmap.values()){
            if(existingStaffRoleKeyRecordMap.get(String.valueof(staffRecord.CLQ_Name__c)+String.valueof(staffRecord.CLQ_Inspection__r.CLQ_Program__c)) == null){
                contactRoleToInsert.add(new CLQ_Role__c(CLQ_Contact__c = staffRecord.CLQ_Name__c
                                                    ,CLQ_Program__c = staffRecord.CLQ_Inspection__r.CLQ_Program__c
                                                    ,CLQ_Start_Date__c = staffRecord.CLQ_Hire_Date__c
                                                    ,CLQ_Role__c = 'Staff'
                                                    ,recordTypeid = Schema.SObjectType.CLQ_Role__c.getRecordTypeInfosByName().get('Program Role').getRecordTypeId()
                                                    ,CLQ_Status__c = 'Approved'));
                                                    
            }
            
        }
        
        insert contactRoleToInsert; 
        
    }*/
}