force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspector__c/CLQ_Inspector__c.object-meta.xml
<CustomObject>
    <label>Inspector</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inspector Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspector__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Inspectors</relationshipLabel>
    <relationshipName>Inspectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspector__c/fields/CLQ_Inspector_Name__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspector_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspector Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inspectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Global_Settings__c/Global_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <label>Global Settings</label>
</CustomObject>

force-app/main/default/objects/Global_Settings__c/fields/Can_Edit_Closed_Programs2__c.field-meta.xml
<CustomField>
    <fullName>Can_Edit_Closed_Programs2__c</fullName>
    <defaultValue>&quot;System Administrator, Admin Read-Only, State Admin - State user, Approver - State User, ODJFS FCC Approver - State User, ODE Lic and SUTQ Reviewer - State User, ODJFS FCC Reviewer - County Role, ODJFS FCC Approver - County Role&quot;</defaultValue>
    <description>Since the text area only has 255 chars, we needed to field to hold the list of profile names.</description>
    <inlineHelpText>Comma separated list of Profile names.</inlineHelpText>
    <label>Can Edit Closed Programs2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Global_Settings__c/fields/Can_Edit_Closed_Programs__c.field-meta.xml
<CustomField>
    <fullName>Can_Edit_Closed_Programs__c</fullName>
    <defaultValue>&quot;, System Administrator, Admin Read-Only&quot;</defaultValue>
    <description>These Profile Names are allowed to edit programs that are closed.</description>
    <inlineHelpText>Comma separated list of Profile names.</inlineHelpText>
    <label>Can Edit Closed Programs</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CLQ_InspectionController.cls
public with sharing class CLQ_InspectionController {
    
    public boolean CanEdit {get;set;}
    
    public CLQ_InspectionController(ApexPages.StandardController controller) {
        CanEdit = false;
         CLQ_Inspection__c inspectionRecord = [SELECT OwnerId FROM CLQ_Inspection__c WHERE ID = :controller.getId() LIMIT 1]; 
                
        Id CurrentUserId = UserInfo.GetUserId();
        if (inspectionRecord.OwnerId == CurrentUserId)
        {
            CanEdit = true;
            return;
        }
            
        User CurrUser = [Select Profile.Name FROM User Where Id = :CurrentUserId];
        string ProfileName = CurrUser.Profile.Name;
        System.debug('ProfileName==>'+ProfileName);
        Global_Settings__c GlobalSettings = Global_Settings__c.GetInstance();
       System.debug('GlobalSettings'+GlobalSettings);
       
        if ((GlobalSettings.Can_Edit_Closed_Programs__c!= null && GlobalSettings.Can_Edit_Closed_Programs__c.Contains(ProfileName)) || (GlobalSettings.Can_Edit_Closed_Programs2__c!=null && GlobalSettings.Can_Edit_Closed_Programs2__c.Contains(ProfileName)))
        {
            CanEdit = true;
            return;
        }       
        list<CLQ_Inspector__c> Inspectors = [Select Id, CLQ_Inspector_Name__c FROM CLQ_Inspector__c WHERE CLQ_Inspection__c = :controller.getId()];   
        for(CLQ_Inspector__c Inspector : Inspectors)
        {
            if (CurrentUserId == Inspector.CLQ_Inspector_Name__c)
            {
                CanEdit = true;
                return;
            }
     
        }
           
        
    }
}