force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Insp_DeferralDueDate__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Insp_DeferralDueDate__c</fullName>
    <description>This field automatically gets calculated based on the deferral duration pick list value.</description>
    <label>Deferral Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Type__c</fullName>
    <formula>TEXT(CLQ_Program__r.CLQ_License_Type__c)</formula>
    <label>License Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program_Transaction__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Transaction</label>
    <referenceTo>CLQ_Program_Transaction__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_OCLQS_Configuration__c/CLQ_OCLQS_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Type__c</fullName>
    <inlineHelpText>Type of license issued</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisional</fullName>
                <default>true</default>
                <label>Provisional</label>
            </value>
            <value>
                <fullName>Continuous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_OCLQS_Configuration__c.field-meta.xml
<CustomField>
    <fullName>CLQ_OCLQS_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OCLQS Configuration</label>
    <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Program_Rating__c.field-meta.xml
<CustomField>
    <fullName>Program_Rating__c</fullName>
    <label>SUTQ Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Effective_Date__c</fullName>
    <label>SUTQ Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/recordTypes/CLQ_FCC_Type_B_Home.recordType-meta.xml
<RecordType>
    <fullName>CLQ_FCC_Type_B_Home</fullName>
    <active>true</active>
    <description>ODJFS - Type B Homes: 1 to 6</description>
    <label>FCC - Type B Home</label>
</RecordType>

force-app/main/default/objects/CLQ_Program_Transaction__c/CLQ_Program_Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage program applications and updates</description>
    <label>Program Application</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipName>Program_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Submission_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Submission_Date__c</fullName>
    <description>The date transaction was submitted. Replace this API with Submission_Date1__c if want to delete the field</description>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/CLQ_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Reviewer Review</fullName>
            </value>
            <value>
                <fullName>Returned for Revision</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed by System</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approver Review In Progress</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
            <value>
                <fullName>Not Complete</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>System Deleted</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Registration Assigned</fullName>
            </value>
            <value>
                <fullName>Return for Revision</fullName>
            </value>
            <value>
                <fullName>Supervisor Desk Review</fullName>
            </value>
            <value>
                <fullName>Unable to Rate</fullName>
            </value>
            <value>
                <fullName>Onsite Visit Pending</fullName>
            </value>
            <value>
                <fullName>Rating Recommended for Review</fullName>
            </value>
            <value>
                <fullName>Supervisor On-Site Review</fullName>
            </value>
            <value>
                <fullName>Annual Report Disapproved</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn at Applicant&apos;s Request</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/fields/DeferralDueDate__c.field-meta.xml
<CustomField>
    <fullName>DeferralDueDate__c</fullName>
    <description>It will automatically get updated based on the Deferral Duration.</description>
    <label>Deferral Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program_Transaction__c/recordTypes/CLQ_Application_CC_Center.recordType-meta.xml
<RecordType>
    <fullName>CLQ_Application_CC_Center</fullName>
    <active>true</active>
    <description>Child Care Center - Application for any type of License</description>
    <label>Application - CC Center</label>
</RecordType>

force-app/main/default/objects/Visit_Information__c/Visit_Information__c.object-meta.xml
<CustomObject>
    <label>Visit Information</label>
    <nameField>
        <label>Visit Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Information__c/fields/Inspection__c.field-meta.xml
<CustomField>
    <fullName>Inspection__c</fullName>
    <label>Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Visit Information</relationshipLabel>
    <relationshipName>Visit_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CLQ_Test_Util.cls
public with sharing class CLQ_Test_Util {
 
  
  public static CLQ_Program__c getCLQProgram()
  {
      
       CLQ_Program__c cp = new CLQ_Program__c();
        cp.name = 'Test Pgrm';
        cp.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByDeveloperName().get('CLQ_FCC_Type_B_Home').getRecordTypeId();
        cp.CLQ_License_Type__c = 'Continuous';
        cp.Program_Rating__c = '0';
        cp.Rating_Effective_Date__c = Date.today().addYears(-2);
      return cp;
  }
    public static CLQ_Program__c getCLQProgram1()
  {
      
        CLQ_Program__c cp1 = new CLQ_Program__c();
        cp1.name = 'Test Pgrm';
        cp1.CLQ_License_Type__c = 'Continuous';
        //cp1.CLQ_OCLQS_Configuration__c = 'FCC - Type B Home';
       
        return cp1;
  }
  public static CLQ_Program__c getCLQProgram2()
  {
      
        CLQ_Program__c cp2 = new CLQ_Program__c();
        cp2.name = 'Test Pgrm';
        cp2.CLQ_License_Type__c = 'Continuous';
        cp2.Program_Rating__c = '3';
        cp2.Rating_Effective_Date__c = Date.today();
        //cp2.CLQ_OCLQS_Configuration__c = 'Child Care Center';
       
        return cp2;
  }
  public static CLQ_Program_Transaction__c getCLQProgramTransaction()
  {
      
       CLQ_Program_Transaction__c cpt = new CLQ_Program_Transaction__c();
        cpt.CLQ_Transaction_Status__c = 'Submitted';      	
        cpt.CLQ_Submission_Date__c = date.today().addDays(-122);
      	cpt.recordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByDeveloperName().get('CLQ_Application_CC_Center').getRecordTypeId();
        
      return cpt;
  }  
    public static CLQ_Program_Transaction__c getCLQProgramTransactionForTask()
  {
      
       CLQ_Program_Transaction__c cpt = new CLQ_Program_Transaction__c();
        cpt.CLQ_Transaction_Status__c = 'Deferral';
      cpt.DeferralDueDate__c = date.today().addDays(-2);
      cpt.CLQ_Submission_Date__c = date.today().addDays(-122);
      return cpt;
  }  
    public static CLQ_Inspection__c getCLQ_InspectionForTask()
  {
      
       CLQ_Inspection__c Insp = new CLQ_Inspection__c();
        Insp.Inspection_Status__c = 'Deferral';
      Insp.CLQ_Inspection_Status__c = 'Deferral';
            Insp.CLQ_Insp_DeferralDueDate__c = date.today().addDays(-2);
      //cpt.CLQ_Submission_Date__c = date.today().addDays(-122);
      return Insp;
  }  
    public static Visit_Information__c getVisitInformation(Id inspId)
  {
      
       Visit_Information__c visit = new Visit_Information__c();
        Visit.Visit_Date__c = date.today();
      visit.Name = 'Visit 1';
      visit.Inspection__c = inspId;
      //Insp.CLQ_Inspection_Status__c = 'Deferral';
        //    Insp.CLQ_Insp_DeferralDueDate__c = date.today().addDays(-2);
      //cpt.CLQ_Submission_Date__c = date.today().addDays(-122);
      return visit;
  }  
}