force-app/main/default/objects/CLQ_Inspection__c/CLQ_Inspection__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Owner__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inspection Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InspectionOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Processing</fullName>
                <default>true</default>
                <label>Pending Processing</label>
            </value>
            <value>
                <fullName>Under Approver Review</fullName>
            </value>
            <value>
                <fullName>Returned to Reviewer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Revision In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Rating Assessment Complete</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Original_Inspection__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Original_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Inspection</label>
    <referenceTo>CLQ_Inspection__c</referenceTo>
    <relationshipLabel>Associated Inspections (Follow-Ups)</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/fields/CLQ_Program__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>CLQ_Program__c</referenceTo>
    <relationshipLabel>Inspections</relationshipLabel>
    <relationshipName>Inspections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLQ_Inspection__c/recordTypes/Onsite_Visit_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Onsite_Visit_Record_Type</fullName>
    <active>true</active>
    <description>Record type belongs to Inspection Object</description>
    <label>Onsite Visit Record Type</label>
</RecordType>

force-app/main/default/objects/CLQ_Program__c/CLQ_Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Continuous_License_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Continuous_License_Status__c</fullName>
    <defaultValue>&apos;started&apos;</defaultValue>
    <description>This field will tell the status of any continuous license transaction that is attached to the program.  It can contain either blank, &apos;initiated&apos; or &apos;approved&apos;, &apos;approved&apos; implies initiated.</description>
    <label>Continuous License Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Current_Rating__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Current_Rating__c</fullName>
    <description>To show this value to portal</description>
    <label>Current Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Current_Rating_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Current_Rating_Expiration_Date__c</fullName>
    <inlineHelpText>Portal visibility</inlineHelpText>
    <label>Current Rating Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Issue_Date__c</fullName>
    <inlineHelpText>Date of issuance of license.</inlineHelpText>
    <label>Provisional License Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_License_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>CLQ_License_Registration_Status__c</fullName>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Licensed</fullName>
            </value>
            <value>
                <fullName>Not Licensed</fullName>
            </value>
            <value>
                <fullName>Licensed/Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/CLQ_Manual__c.field-meta.xml
<CustomField>
    <fullName>CLQ_Manual__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Must be checked for admins to manually update SUTQ rating fields</description>
    <label>Manual Rating Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Program_Rating__c.field-meta.xml
<CustomField>
    <fullName>Program_Rating__c</fullName>
    <label>SUTQ Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Anniversary_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Anniversary_Date__c</fullName>
    <description>Program rating anniversary date gets populated based on the program effective date and expiration date.</description>
    <label>Rating Anniversary Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Effective_Date__c</fullName>
    <label>SUTQ Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/Rating_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Expiration_Date__c</fullName>
    <label>SUTQ Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CLQ_Program__c/fields/SUTQ_Current_Rating__c.field-meta.xml
<CustomField>
    <fullName>SUTQ_Current_Rating__c</fullName>
    <label>SUTQ_Current_Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Yes_No.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>List with 2 values: Yes and No</description>
    <masterLabel>Yes_No</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Schedule_Inspection_Rating_batch.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name             : Schedule_Inspection_Rating_batch
** Description      : 
** Version          : 1.0
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
**  Developer               Date            Version      Description
** Ankush R Relekar	     12/14/2021		      1.0	    Initial Build 
** 		
**************************************************************************************************************/
global with sharing class Schedule_Inspection_Rating_batch implements Database.Batchable<sObject>, Database.Stateful {
    
    global Integer recordsDeleted = 0;
    global static final String IN_PROGRESS = 'In Progress';
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        //list <CLQ_Program__c> ProgList=[select id,CLQ_Manual__c, CLQ_Program_Rating__c,CLQ_Current_Rating__c, CLQ_Current_Rating_Expiration_Date__c,  Rating_Effective_Date__c, Rating_Expiration_Date__c, Rating_Anniversary_Date__c, Program_Rating__c, SUTQ_Current_Rating__c,CLQ_Continuous_License_Status__c, CLQ_License_Registration_Status__c, CLQ_License_Issue_Date__c from CLQ_Program__c where Rating_Expiration_Date__c=:d];
        date d = system.today().addDays(60);
        return Database.getQueryLocator([select id,CLQ_Manual__c, CLQ_Program_Rating__c,CLQ_Current_Rating__c, CLQ_Current_Rating_Expiration_Date__c,  Rating_Effective_Date__c, Rating_Expiration_Date__c, Rating_Anniversary_Date__c, Program_Rating__c, SUTQ_Current_Rating__c,CLQ_Continuous_License_Status__c, CLQ_License_Registration_Status__c, CLQ_License_Issue_Date__c,(select id, RecordType.Name from Inspections__r where RecordType.Name='Onsite Visit Record Type') from CLQ_Program__c where Rating_Expiration_Date__c=:d]);
    }
    
    global void execute(Database.BatchableContext BC,List<CLQ_Program__c> scope){
        list<CLQ_Inspection__c> insplist=new list<CLQ_Inspection__c>();
        Map<String,List<CLQ_Inspection__c>> mapInspectLst = new Map<String,List<CLQ_Inspection__c>>();
        
        for(CLQ_Program__c prog:scope){
            system.debug('prog in scope:'+prog);
            if(prog.Inspections__r.IsEmpty()){
                CLQ_Inspection__c inspectionrecord = new CLQ_Inspection__c();
                inspectionrecord.RecordTypeId=Schema.SObjectType.CLQ_Inspection__c.getRecordTypeInfosByDeveloperName().get('Onsite_Visit_Record_Type').getRecordTypeId();
                inspectionrecord.CLQ_Program__c = prog.Id; 
                inspectionrecord.CLQ_Inspection_Owner__c = UserInfo.getUserId();
                inspectionrecord.CLQ_Inspection_Status__c = IN_PROGRESS; 
                insplist.add(inspectionrecord);
            } 
        }
        
        if(!insplist.isEmpty()){
            insert insplist;
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        system.debug('Rating_exp_date_batch - Finished!');
        
    }        
}